### ISSUE TITLE
crashing when generating new chunks in the end

### ISSUE THREAD

**Issue by Laialot** [paulevsGitch/BetterEnd#10]
full crash report is in this link: https://pastebin.com/zKLsmyjA

when i tried exploring the end to find the new biomes the game crashed, i tried erasing the DIM1 folder to generate a new end thinking the problem could be with chunk generation, up to the dragon fight everything was working, but as soon as i used the gateway to begin exploring the game crashed again.
i undersatnd this mod is in beta, so i mostly report this in case the problem is unknown and has a fix

**Comment by paulevsGitch** [comment]
Looks like biome registry is not initialized, did you use another mods or updated an old world?

**Comment by Laialot** [comment]
It's a world i began in 1.16 1
The mods i have that change biome generation are biomes you'll go, better nether, terrestria, traverse and cinderscapes

**Comment by paulevsGitch** [comment]
You can edit your level.dat in world folder with [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases/tag/v2.8.0-win) and replace the End biome source with "betterend:better_end_biome_source", then delete "region" and "poi" folders in DIM1. And make a backup first

![image](https://user-images.githubusercontent.com/17707380/98288209-91c4c480-1fb7-11eb-9d21-499faf666b09.png)

**Comment by paulevsGitch** [comment]
This bug is a result of wrong biome source. It will be fixed in next release. So, to fix it right now you can change your biome source manually. This will also work for old worlds

**Comment by Laialot** [comment]
Thank you for the response
I did as suggested and changed the biome source for the end from byg to betterend and i can now freely explore withour crashing
Thanks again

**Comment by paulevsGitch** [comment]
Fixed in 0.6.0
