### ISSUE TITLE
I can't open my end stone smelter on my friends modded aternos server

### ISSUE THREAD

**Issue by ShepBoi** [paulevsGitch/BetterEnd#100]
For some reason I can't open my end stone smelter on my friends server.
It's a Fabric 1.16.5 server
The mods installed on the server are:
Fabric API
Fabric Waystones
Astromine
Origins
Extra Origins
Pekhui
lithium
Croptopia
Cosmetic armour
Curios
Fabric Tailor
better nether
and of course better end.
On my client I have REI, litematica and canvas as well as their respective library mods

I'm not sure whats happening but I think its something to do with aternos as their servers have given us some very weird issues so far and we'll be switching to a server hosted by me in the near future hopefully but for now, this is very annoying and completely halts my progress.

My hardware config is (If this even matters)
Intel Core i5 6600K
Nvidia Geforce GTX 1070
2x16GB 2933MHZ DDR4
MS windows 10

**Comment by paulevsGitch** [comment]
After some research we found that Aternos use its own rewritten API, as it is unofficial it will not be supported and this issue will be closed
