### ISSUE TITLE
'ARrow of End Veil' [en_us]

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#101]
The *Arrow of End Veil* is incorrectly capitalized as *ARrow of End Veil* in en_us language.

![2021-02-23_12 00 49](https://user-images.githubusercontent.com/69029346/108900827-f3dd2000-75ce-11eb-93f4-1574b5f9dfe8.png)

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
