### ISSUE TITLE
Thallasium/Terminite can't be used in vanilla recipes, and tech mods can convert them into iron

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#105]
First off, I just want to say that tags are lovely and good for making mods play nicely together, and I absolutely appreciate your use of them in *Better End.* However, I have noticed one side effect with the addition of the Thallasium and Terminite ingots to c:iron_ingots specifically: technical mods such as *Tech Reborn, Astromine* and *Applied Energistics 2* can convert these metals into iron using various recipes. TR's grinder, Astromine's triturators and AE2's quartz grindstone can grind them into iron dust, which can then be cooked into iron ingots, and Astromine also lets them be made into iron plates and its unique tools.

In addition to this, vanilla recipes outside of the Smithing Table do not use the c:iron_ingots tag unless the end user makes them use it with a datapack, which means that Thallasium and Terminite cannot be used to make things like buckets, hoppers, pistons or minecarts the way that *Better Nether's* Cincinnasite can.

I wanted to bring this to your attention and open a discussion about it. My suggestion, while it makes assumptions as to your intentions for these metals, for a solution would be:
- Replace the vanilla bucket, hopper, piston, minecart, shears, compass, and the like recipes with ones that use the c:iron_ingots tag in the mod itself so that these metals can be used in these recipes without end user intervention via datapacks.
- If being able to convert these metals into iron is deemed unintentional, then prevent the above mods from being able to use Thallasium/Terminite ingots in recipes that create iron dusts, plates or Astromine's mining tool and mattock.
- Potentially, if the above is deemed unintentional, include with *Better End* Thallasium and Terminite dusts that TR's grinder, Astromine's triturators and AE2's quartz grindstone can produce instead of iron dust with these recipes, that can then be cooked into their respective ingots. Plates and Astromine's tools would be extra credit, not at all necessary.

**Comment by Bulldog83** [comment]
One thing: Terminite not iron equivalent, only Thallasium.

**Comment by saltyseadoggo** [comment]
Okay, gotcha. In that case, Terminite should probably be removed from this tag outright to prevent technical mods from seeing it as an iron equivalent.

**Comment by paulevsGitch** [comment]
Fixed in 0.9.5
