### ISSUE TITLE
Buggy lighting inside of menger sponges

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#106]
Menger sponges' inner faces turn almost pitch black when there are enough blocks next to it on a given side.

Placing a 3x3 of blocks above a menger sponge turns the bottom faces pitch black:
![2021-03-03_12 52 41](https://user-images.githubusercontent.com/69029346/109871203-cec85d00-7c1f-11eb-8506-86575ec4e8bb.png)
Placing a vertical 3x3 next to one turns the opposite side faces pitch black:
![2021-03-03_12 54 55](https://user-images.githubusercontent.com/69029346/109871247-dc7de280-7c1f-11eb-9623-9f340e008bd0.png)
This applies to both wet and dry menger sponges.

**Comment by paulevsGitch** [comment]
I think this is because this block is opaque and light engine calculations are wrong, I think if I will make it transparent to light it will be fixed

**Comment by paulevsGitch** [comment]
As this bug is related to MC rendering engine (and is not appearing on others) it will be postponed. Probably 1.17 will fix it automatically

**Comment by paulevsGitch** [comment]
Proper bounding boxes fix this

![2021-11-30_14 24 59](https://user-images.githubusercontent.com/17707380/144039272-0ea4462c-8424-4b5f-8604-799f27e35957.png)

**Comment by paulevsGitch** [comment]
Fixed in 0.12.5
