### ISSUE TITLE
Breaking wet menger sponge next to dry vanilla/menger sponge wets the sponge

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#107]
Breaking a wet menger sponge next to a dry vanilla sponge or a dry menger sponge turns either into their wet equivalent.

Steps to reproduce: Create a new world in Creative mode with only Better End and the Fabric API loaded, and do this:
![2021-03-03_12 59 55](https://user-images.githubusercontent.com/69029346/109871791-68900a00-7c20-11eb-9fbb-cc20f72cf979.png)
![2021-03-03_13 00 03](https://user-images.githubusercontent.com/69029346/109871794-6928a080-7c20-11eb-829f-a04d22fc17fe.png)
![2021-03-03_13 00 06](https://user-images.githubusercontent.com/69029346/109871795-69c13700-7c20-11eb-926e-93cc766b5cdd.png)

**Comment by paulevsGitch** [comment]
The reason is that wet menger sponge is waterlogged (to render water correctly) and when it breaks it tries to place water. It was "fixed" by fastly replacing water to the air, but there is enough time for other sponge to become wet, I will try to fix this

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
