### ISSUE TITLE
Crash on startup on 1.16.3

### ISSUE THREAD

**Issue by Moonflowey** [paulevsGitch/BetterEnd#11]
Hey, so, um, remember this issue with betternether? https://github.com/paulevsGitch/BetterNether/issues/123
Yeah, well, it seems to have returned in betterend with 0.50 lol. it just doesnt leave me alone

Can tell it is the same issue because the crash logs are almost identical:
https://justpaste.it/4hkjv

Fabric loader: 0.10.6 build 214 for 1.16.3
Fabric API: 0.25.0 build 415

**Comment by paulevsGitch** [comment]
This is similar issue as before - incorrect blockstate name, we will fix that

**Comment by paulevsGitch** [comment]
Fixed in 0.6.0
