### ISSUE TITLE
Biome Megalake spawning but no Megalakestructure

### ISSUE THREAD

**Issue by Blaueschmied** [paulevsGitch/BetterEnd#110]
Hi, I think I found a little bug!
Your Megalake biome is spawning, but the name-giving Megalake itself isn't.
I teleported to different Megalake structures through the locate command, but they are not spawning.

![2021-03-06_09 21 25](https://user-images.githubusercontent.com/59196184/110200291-754d7180-7e5d-11eb-928d-db73462659a7.png)

**Comment by paulevsGitch** [comment]
This is a problem with your structure cache (something similar happened on our discord), you can join and see how it was solved

**Comment by Fireface677** [comment]
I kinda solved it by deleting bin folder. Maybe this could help you too.
