### ISSUE TITLE
Textures on blocks aren't transparent

### ISSUE THREAD

**Issue by 1-800-SAT-ANIC** [paulevsGitch/BetterEnd#113]
Hi, this is my first time using the site so I'm not sure what all I need to include in the post, but I am running on PC on Forge 1.16.5 with no other mods/resources/texture packs. I do have Optifine with the built in shaders if that may be what is causing the issue?

![2021-03-10_13 52 45](https://user-images.githubusercontent.com/80429071/110704986-95a56500-81aa-11eb-8916-d70c61694de6.png)
![2021-03-10_13 56 59](https://user-images.githubusercontent.com/80429071/110704993-976f2880-81aa-11eb-8b08-c720e10ec8c9.png)
![2021-03-10_13 52 10](https://user-images.githubusercontent.com/80429071/110705000-9a6a1900-81aa-11eb-86d6-21cae1bf194d.png)
![2021-03-10_13 50 31](https://user-images.githubusercontent.com/80429071/110705006-9ccc7300-81aa-11eb-9752-059a1722a693.png)
![2021-03-10_13 48 35](https://user-images.githubusercontent.com/80429071/110705009-9e963680-81aa-11eb-9698-347281a34a17.png)

**Comment by paulevsGitch** [comment]
1) This is a shaderpack issue, not a BetterEnd issue, you can use another shaders.
2) This is a Fabric mod tracker, not Forge mod tracker

**Comment by theishiopian** [comment]
other than that not a bad first post. next time, be sure you research a bit more.
