### ISSUE TITLE
Any tutorial on this mod/how to use it?

### ISSUE THREAD

**Issue by Begnom** [paulevsGitch/BetterEnd#114]
By "How to use it" i mean how to get the stuff that are there and what kind of stuff the mod adds and a showoff of the crafting recipes, since the mod adds a lot of stuff, also a new ore from what i know.

**Comment by RDKRACZ** [comment]
Just create a test world in creative and fly for 10 minutes in the End, also use REI.

**Comment by Begnom** [comment]
I already did, i think i wrote the question wrong. I can't seem to find any tutorial on the mod, i know the terrain and the other things  but i have no idea how the ender ore works etc. that's why i wanted to find a tutorial on how to get the new armors and stuff. Also, what's REI?

**Comment by RDKRACZ** [comment]
> what's REI?

You play modded mc and don't know this? https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items
JEI if you use forge

**Comment by Begnom** [comment]
Ohhhh this mod, sorry but i don't know this perticular mod. Thanks for the help :)
