### ISSUE TITLE
Suggestion for giant tree structure planting

### ISSUE THREAD

**Issue by knightsofNit** [paulevsGitch/BetterEnd#117]
![image](https://user-images.githubusercontent.com/80883429/111596464-32639600-879b-11eb-9109-0952e88801c6.png)
so i have been explained a little on this and would like to know if it would ever be possible to make this something that could be grown with say a 6x6 of saplings to do it so it didn't happen unintentionally

**Comment by paulevsGitch** [comment]
For the game balance this structure will not be plantable/growable
