### ISSUE TITLE
I want to ask if I can repost it to www.mcbbs.net

### ISSUE THREAD

**Issue by lkqyyds** [paulevsGitch/BetterEnd#118]
can i Reprint it to mcbbs.net

**Comment by paulevsGitch** [comment]
What do you want to reprint?

**Comment by lkqyyds** [comment]
The mod i want to reprint is betterend. And mcbbs is very famous in China. This and curseforge will be the only download channel for this module. And provide users with free download and mod introduction. And can i reprint?

**Comment by paulevsGitch** [comment]
You can publish it, but all download links (except mirrors) should be to the Curseforge files
