### ISSUE TITLE
End Fish Client Crash

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [paulevsGitch/BetterEnd#12]
When trying to pick up an end fish with a water bucket, the client crashes as there seems to be no related item for these fish in a bucket.
[crash-2020-11-07_12.28.28-client.txt](https://github.com/paulevsGitch/BetterEnd/files/5504656/crash-2020-11-07_12.28.28-client.txt)

**Comment by paulevsGitch** [comment]
Fixed in 0.6.0
