### ISSUE TITLE
Eternal Portal frames shouldn't be broken by the Ender Dragon.

### ISSUE THREAD

**Issue by SatDog92** [paulevsGitch/BetterEnd#120]
I use Fabric v.1.11.1 on MC 1.16.5 and API v.0.30.3, and mod version is v.0.9.1-pre-1.16.4/5

When i finally reached the End, i noticed that an Eternal Portal structure was right below my obsidian platform spawn (yes i spawned underground), but since i was busy preparing for the battle (and preparing hundreds of bottles), i let the Ender Dragon destroy the whole structure. A bit of a bummer.

I feel like there could be two solutions: since the Eternal Frames and the Eternal Pedestals are as indestructible as Bedrock and End Portal elements, they should be put in the list of blocks that cannot be broken by the Ender Dragon's flight (a bit like the End Portal Frame and the End Portal itself) 
Another solution is to prevent the portal structure from spawning in the central island (i liked the idea of having the portal spawning near my spawn, though, and if possible making them indestructible feels better).

One side aspect: i also feel that they should work a bit like Nether Portals. In Creative, since it is possible to break the structure, the mechanics break too: if you break a portal from one side, you cannot travel from the other side anymore, while Nether portals just create one new portal nearby the one that was destroyed by the other side. A bit like obsidian platforms, can't they replace the previously broken portal in order to prevend more portals from spawning? Just an idea, but i realize this one might be convoluted, and in Survival this is useless anyway, since these structures are unbreakable anyway.
EDIT: well, something similar was written [here](https://github.com/paulevsGitch/BetterEnd/issues/99), but felt appropriate to include this, since there is the possibility that the Ender Dragon might destroy the portal if i respawned her after activating that one portal.
EDIT2: i forgot to add: the Ender Dragon also destroys ore and Flavolite veins. I don't feel like it's right, since they're made of end stone and Flavolite (the stone, not the building bricks, even the vanilla End Stone Bricks are destroyed by the Ender Dragon) is part of the island.

**Comment by paulevsGitch** [comment]
Eternal portals shouldn't generate near central island, this was fixed some time ago, is you world old?

**Comment by SatDog92** [comment]
> Eternal portals shouldn't generate near central island, this was fixed some time ago, is you world old?

No no, it's pretty recent, i have never generated chunks in The End and i used the latest mod version from the beginning. To be sure, i tested again with a fresh world and yes, a portal spawns right above my obsidian platform (the first time it was full, this time was broken, but the portal does indeed spawn). Seed i used is -4617598398700268207 and two screenshots are below:

![end-above](https://user-images.githubusercontent.com/56725716/111958660-cb711480-8aed-11eb-9160-74fae535eb6d.png)
![end-eternal-portal](https://user-images.githubusercontent.com/56725716/111958664-cca24180-8aed-11eb-81f9-285e5a7954dc.png)

I'm not sure if the unfortunate morphology of the island causes this (you can see one obsidian pillars floating over the void, yikes), but this does happen in this world. I'll also post a log in case it's needed:
[betterendlog.log](https://github.com/paulevsGitch/BetterEnd/files/6180502/betterendlog.log)

Not sure how it works, but maybe the radius lenght where the portal doesn't spawn should be increased? Usually, the obsidian platform spawns over the void, but sometimes it spawns inside the island (thank god because i hate it when it spawns over the void).

**Comment by paulevsGitch** [comment]
I increased radius of structure spawning and make its important blocks dragon-immune

**Comment by paulevsGitch** [comment]
Added in 0.9.2
