### ISSUE TITLE
[Worldgen Bug] Conformation of terrain are randomized every time game is restarted.

### ISSUE THREAD

**Issue by SatDog92** [paulevsGitch/BetterEnd#123]
I use Fabric v.1.11.1 on MC 1.16.5 and API v.0.30.3, and mod version is v.0.9.1-pre-1.16.4/5

First, i'll note something: this freaky worldgen bug happens with this mod alone installed, but i used Xaero's World Map after testing, in order to give an idea of what i'm talking about.

In Betterend v.0.9.1-pre, the conformation of terrain features are randomized everytime the game is restarted (yeah, the game, not the world). Luckly, this doesn't happen to biomes, but the result of this bug are pretty damn jarring. I'll describe this throug my use of Xaero's World Map.
-[Image 1](https://user-images.githubusercontent.com/56725716/112465504-19dc1880-8d65-11eb-9c52-ec3034973427.png): this is how the terrain looks before restarting the game;
-[Image 2](https://user-images.githubusercontent.com/56725716/112465511-1b0d4580-8d65-11eb-98d8-71adcc6f63e1.png): this is how the terrain looks before restarting the game and after loading new chunks. You can see these "cuts" that generated a bit farther in newly loaded chunks after a new game session, as if the mod tried generating these structures again and not "finishing" generating them.
Examples of how bad this looks: [example 1](https://user-images.githubusercontent.com/56725716/112465776-61fb3b00-8d65-11eb-8f03-2b74ae1ab030.png) and [example 2](https://user-images.githubusercontent.com/56725716/112465781-64f62b80-8d65-11eb-90ad-245c5716bb20.png). This happens with all the custom terrain features, all the trees included. I don't know if this depends from the Minecraft's experimental worldgen feature, but i wish this didn't happen, i was having fun with this mod. The only temporary solution is by using a tool for deleting individual chunks and regenerating these biome areas between islands whole and not broken, if this doesn't feel right. Any way to fix this?

**Comment by paulevsGitch** [comment]
After dome research looks like this is a bug of MC itself - chunk have wrong state when they are saved/loaded. It is potentially possible to solve, but it will require large amount of work

**Comment by paulevsGitch** [comment]
Summary - bug is a core MC bug related to wrong chunk status saving and multithreading, looks like it will be not possible to fix. Probably 1.18 or later this bug will be fixed from MC itself
