### ISSUE TITLE
Outer leaves / fur blocks make coral fan sounds instead of leaf sounds

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#124]
Tenanea Outer Leaves, Glowing Pillar Leaves, Mossy Glowshroom Fur and Blue Vine Fur are all either leaf blocks or similar (I do not know what 'fur' means for the fur blocks in this case), but they make coral fan sounds when placed or broken instead of leaf block sounds. This is especially noticeable if one sets out to harvest tenanea leaves for saplings, and is constantly hearing the two differing breaking sounds while doing so.

**Comment by paulevsGitch** [comment]
I will replace sounds to more "plant like"

**Comment by paulevsGitch** [comment]
Added in 0.9.2
