### ISSUE TITLE
Helix tree leaves have no effective tool

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#125]
Helix tree leaves cannot be broken faster than breaking them by hand making use of a hoe or shears, like other leaf blocks. This can be tested by placing some down and attempting to break them with a hoe, shears, axe, pickaxe and shovel, and comparing to the speed of breaking them by hand.

**Comment by paulevsGitch** [comment]
If I remember correctly this bug was [already fixed](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/blocks/HelixTreeLeavesBlock.java#L39) in dev version

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
