### ISSUE TITLE
Leaf blocks drop themselves with Fortune enchanted hoe

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#126]
Breaking Tenanea, Pythadendron, Lacugrove or Dragon Tree Leaves with a hoe enchanted with Fortune does not amplify the drop rate for sticks and saplings; instead, it behaves like Silk Touch, and drops the leaf block as an item. Breaking these blocks with a pickaxe, shovel or axe enchanted with Fortune drops sticks or saplings, presumably at the regular, non-Fortune rate, as per vanilla behaviour for leaves.
This can be tested by placing some of any of the above leaf blocks, obtaining any hoe, running `/enchant @p fortune`, and then breaking the leaves with the hoe in survival mode.

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
