### ISSUE TITLE
0.9.2 Server won't start

### ISSUE THREAD

**Issue by unlikexd** [paulevsGitch/BetterEnd#127]
Hello there! I have an issue when starting the server with 0.9,2 BetterEnd version on. An "Exception in server tick loop" pops up. However, the 0.9.1 version works perfectly. There's probably no problem with compatibility with other mods, because just a standalone 0.9,2 version mod (w/ fabric-api) won't launch either. The thing is, I really want to use the new end generator along with custom portal and pillars and no-void feature. So, I hope there is a solution to this! Linking [crash log](https://pastebin.com/Y0c4i3nh) and a[latest log file](https://pastebin.com/0v0vNLqg)

**Comment by paulevsGitch** [comment]
There is no BE 0.9.2, the latest version is 0.9.1
