### ISSUE TITLE
[Bug?] Chorus Plants on generator.json

### ISSUE THREAD

**Issue by SatDog92** [paulevsGitch/BetterEnd#129]
I use Fabric v.1.11.1 on MC 1.16.5 and API v.0.30.3, and mod version is v.0.9.1-pre-1.16.4/5

In the generator.json file, setting "changeChorusPlant" to false reverts the chorus's graphics but not the flower's hitbox (in this way, the graphics do not match the hitbox), ~~and setting "removeChorusFromVanillaBiomes" to false doesn't enable them on already created worlds (not chunks already generated, but the world itself), it's as if it's permanently enabled or disabled for these.~~ It's not a big deal but i thought it would be nice if this was fixed or changed.

**Comment by paulevsGitch** [comment]
I will fix the hitbox, but "removeChorusFromVanillaBiomes" is world independent - it removes plants only on world loading if enabled, so the same world will have chorus plants after regeneration or in new chunks (game need to be restarted to apply config changes)

**Comment by SatDog92** [comment]
> "removeChorusFromVanillaBiomes" is world independent

I know how that works, but i was under the impression that the setting didn't work for already created worlds, but after doing more tests, i found out it was just bad luck. Weird because the bad luck fueled this confirmation bias.

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
