### ISSUE TITLE
[Cheese or Bug?] Eternal Crystal can be removed from Eternal Pedestals and "recycled" for the others

### ISSUE THREAD

**Issue by SatDog92** [paulevsGitch/BetterEnd#130]
I use Fabric v.1.11.1 on MC 1.16.5 and API v.0.30.3, and mod version is v.0.9.1-pre-1.16.4/5

Basically, when the Eternal Crystals are placed on the Eternal Pedestals (and emit the beacon-like beam signing that it's special behavior), they can be removed after activating the pedestal's light. In this way, only one Eternal Crystal is needed to open one portal: you just need to put a crystal on a pedestal, remove it and repeat this process on the others.

Is this intended behavior? While i feel like Ender Ores could be just a little bit more common, but this "cheese" just removes the point of their rarity.

One idea is to have them be placed and "sealed" on there, with no way to recover them. Another idea is to have them sealed only once the portal is open, but in this way the pedestal's light should go away, and that's more code and i don't know how necessary is that.

**Comment by paulevsGitch** [comment]
Looks like this is a bug, but the whole portal system will be redone in the next release, so it will be fixed

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
