### ISSUE TITLE
[Bug] Silk Moth deletes the lead it is tied to after restarting the world.

### ISSUE THREAD

**Issue by SatDog92** [paulevsGitch/BetterEnd#131]
I use Fabric v.1.11.1 on MC 1.16.5 and API v.0.30.3, and mod version is v.0.9.1-pre-1.16.4/5

Looks like that when Silk Moths make leads they're tied to completely disappear after quitting and restarting the world, whether the lead is held by the player or by a fence. Images below:
-[Before restarting the game](https://user-images.githubusercontent.com/56725716/113022560-07a71380-9185-11eb-8c7f-4d53cde7d8d0.png);
-[After restarting the game](https://user-images.githubusercontent.com/56725716/113022564-08d84080-9185-11eb-966b-9e126eca33cd.png).

The Silk Moth is the only leashable mob that does this.

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
