### ISSUE TITLE
Emerald ice variants drop even without silk touch

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#132]
All three variants of emerald ice- regular, dense and ancient- do not require silk touch to drop when broken in the same manner as vanilla ice, compressed ice and blue ice blocks. The three emerald ice types drop when broken with any tool or by hand. If they are supposed to behave identically to vanilla ice, compressed ice and blue ice, they should only drop with silk touch.

This bug also means that breaking emerald ice without silk touch while a block is beneath it will both generate water and drop the emerald ice block, which makes no sense.

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
