### ISSUE TITLE
Wall signs cannot be placed without block below

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#133]
The nine signs added by this mod cannot be attached to the side of a block unless a block is beneath the space that the player is trying to place it into. The block below the sign can be removed after the sign is placed, and the sign remains in place, but the block is needed to place it down.

![2021-03-30_22 54 31](https://user-images.githubusercontent.com/69029346/113096972-07ba0a00-91ab-11eb-9270-5d77dd2230a6.png)
![2021-03-30_22 55 18](https://user-images.githubusercontent.com/69029346/113096976-0852a080-91ab-11eb-8405-22e788a42cdd.png)

**Comment by paulevsGitch** [comment]
I fixed that in dev code a bit earlier

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
