### ISSUE TITLE
End Stone Smelter recipes appear broken in vanilla blast furnace recipe book

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#134]
If the player unlocks the recipes for any of the alloying or double ore processing recipes unique to the End Stone Smelter and then views one in a regular blast furnace, the second input item appears under the fuel item.

This can be tested by cooking the two thallasium ore to three thallasium ingot recipe in an End Stone Smelter, taking the result out in survival mode to unlock the recipe, and then viewing it in the recipe book in a regular blast furnace.

Perhaps the End stone smelter should use its own recipe category that inherits all of the blast furnace recipes on runtime (for compatibility), and then show a recipe book for its own recipes, so the vanilla blast furnace recipe book doesn't show them?

![2021-03-30_22 59 33](https://user-images.githubusercontent.com/69029346/113097618-13f29700-91ac-11eb-8416-ba72e596b253.png)

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
