### ISSUE TITLE
Anvils can have their damage refreshed by breaking and replacing them

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#135]
The thallasium, terminite and aeternium anvils using a blockstate for their destruction value instead of three separate blocks like the vanilla anvil means that the player can break any of these anvils when they are damaged and place them back down to 'repair' them, effectively cheating around needing to replace the anvil.
This could be resolved by introducing new items for each damaged variant of these anvils like the vanilla anvil that place their respective blocks with the appropriate `destruction` value, and then having these anvils drop the correct anvil based on their `destruction` value when broken. They could alternatively drop some blocks and ingots of their respective metals when broken when not at `destruction = 0`, less of each the more damaged they are, to avoid needing to make new items.

**Comment by paulevsGitch** [comment]
I think I know a better way than adding more items

![2021-04-21_21-39-53](https://user-images.githubusercontent.com/17707380/115604758-683ff100-a2ea-11eb-98b5-1468db9b3251.png)

**Comment by paulevsGitch** [comment]
Added in 0.9.2
