### ISSUE TITLE
[Enhancement?] Growing End Grass types by checking a 3x3x3 box?

### ISSUE THREAD

**Issue by SatDog92** [paulevsGitch/BetterEnd#137]
I use Fabric v.1.11.1 on MC 1.16.5 and API v.0.30.3, and mod version is v.0.9.1-pre-1.16.4/5

One thing i noticed about growing End Grass types (all of them) is that it's pretty limited: while growing vanilla Nylium is omni-directional and checks for near Nylium blocks in a 3x3x3 blocks area, while the End Grasses only checks if there is one next to it in the same x or z coordinate.

I'm posting images in order to show what i am trying to explain: 
[Vanilla Nylium](https://user-images.githubusercontent.com/56725716/113858476-13f22880-97a4-11eb-8b4c-7bb1780b117a.png);
[All End Grass](https://user-images.githubusercontent.com/56725716/113858482-148abf00-97a4-11eb-9c40-6cd496f77a60.png).

The green circles indicates where bone meal can be used, and the red crosses indicate where it cannot be used

Is it possible to apply the bone meal growth logic of vanilla Nylium to all End Grass types? I was doing something crazy and turning a Mushroom Fields biome into one of these End biomes, but without the Nylium logic this is going to be unpractical (having to grow grass and use Silk Touch to place them manually might be a nightmare, while vanilla Nylium doesn't need this)

**Comment by Fabrieze** [comment]
Piggybacking off your post a little to ask a question, sorry! 

Are you able to grow/spread The End biome grass/moss/phylium/what-have-you? I thought it would be possible but it seems I can't use bonemeal at all, implying the biome tiles are a finite resource that can only be retrieved by silk touch. They're so pretty, so it's a bit of a bummer.

**Comment by paulevsGitch** [comment]
@Fabrieze, the answer is directly in the suggestion - you can grow End grasses with bonemeal

**Comment by Fabrieze** [comment]
> @Fabrieze, the answer is directly in the suggestion - you can grow End grasses with bonemeal
 
Yup! I see that. But it doesn't work for me, so I was asking rather if there was something I'm doing wrong. I set up end stone next to an end block as OP had done, but it doesn't do anything.

**Comment by SatDog92** [comment]
If you're talking about "phylium", you're probably talking about BYG (Oh the Biomes you'll go) blocks! Because "phylium" is a thing from BYG, and yeah, the "phylium" blocks from BYG do not indeed work at all (~~like most things in that mod~~). If you press F3+H, you'll see the block ID, and you will also see what mod that block is part of. If you're not using BYG, then you should update BetterEnd.

**Comment by paulevsGitch** [comment]
Added in 0.9.2
