### ISSUE TITLE
[Suggestion] Make End woods and plants fiammable by lava and fire

### ISSUE THREAD

**Issue by SatDog92** [paulevsGitch/BetterEnd#139]
I use Fabric v.1.11.1 on MC 1.16.5 and API v.0.30.3, and mod version is v.0.9.1-pre-1.16.4/5

Realized this after trying to burn away the leaves from the Helix Trees in order to get rid of them quickly, which didn't work. Tested on almost all plants, and none of them burns away, while some of them catching fire for a short time (Helix leaves catch fire, while Lacugrove leaves do not at all, for example). This might be intended but i don't know if these plants in the End should be immune to fire and lava, even if there is no lava in The End (i don't know about the "lore").

When it comes to trees: in order to avoid weird things, the "leafy" trees could burn away after catching fire, like ordinary overworld wood/leaf types. This means that elements from "shroomy" trees like Mossy Glowshroom, Umbrella Tree and Small Jellyshroom shouldn't burn away, but they could catch fire anyway like the vanilla mushroom blocks, unless one doesn't want to make wood builds near lava with these mushroom wood types in order to avoid annoyances.

On the other hand, some End Grass types (Chorus Nylium Pink Moss, End Moss,) catch fire from lava while they do not burn away either: in order to make it more consistent with vanilla grass blocks (which do not even catch fire from lava in order to avoid fire griefing), i don't think all the End Grass types should catch fire either.

Between making these elements vulnerable to fire and lava, and making them immune, i would go with the first option, but the choice isn't mine here, it's just an enhancment suggesion.

**Comment by paulevsGitch** [comment]
Added in 0.9.2
