### ISSUE TITLE
Conflict with Falling Leaves

### ISSUE THREAD

**Issue by Fourmisain** [paulevsGitch/BetterEnd#14]
Refering to the comments below https://github.com/RandomMcSomethin/fallingleaves/issues/2#issuecomment-724280523, quote:

> **NekoKera**:
> I've done some more testing and I can confirm that FallingLeaves does work on servers when only present on the client-side; however, I had issues running in combination with my server mod list, so I started going down testing it with each mod. What I discovered is that Falling Leaves does not work when BetterEnd is present on the server and client. BetterEnd (using the current most version) does work with FallingLeaves on Single Player, but this is not the case for Multiplayer, as the leaves do not fall from the trees (even in the overworld).

I did some debugging of [Falling Leaves](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric) 1.1 (the 1.16.4 git branch) using BetterEnd 0.5.2 and found that [randomDisplayTick](https://github.com/RandomMcSomethin/fallingleaves/blob/900db0b851ec63c102377471d85398dcdf942b8b/src/main/java/fallingleaves/fallingleaves/mixin/LeafTickMixin.java#L30) and [world.addParticle](https://github.com/RandomMcSomethin/fallingleaves/blob/900db0b851ec63c102377471d85398dcdf942b8b/src/main/java/fallingleaves/fallingleaves/mixin/LeafTickMixin.java#L86) is called like normal with reasonable positions and colors and that doesn't change when BetterEnd is installed on both server and client, but what does change is that the Factory's [createParticle](https://github.com/RandomMcSomethin/fallingleaves/blob/4c2327e837f50dc2de5e65d12450230daa56894f/src/main/java/fallingleaves/fallingleaves/particle/FallingLeafParticle.java#L74-L76) is for some reason never called, despite being [registered](https://github.com/RandomMcSomethin/fallingleaves/blob/900db0b851ec63c102377471d85398dcdf942b8b/src/main/java/fallingleaves/fallingleaves/client/FallingLeavesClient.java#L23-L24).

**Comment by paulevsGitch** [comment]
Does Falling Leaves work with server worlds if BetterEnd is not installed?

**Comment by Fourmisain** [comment]
Yes, that's the thing, I don't see what is conflicting, but apparently something is

**Comment by paulevsGitch** [comment]
I think the reason (probably) is that Falling Leaves mixin into the sever side, and this is can stop working if the server has other mods (that can also add particles, like BetterEnd), but this will work for singleplayer as it runs on a dedicated server. Leaves can use a client-side mixin, this probably can fix this issue

**Comment by Fourmisain** [comment]
I was already debugging it with these changes https://github.com/Fourmisain/fallingleaves/commit/7a36bec6717a8c54faee16a7d79a546b1616738b that should ensure everything is run client side, but it's the same story.

**Comment by paulevsGitch** [comment]
[This function](https://github.com/Fourmisain/fallingleaves/blob/main/src/main/java/fallingleaves/fallingleaves/mixin/LeafTickMixin.java#L21) is public, but as I know all mixin functions should be private (and have unique names to prevent compatibility issues, for example "flDisplayTick"). Can this be one of issue sources?

**Comment by Fourmisain** [comment]
Just tested it (and some different stuff), no difference sadly.
I really want to know what happens (or doesn't happen) between `world.addParticle` and `createParticle`

**Comment by Fourmisain** [comment]
Okay, after way too much time eliminating options I brought it down to 2 lines.
If these lines are commented out of BetterEnd, Falling Leaves works again:
https://github.com/paulevsGitch/BetterEnd/blob/70f5e3e02457cc0e5dafea8fede12d05c0f26064/src/main/java/ru/betterend/world/biome/BiomeMegalakeGrove.java#L19
https://github.com/paulevsGitch/BetterEnd/blob/c3a7a59d785bddc51523e2f842ce13ed2882619d/src/main/java/ru/betterend/world/biome/BiomeFoggyMushroomland.java#L21

I tried upping the probability to 1, but that had no effect.
No real idea where to go from here.

**Comment by Fourmisain** [comment]
Took a deeper dive and found that this is (unsurprisingly?) a Registry issue of some kind.
Here's a mocked up log of what happens in multiplayer:

> `Registry.register(Registry.PARTICLE_TYPE, id("falling_leaf"), FabricParticleTypes.simple())`
> -> FabricParticleTypes$1@451b7faf
> ...
> entering ParticleTypes.createParticle()
> parameters.getType() = FabricParticleTypes$1@451b7faf
> `Registry.PARTICLE_TYPE.getRawId(parameters.getType())` -> -1
> entering SimpleRegistry.getRawId()
> {..., FabricParticleTypes$1@89741e2=>72, ..., FabricParticleTypes$1@12e56e82=>73, ...}

So at first, the falling leaf particle type is registered, later ParticleTypes.class tries to create particles added to the world.
It does get the previously registered leaf type and then looks up it's id in the Registry.
Looking inside the registry however shows exactly 2 `FabricParticleTypes` (I left out the vanilla types), neither of which are the falling leaf, so the id is -1 and the particle is never created.

That means at some point the Registry was... overwritten? The leaf forgotten?
In singleplayer (in the menu even) there are 3 `FabricParticleTypes`.

I can only guess that there is some kind of server-client synchronization of ids and the server gets the last word.
That would make some sense since biomes, which are server side, contain `BiomeDefinitions` which contain `ParticleTypes`, so the "server particle types" govern over the client ones - and that only happens if there is are discrepancies, hence commenting out those 2 lines "fixes" it? Still only guessing...

This gets us no closer to an understanding or a solution, I wish somebody who understood this stuff could take a look at it.
Do you think this might be a fabric issue?

**Comment by paulevsGitch** [comment]
Actually this is not a fabric issue as these particles don't exist on server, and synchronization server--client overrides them. I think there are 2 solutions - register particles after all other particles (problematic) and assign them large numerical ID manually (something like 4000 or 255)

**Comment by Fourmisain** [comment]
> and synchronization server--client overrides them

Wait, so are you saying there actually is such synchronization? Of particle types?

> particles don't exist on server

But when they don't, how are they being synchronized?
I mean it's clear the particles themselves aren't server-side, but it looks like the particle _types_ are - at least in this specific case, because they are part of biome definitions, right?

>  assign them large numerical ID manually

That was a really nice idea that I took way too long to figure out again (tried all kinds of Mixins into SimpleRegistry) until I found `register` has this variant:
`FALLING_LEAF = Registry.register(Registry.PARTICLE_TYPE, 126, "fallingleaves:falling_leaf", FabricParticleTypes.simple());`
It did successfully change the `rawId` to 126, but when entering multiplayer the id was missing, so it's not that ids are being overwritten, it seems to completely replace the registry.

Which basically only leave the options to register at a later point and/or try to find out where this synchronization happens so that it could maybe be fixed (by making it only overwrite ids, not replace the whole thing).

I don't really understand your reasoning why it's not a fabric issue, though I also don't really know what it is fabric can and does do.
However, to me, Registry synchronization seems like something that would only be relevant in modded Minecraft, since Vanilla only allows connections with perfect version matches and so both client and server would have the same ids anyways because they're built this way, right?

Doesn't fabric do some kind of registry remapping?
Like [here](https://github.com/FabricMC/fabric/blob/c29304db6ad616cec5862fc5b7ac3a89ef9bd3f9/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/MixinIdRegistry.java) it mixes into SimpleRegistry and there's [RegistryIdRemapCallback](https://github.com/FabricMC/fabric/blob/ff71903321aa812ab21ce688efdf6aa916669a3d/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/api/event/registry/RegistryIdRemapCallback.java).
Even more related, there's [RegistrySyncManager](https://github.com/FabricMC/fabric/blob/5f10696617898a8bdb1139099681b3a71d1e2619/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager.java) which might actually do the synchronization?

**Comment by Fourmisain** [comment]
I'm asking about fabric because I'm thinking about opening an issue there, so I want to verify whether it's actually related to fabric.

**Comment by Fourmisain** [comment]
After reiterating, I think I understand your comment a lot better now, I'm pretty sure I misinterpreted what you are saying, so I'm editing my reply

**Comment by paulevsGitch** [comment]
>It did successfully change the rawId to 126, but when entering multiplayer the id was missing, so it's not that ids are being overwritten, it seems to completely replace the registry.
>
>Which basically only leave the options to register at a later point and/or try to find out where this synchronization happens so that it could maybe be fixed (by making it only overwrite ids, not replace the whole thing).

This looks like an issue. I don't know is it on the Fabric side or not, but I think they can fix it. You can try to report it on Fabric GitHub, probably then they can provide good solution for you or fix this bug

**Comment by Fourmisain** [comment]
Thanks, will do!
Not before consulting my pillow though.

**Comment by Fourmisain** [comment]
This should now be fixed with https://github.com/FabricMC/fabric/pull/1179, in the fabric API 0.26.3 release
