### ISSUE TITLE
Custom composters can insert bone meal into golden hoppers

### ISSUE THREAD

**Issue by haykam821** [paulevsGitch/BetterEnd#145]
Despite [golden hoppers](https://github.com/haykam821/Golden-Hoppers) using vanilla functionality to prevent certain items from being transferred from inventories, they still can receive bone meal from this mod's custom composters. This is unlike vanilla composters which properly prevent the composter from being emptied.

**Comment by paulevsGitch** [comment]
Composters are not inserting items anywhere - they don't use ticks, all item code is in hopper class. Also all composters extending vanilla composter. In sum, this means that this bug is not on BE side
