### ISSUE TITLE
End EnumProperty crash (Threaded Anvil Chunk LargeOakTrunkPlacer)

### ISSUE THREAD

**Issue by profjb58** [paulevsGitch/BetterEnd#146]
**Quick disclaimer**
Better end isn't named in the crash log but we are running the pack on the latest version of AOF3 with a few additional mods on-top (https://github.com/The-Tiny-Taters/TTTM-AOF). None of these add trees / wood into the end biome though so i'm assuming this is an issue related to better end generation possibly not caused by The Better End mod alone, If it's too vague feel free to close though

**Log file**: https://gist.github.com/profjb58/ded245b5ed2c393c0bd8e429e8fb0f3e
**Crash report**: https://gist.github.com/profjb58/327b81d301bfc39afae190a138211551

**Comment by profjb58** [comment]
Guess next steps would be to just test with better end on it's own and see if the issue is reproducible just from exploring

**Comment by paulevsGitch** [comment]
>Cannot set property

Means that property of block is missing in its class. As I can see Jellysquid mods in the list - they probably is the real reason of this bug as one of their optimisation is deleting block data from memory. Another mod that changes the End in you list is BYG, so BE is not only one mod with end generation. I actually couldn't see anything relative to BE in logs, so I will close this
