### ISSUE TITLE
0.9.3 Crash on cave biome generation

### ISSUE THREAD

**Issue by Ninonsand** [paulevsGitch/BetterEnd#148]
Hello. 
Whenever I try and travel away from the main end island or use a porter after defeating the dragon I receive the following crash report:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/28/21 2:55 PM
Description: Feature placement

java.lang.NullPointerException: Feature placement
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.8)
	at net.minecraft.world.biome.source.BiomeArray.be_setBiome(BiomeArray:1037)
	at ru.betterend.world.features.terrain.caves.EndCaveFeature.setBiome(EndCaveFeature.java:120)
	at ru.betterend.world.features.terrain.caves.EndCaveFeature.lambda$setBiomes$3(EndCaveFeature.java:114)
	at ru.betterend.world.features.terrain.caves.EndCaveFeature$$Lambda$10354/75693472.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at ru.betterend.world.features.terrain.caves.EndCaveFeature.setBiomes(EndCaveFeature.java:114)
	at ru.betterend.world.features.terrain.caves.EndCaveFeature.place(EndCaveFeature.java:54)
	at ru.betterend.world.features.terrain.caves.EndCaveFeature.generate(EndCaveFeature.java:28)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:55)
	at net.minecraft.world.gen.feature.DecoratedFeature.method_30384(DecoratedFeature:23)
	at net.minecraft.class_2988$$Lambda$8869/1010108531.accept(Unknown Source)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.minecraft.world.gen.feature.DecoratedFeature.generate(DecoratedFeature:22)
	at net.minecraft.world.gen.feature.DecoratedFeature.generate(DecoratedFeature:14)
	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature:55)
	at net.minecraft.world.biome.Biome.generateFeatureStep(Biome:373)
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator:220)
	at net.minecraft.world.chunk.ChunkStatus.method_12151(ChunkStatus:89)
	at net.minecraft.class_2806$$Lambda$2212/382110147.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus.mde2b25a$lambda$injectLightmapSetup$1$4(ChunkStatus:546)
	at net.minecraft.class_2806$$Lambda$2213/302984430.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:219)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:568)
	at net.minecraft.class_3898$$Lambda$8744/1639238111.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:562)
	at net.minecraft.class_3898$$Lambda$8730/1665139061.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.class_3900$$Lambda$8743/418596109.run(Unknown Source)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:94)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:137)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Feature --
Details:
	Id: minecraft:decorated
	Config: < class_2986 [betterend:round_cave | [minecraft:chance net.minecraft.class_3297@7d4e188d]] >
	Description: < class_2988 [minecraft:decorated] >
Stacktrace:
	at net.minecraft.class_1959.method_8702(class_1959.java:376)
	at net.minecraft.class_2794.method_12102(class_2794.java:220)
	at net.minecraft.class_2806.method_12151(class_2806.java:89)
	at net.minecraft.class_2806$$Lambda$2212/382110147.doWork(Unknown Source)
	at net.minecraft.class_2806.mde2b25a$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806$$Lambda$2213/302984430.doWork(Unknown Source)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at net.minecraft.class_3898$$Lambda$8744/1639238111.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at net.minecraft.class_3898$$Lambda$8730/1665139061.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3900$$Lambda$8743/418596109.run(Unknown Source)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
-- Generation --
Details:
	CenterX: 37
	CenterZ: -8
	Seed: -828869275344545501
	Biome: net.minecraft.class_1959@4aea0b04
-- Chunk to be generated --
Details:
	Location: 37,-8
	Position hash: -34359738331
	Generator: net.minecraft.class_3754@7a9241c1
-- Affected level --
Details:
	All players: 1 total; [class_3222['ScarlettBlade'/237, l='ServerLevel[Test]', x=398.75, y=83.59, z=95.60]]
	Chunk stats: ServerChunkCache: 2256
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (160,68,-176), Chunk: (at 0,4,0 in 10,-11; contains blocks 160,0,-176 to 175,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 913 game time, 913 day time
	Level name: Test
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 76903 (now: false), thunder time: 70092 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 539605720 bytes (514 MB) / 2331508736 bytes (2223 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Suspected Mods: Better End (betterend)
	Fabric Mods: 
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		antiqueatlas: Antique Atlas 5.4.4-fabric
		architectury: Architectury 1.12.145
		artifacts: Artifacts 3.2.0+fabric
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		backslot: BackSlot 1.1.9
		bannerpp: Banner++ 2.0.2+mc.1.16.3
		beaconoverhaul: Beacon Overhaul 1.3.0+1.16
		bedspreads: Bedspreads 1.3.1-1.16.4
		beebetter: Bee Better 1.8.0-1.16.4
		betterend: Better End 0.9.3-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		bewitchment: Bewitchment 1.16.5-10
		biome_locator: Biome Locator 1.1.2
		biomemakeover: Biome Makeover 1.16.5-1.3.7
		blast: BLAST 1.5.2
		blue_endless_jankson: jankson 1.2.0
		blur: Blur (Fabric) 2.1.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.0.2-1.16.5
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		capes: Capes 1.1.1
		cardinal-components: Cardinal Components API 2.8.0
		cardinal-components-base: Cardinal Components API (base) 2.8.0
		cardinal-components-block: Cardinal Components API (blocks) 2.8.0
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.0
		cardinal-components-entity: Cardinal Components API (entities) 2.8.0
		cardinal-components-item: Cardinal Components API (items) 2.8.0
		cardinal-components-level: Cardinal Components API (world saves) 2.8.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.0
		cardinal-components-util: Cardinal Components API (utilities) 2.8.0
		cardinal-components-world: Cardinal Components API (worlds) 2.8.0
		cavebiomes: Cave Biomes 0.6.2
		chainmail: Chainmail 0.5.0
		charm: Charm 2.3.2
		cinderscapes: Cinderscapes 1.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		colormatic: Colormatic 2.2.8+mc.1.16.3
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.2-1.16.5
		compacttnt: Compact TNT Mod 1.5
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		couplings: Couplings 1.3.3
		crimsonmoon: Crimson Moon 2.0.4-1.16.5
		croptopia: Croptopia 1.3.1
		crowdin-translate: CrowdinTranslate 1.2
		culinaire: Culinaire 2.0
		cullleaves: Cull Leaves 2.1.0
		custom-fog: Custom Fog 1.5.0
		customportalapi: Custom Portals 0.0.1-beta29-1.16
		dark-loading-screen: Dark Loading Screen 1.6.3
		dawn: Dawn API 1.8
		dragonloot: DragonLoot 1.0.5
		ducts: Ducts 1.0.4
		dynamicfps: Dynamic FPS 2.0.1
		eldritch_mobs: Eldritch Mobs 1.6.9
		entityculling: EntityCulling-Fabric 1.2.1
		expandedstorage: ExpandedStorage 5.6.33
		extragenerators: Extra Generators 1.0.1-BETA
		fabric: Fabric API 0.33.1+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fabricshieldlib: Fabric Shield Lib 1.3.5-1.16.5
		fabrishot: Fabrishot 1.4.0
		fallingleaves: Falling Leaves 1.6.0+1.16.5
		fallingtree: FallingTree 2.11.3
		fastbench: FastBench 2.3
		fastchest: FastChest 1.2+1.16
		fastfurnace: FastFurnace 2.4
		fasttransferlib: Fast Transfer Lib 0.2.1
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.8
		geckolib3: Geckolib 3.0.31
		gentlefawn: GentleFawn 1.1.4-MC1.16.5-fabric
		gildednetherite: Gilded Netherite 1.0.0
		glassential: Glassential 1.16.4-1.1.5
		glimmeringpotions: Glimmering Potions 1.1.3-1.16.5
		go-fish: Go Fish 1.2.1-beta-1.16.4
		gravestones: Gravestones v1.9
		greater_eye: Greater Eye of Ender 1.1.5
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		harvest_scythes: Harvest Scythes 1.1.1
		hydrogen: Hydrogen 0.2
		impersonate: Impersonate 2.1.0
		improved-stations: Improved Stations 2.0.3
		inmis: Inmis 2.2.1-1.16.5
		intotheomega: Into the Omega 1.1.2-beta-1.16.2
		inventorysorter: Inventory Sorter 1.7.9-1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumploader: Jumploader 2.1.3
		kiln: Kiln 1.1.1+1.16.5
		kyrptconfig: Kytpt Config 1.1.6-1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes: LibBlockAttributes 0.8.5
		libblockattributes_core: LibBlockAttributes (Core) 0.8.8
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.8
		libblockattributes_items: LibBlockAttributes (Items) 0.8.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		libstructure: Libstructure 1.3
		lithium: Lithium 0.6.4
		lootbeams: Lootbeams 2.0.1
		maelstrom_library: Maelstrom Library 1.2-1.16.5
		mambience: MAmbience 3.1.1+1.16.5
		microconfig: Microconfig 1.0.3
		minecraft: Minecraft 1.16.5
		miskatonicmysteries: Miskatonic Mysteries 0.0.3
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.16.9
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		multipart_entities: MultipartEntities 1.1.1-SNAPSHOT
		musica: Musica 1.2.0
		musicdr: Music Duration Reducer 1.2.0
		nofade: No Fade 1.16.5-1.0.1
		notenoughcrashes: Not Enough Crashes 3.2.0
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 2.0.0+21w14a
		phosphor: Phosphor 0.7.1+build.11
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.10-1.16.5
		portaltags: Portal Tags 2.1.0
		quickshulker: Quick Shulker 1.1.14-1.16
		raisedclouds: Raised Clouds 1.0.0
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		reborncore: Reborn Core 4.7.2+build.132
		repurposed_structures: Repurposed Structures 1.16.5-1.10.4-fabric
		reroll: Reroll 1.2.1-1.16.5
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		satin: Satin 1.6.0-nightly.20w48a
		seasons: Fabric Seasons 1.1.1-BETA
		seedy-behavior: Seedy Behavior 1.0.1
		shulkerutils: shulkerutils 1.0.1-1.16
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.1.0
		sodium-extra: Sodium Extra 0.2.5
		somnus: Somnus API 0.0.11-1.16.5
		staffofbuilding: Staff of Building 1.2.6-1.16.5
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.1.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.2+build.220
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		terrestria: Terrestria 2.2.0
		the_aether: The Aether 1.16.5-1.0.3
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		veinmining: Vein Mining 0.0.7-1.16.5
		voyager: Voyager 1.0.0
		waystones: Waystones 1.1.1.1
		wthit: wthit 2.7.1
		yungsapi: YUNG's API 1.16.5-Fabric-2
		zoob: Monster Of The Ocean Depths 3.0.0
	Patchouli open book context: n/a
	
****************** Not Enough Crashes Report ******************: 

 ConfiguredFeature Registry Name : Has no identifier as it was not registered... go yell at the mod owner when you find them! lol
 Biome Registry Name : minecraft:the_end

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "betterend:round_cave"
    },
    "decorator": {
      "config": {
        "chance": 2
      },
      "type": "minecraft:chance"
    }
  },
  "type": "minecraft:decorated"
}

	Player Count: 1 / 8; [class_3222['ScarlettBlade'/237, l='ServerLevel[Test]', x=398.75, y=83.59, z=95.60]]
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by paulevsGitch** [comment]
What is your biome source?

**Comment by paulevsGitch** [comment]
Yes, this issue happens when biome source is not BE. You can change your biome source with [this tutorial](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source) until this will be fixed

**Comment by Ninonsand** [comment]
> Yes, this issue happens when biome source is not BE. You can change your biome source with [this tutorial](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source) until this will be fixed

I looked into it and my lvl.dat files all show betterend:better_end_biome_source as the type field. Do I need to change it to something else to get it to generate?

**Comment by paulevsGitch** [comment]
> my lvl.dat files all show betterend:better_end_biome_source

Each world save have only one level.dat and its cached copy, do you have more than one world or you mean this two files?
If your biome source is "betterend:better_end_biome_source" than this error will never happen (due to its nature), did you chech the right world?

**Comment by Ninonsand** [comment]
I'm pretty sure I'm in the right file location. And I'm using the correct level.dat. To test again I generated a brand new world and placed down an end portal and flew away from the flight and got the same exact crash. I then checked the nbt data and it shows better end generation for the biomes. I'm not sure, maybe it's a conflicting mod, though I don't have any others that mess with the end. Going to run some tests and I'll get back to you if it's another mod causing the problem.
![Capture](https://user-images.githubusercontent.com/20290131/116563561-227abe00-a8d2-11eb-8b1d-62e30dfa878b.PNG)

**Comment by srnyx** [comment]
> I'm not sure, maybe it's a conflicting mod, though I don't have any others that mess with the end.

What mods do you have?

**Comment by paulevsGitch** [comment]
This issue is probably unrelated to biome source, but its relative to null biome data, this is fixed in dev code and should never happen again

**Comment by srnyx** [comment]
> This issue is probably unrelated to biome source, but its relative to null biome data, this is fixed in dev code and should never happen again

Was that dev released in the latest version from 2 hours ago (v0.9.4)?

**Comment by Ninonsand** [comment]
After a lot of trial and error I found that [Hydrogen](https://modrinth.com/mod/hydrogen) was the culprit. With it installed it would cause the crash. The mod reduces the memory load when launching Minecraft so it must have been doing something funky with biomes that caused the problem. Sorry for the trouble!
