### ISSUE TITLE
Strange trails on the nether skybox on a server?

### ISSUE THREAD

**Issue by JumperCzech** [paulevsGitch/BetterEnd#152]
![image](https://user-images.githubusercontent.com/83337894/116723941-53491900-a9e0-11eb-9f4b-ba176558a5a5.png)
they just kinda stack up over time, gets really annoying
fog hides them but i dont think im the only one playing without fog

**Comment by paulevsGitch** [comment]
This is BetterEnd issue tracker, not BetterNether. And this issue was already mentioned, just don't use fabulous graphics settings
