### ISSUE TITLE
Incompatibility with hydrogen (missing biomes on generation)

### ISSUE THREAD

**Issue by WachumaFox** [paulevsGitch/BetterEnd#154]
A player on my server crashed the server after travelling out in the end and generating biomes
https://pastebin.com/62AWRvci

The biome generator is set to better_end_biome_source for the end, 
A list of my mods can be seen in the crash report, it also generated a second crash log at the same time
https://pastebin.com/ZTxLRV3B

EDIT:
I was able to replicate the crash in a new singleplayer world with the same mods, just travelling out in the end. 
https://pastebin.com/t9ZbgzuF
Biome generator is set correctly there, too.

**Comment by paulevsGitch** [comment]
Duplicate of #148

**Comment by WachumaFox** [comment]
Upon adding and removing every single mod in my modpack, it seems to be hydrogen. Im generating everything just fine now with the removal of hydrogen!

**Comment by paulevsGitch** [comment]
Hydrogen changes [biome array](https://github.com/CaffeineMC/hydrogen-fabric/blob/1.16.x/src/main/java/me/jellysquid/mods/hydrogen/mixin/chunk/MixinBiomeArray.java), probably compatibility will be impossible to implement

**Comment by RDKRACZ** [comment]
Can confirm that https://github.com/paulevsGitch/BetterEnd/commit/38eaf8be67f99fd6d8206dce76b979cf4464daaf fixed the issue.

**Comment by paulevsGitch** [comment]
Fixed in 0.9.7
