### ISSUE TITLE
Issue with saplings

### ISSUE THREAD

**Issue by arttoanimate** [paulevsGitch/BetterEnd#155]
Tenanea saplings only grow on the rutiscus block and transform into lucernia trees. Unable to grow more tenanea trees on any other soil end block. 
![image](https://user-images.githubusercontent.com/83623672/116953800-302a9d80-ac5c-11eb-97f4-fa1e75fc3dfa.png)

**Comment by paulevsGitch** [comment]
Fixed in dev code

![2021-05-05_03 07 26](https://user-images.githubusercontent.com/17707380/117084174-2c2b7800-ad4f-11eb-84e2-d261ae132b1f.png)

**Comment by paulevsGitch** [comment]
Fixed in 0.9.6
