### ISSUE TITLE
Charcoal Blocks cannot be crafted back into charcoal

### ISSUE THREAD

**Issue by heyjudek** [paulevsGitch/BetterEnd#157]
As the title says, I have made a few stacks of charcoal blocks hoping to use them as charcoal when I have to, only to realize they burn 30 items per block and cannot be turned back into charcoal. So, to fix this their smelting rate should be increase (from 30 to 72 or 80) and they should also be crafted back into charcoal.

**Comment by paulevsGitch** [comment]
Fixed in 0.9.6
