### ISSUE TITLE
Bucket of Cubozoa does not spawn a Cubozoa.

### ISSUE THREAD

**Issue by ChrisLensFlare** [paulevsGitch/BetterEnd#158]
In the title. Latest version 0.9.5.

**Comment by paulevsGitch** [comment]
There was a similar issue with Bucket of End Fish, fixed in dev code

![2021-05-05_03 17 47](https://user-images.githubusercontent.com/17707380/117084699-8d078000-ad50-11eb-9f39-7ac311996730.png)

**Comment by paulevsGitch** [comment]
Fixed in 0.9.6
