### ISSUE TITLE
Enhancement {1.16.3-1.16.4} Add Tags to BetterEnd Logs

### ISSUE THREAD

**Issue by litjohn50** [paulevsGitch/BetterEnd#16]
Can you Add tags to BetterEnd Logs so recipe can be made that will accept either the stripped version or normal version.

Example: me adding a recipe via sawmill with KubeJS, but would have to add 2 recipe for getting the same planks. Instead of 1 recipe.

Example Tag: #betterend:pythadendron_log for both the log and stripped log

What it looks like in REI: https://gyazo.com/62202428c9c40463a074ad515b58d4fe

**Comment by paulevsGitch** [comment]
All BE logs already have tags. Tags are not used for individual log types, this is wrong way of using tags. If you are using KubeJS to add a recipe you can use condition with name and make them procedurally instead of making them manually

**Comment by litjohn50** [comment]
Only your logs were having issues with the recipes...

**Comment by Reveter** [comment]
Mojang adds tags for each of the types of vanilla logs, and uses that tag for its planks recipes. Nearly every other mod also follows this precedent, its a bit silly to claim its incorrect.

**Comment by paulevsGitch** [comment]
![2020-11-17_11 29 18](https://user-images.githubusercontent.com/17707380/99365524-78315000-28c8-11eb-8f62-c0da56eb6d4e.png)

**Comment by paulevsGitch** [comment]
Added in 0.7.0
