### ISSUE TITLE
Discs Dup issue

### ISSUE THREAD

**Issue by arttoanimate** [paulevsGitch/BetterEnd#160]
Discs duplicate when you remove them from jukeboxes

**Comment by paulevsGitch** [comment]
I can't reproduce this, can you explain it in more details?

**Comment by arttoanimate** [comment]
On our smp we used the strange and alien disc with a jukebox and took it out and it drops multiple. The faster I put it in and take it out the more it drops I think. Sent from Mail for Windows 10 From: paulevsGitchSent: Wednesday, May 5, 2021 7:09 AMTo: paulevsGitch/BetterEndCc: arttoanimate; AuthorSubject: Re: [paulevsGitch/BetterEnd] Discs Dup issue (#160) I can't reproduce this, can you explain it in more details?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by paulevsGitch** [comment]
Looks like a bug from vanilla or other mod, BE itself don't have this bug
