### ISSUE TITLE
Blockus update means some compatibility retextures need updating/adding

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#163]
[Blockus](https://www.curseforge.com/minecraft/mc-mods/blockus/files) has had an update changing the texture of their **chiselled purpur block**, which means that BE's retexture of it to match its new purpur colour no longer matches. I would like to request that this texture be updated to have the new shape with Better End's purpur colour. The Blockus update also added a new purpur-decorated end stone block that I would like to request be given an appropriate recolour as well.
The relevant Blockus changelog and version download is linked above.

**Comment by paulevsGitch** [comment]
Added in 0.9.7
