### ISSUE TITLE
Dragon bone stairs and slab are uncraftable

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#164]
Dragon bone stairs and dragon bone slabs are uncraftable. One would expect that they could be created with the standard vanilla stair and slab crafting recipes using dragon bone blocks. In addition to the crafting table, you can decide whether or not you feel the stonecutter is appropriate for processing bones.

**Comment by paulevsGitch** [comment]
They are just unfinished, I will add recipes for bones when they will be obtainable in survival

**Comment by paulevsGitch** [comment]
Added in 0.12.5
