### ISSUE TITLE
wont let me start minecraft

### ISSUE THREAD

**Issue by do9y** [paulevsGitch/BetterEnd#168]
when i try to launch minecraft with the mod installed it comes up with could not find required mod: betterend requires {fabric @ [>=0.32.0]} is there anything i can do about this??

**Comment by RDKRACZ** [comment]
>is there anything i can do about this

Well yes... download or update your fabric API.

**Comment by paulevsGitch** [comment]
This message directly says you to install Fabric API 0.32.0 or newer
