### ISSUE TITLE
Game crashes on startup. No other mods installed currently.

### ISSUE THREAD

**Issue by KewlDude2005** [paulevsGitch/BetterEnd#17]
I have no idea what is happening. It is only the better end mod that does this.

https://github.com/paulevsGitch/BetterEnd/files/5541285/crash-2020-11-14_13.45.29-client.txt

BTW it's version 1.16.4

**Comment by EnderBro123** [comment]
Try updating your Fabric API.

**Comment by paulevsGitch** [comment]
@EnderBro123 this is not related with Fabric API, this is related to text codecs

**Comment by EnderBro123** [comment]
Ah.

**Comment by KewlDude2005** [comment]
Not to be the idiot but what does that mean and how do I fix it?

**Comment by paulevsGitch** [comment]
Fixed in 0.7.0
