### ISSUE TITLE
Build fails.

### ISSUE THREAD

**Issue by RDKRACZ** [paulevsGitch/BetterEnd#170]
I saw https://github.com/paulevsGitch/BetterEnd/commit/38eaf8be67f99fd6d8206dce76b979cf4464daaf and wanted to try it but building from the source fails with `/usr/bin/env: ‘sh\r’: No such file or directory`. Tested on the local machine and Github Actions (to make sure it's not my fault) (https://github.com/RDKRACZ/BetterEnd/runs/2543774491?check_suite_focus=true).

**Comment by paulevsGitch** [comment]
You are trying to build mod with GitHub actions which is not implemented, we recommend you to use traditional way - gradlew build

**Comment by RDKRACZ** [comment]
Like I said I tried both methods and it fails the same way.

**Comment by paulevsGitch** [comment]
\r in the ‘sh\r’ mean incorrect string ending, this is probably a cross-platform issue as endings on Windows and on Unix are different

**Comment by RDKRACZ** [comment]
This is weird but Github builds the file successfully. 
I can open a pr, if you want, with:
- converted gradlew file
- enabled Github Actions
- added build-artifacts to every Guthub Action

https://github.com/RDKRACZ/BetterEnd/actions/runs/829428466

**Comment by paulevsGitch** [comment]
As this issue is not directly on BE side I will close this
