### ISSUE TITLE
Aquatic Mobs not spawning frequently

### ISSUE THREAD

**Issue by SplatteredRaccoon** [paulevsGitch/BetterEnd#176]
not seeing a whole lot of the aquatic mobs at all, i searched all of their listed biomes, and they only sometimes show up in the sulfuric springs? is there a fix for this?

**Comment by paulevsGitch** [comment]
This is bug of Minecraft spawning system, not the mod. If you want to increase spawn rates of creatures you can use a datapack to alternate spawn values
