### ISSUE TITLE
Thalassium rail recipe is bugged

### ISSUE THREAD

**Issue by CoaLMaN122PL** [paulevsGitch/BetterEnd#177]
Thalassium rail recipe is bugged and only gives 1 rail from the recipe, it also overrides the vanilla iron rail recipe to give 1 rail per recipe too

**Comment by paulevsGitch** [comment]
Iron tag recipes were moved to BCLib and fixed

**Comment by paulevsGitch** [comment]
Fixed in 0.9.7
