### ISSUE TITLE
Eternal Pedestals generated before 0.6.2 don't function correctly

### ISSUE THREAD

**Issue by ElKameleon** [paulevsGitch/BetterEnd#18]
I loaded up a world created with 0.5.2 beta and the eternal pedestals do not work like newly placed ones, they have to be broken and replaced in creative. Pre-generated portal blocks seem to be unaffected, they work just fine after replacing the pedestals.

https://photos.app.goo.gl/r45wr8LQ8Tn8Ac6i7

**Comment by paulevsGitch** [comment]
Portal entity serialization was changed like biome IDs, so this is not a bug. Worlds created before 0.6.1 can work incorrectly. You can regenerate DIM1 if you want or edit wrong entities/biomes manually
