### ISSUE TITLE
armored elytra not working when in trinket slot

### ISSUE THREAD

**Issue by SpinnyBoiii** [paulevsGitch/BetterEnd#180]
noticed not being able to open elytra when shift-clicking, which prioritizes the trinket slot.
manually putting it in the chest slot works, and normal elytra does work in the trinket slot.

**Comment by paulevsGitch** [comment]
What do you mean under "trinket slot"?

**Comment by SpinnyBoiii** [comment]
https://gyazo.com/965ed139763aa734d0fc442e78342940
https://gyazo.com/df72b3b8dd51cd62c6f20c83284faeb7
https://gyazo.com/65fc9c5e44585d4cabdb79c3d4e4594d
https://gyazo.com/6117232d8aff39f2a032773f842cd444

when equipped like this, its not possible to start gliding, only works when in the slot normally used for chestplates

**Comment by paulevsGitch** [comment]
This is not a vanilla slots, all functionality of non-vanilla slots is not on our side

**Comment by SpinnyBoiii** [comment]
made an issue on this at the trinkets mod, they say this is all up to other mod owners for compatability if they desire it

**Comment by Kazzaowo** [comment]
how would someone give a slot functionality?
