### ISSUE TITLE
Thallasium Armor Crafting Not Working

### ISSUE THREAD

**Issue by sheesh420** [paulevsGitch/BetterEnd#182]
After smelting the thallasium ingots, I tried making armor out of it but It wont work, I have watched youtubers craft it normally but does not work for me. The other mods I have installed are Better Nether.

**Comment by paulevsGitch** [comment]
Do you have anvil of proper level?

**Comment by sheesh420** [comment]
No because Im new to the mod

**Comment by sheesh420** [comment]
What anvil do we need for it to work?

**Comment by paulevsGitch** [comment]
> What anvil do we need for it to work?

At least with the same level as your metal. If you want to make Thallasium you will need Thallasium anvil. You can use REI too see required anvil type

**Comment by sheesh420** [comment]
Okay, once I have the required anvil what do i have to do?
