### ISSUE TITLE
End Stone Smelter does not work on multiplayer

### ISSUE THREAD

**Issue by ElKameleon** [paulevsGitch/BetterEnd#19]
Like the title says, End Stone Smelter is not interactable in multiplayer, works as intended in single player.

Minecraft 1.16.4
Better End 0.6.2 Beta

**Comment by Bulldog83** [comment]
Can you attach full latest.log file?

**Comment by ElKameleon** [comment]
I can but there's nothing there. I did notice a quirk that when it wasn't working, I went to singleplayer and tried it and it worked, then came back to the server (without closing out of minecraft) and it was now working on the server, but other players still couldn't access it.

https://pastebin.com/G4ac3e1x

**Comment by Bulldog83** [comment]
Replace smelter and try again. I've tested it in the singleplayer, and on the server. It works well.

**Comment by ElKameleon** [comment]
I'll get back to you tonight when I have a chance to test it out again. Like I said, it was working for me again after some time, but other people said it does absolutely nothing when clicking on it. (which was also my experience at first too) Could it have anything to do with our world being created with 0.5.2-beta originally? It didn't seem to work in that version when I tried it and just assumed it was a placeholder.

**Comment by ElKameleon** [comment]
Ok so I logged on this afternoon, and it refused to let me use the smelter again, so I alt-tabbed out and saw this in the console window:
[https://paste.ee/p/8o3k4](url)

**Comment by paulevsGitch** [comment]
Fixed in 0.7.0
