### ISSUE TITLE
Compatibilty with BetterNether

### ISSUE THREAD

**Issue by Blunder-G** [paulevsGitch/BetterEnd#191]
BetterEnd's hammers are incompatible with BetterNether's gems, and this is very odd. I mean, same creator, sister mods..?

**Comment by paulevsGitch** [comment]
What do you mean under "BetterEnd's hammers are incompatible with BetterNether's gems"?

**Comment by paulevsGitch** [comment]
Looks like there will be no answer, I'll close this
