### ISSUE TITLE
[Bug] Umbrella Cluster Juice Don't Give Saturation And Hunger

### ISSUE THREAD

**Issue by JuceDoesThings** [paulevsGitch/BetterEnd#194]
I was in the middle of using Appleskin to work on my food resource pack, and I noticed a small issue with one of the items; the umbrella cluster juice shows that it should give you hunger and saturation, however it does not do that when you actually drink it

**Comment by JuceDoesThings** [comment]
![see](https://user-images.githubusercontent.com/85078618/120117544-4fc9be80-c153-11eb-86c8-b0a3a85379f0.png)

**Comment by paulevsGitch** [comment]
Hi, this is not incompatibility, umbrella cluster juice really should give you hunger and saturation on usage, but as you write it doesn't do this, so this is a bug with vanilla food system. I will try to fix it

**Comment by JuceDoesThings** [comment]
Ah! Thank you for the clarification

**Comment by paulevsGitch** [comment]
Fixed in 0.9.7
