### ISSUE TITLE
BetterEnd biomes in overworld

### ISSUE THREAD

**Issue by NebelNidas** [paulevsGitch/BetterEnd#195]
Is it normal that, after upgrading from v0.9.1 to 0.9.2+, BetterEnd places and replaces its biomes into the overworld? 🤔

![2021-05-31_21 59 21](https://user-images.githubusercontent.com/48808497/120239237-192c9a80-c25e-11eb-838e-e4fc96cb4f48.png)

Previously, there was an ocean biome:
![2021-05-31_22 20 42](https://user-images.githubusercontent.com/48808497/120239395-7aed0480-c25e-11eb-9b83-a81ce7ab60eb.png)

Hydrogen is not installed.

Edit: The different grass/leaf colors are from the Fabric Seasons mod, they're not related to this issue.

**Comment by paulevsGitch** [comment]
BetterEnd doesn't replace overworld biomes, this is biome ID shifting or similar issue, it is not related to BE and is a result of new Mojang biome+datapack system. You can fix shifted biomes with external tools like WorldEdit or regenerate this area. New chunks will generate as usual

**Comment by NebelNidas** [comment]
There must be a better way than flying over the entire map, looking for every possible corrupted region and fixing it manually? 😐 Regenerating is not an option, since many of the affected chunks include buildings and other user generated content.

**Comment by paulevsGitch** [comment]
[WorldPainter](https://www.worldpainter.net/), for example, will allow you to modify all biomes on the map, probably there are more programs like it

**Comment by NebelNidas** [comment]
Thanks for the suggestion. In the meantime, I've been testing around a bit and found out that this statement is not true:
> New chunks will generate as usual

Because I teleported to not yet generated chunks, and found this:
![2021-06-01_18 07 31](https://user-images.githubusercontent.com/48808497/120356334-8430ac80-c304-11eb-86e3-c05c2170466d.png)

The weird thing is that this issue only happens with BetterEnd v0.9.2 onward. No other biome mod (or previous BE version), and I've used many, results in this corruption, which would certainly happen if this was truly a vanilla bug?

Also, it seems like the only biome replacement that happens is `minecraft:ocean` → `betterend:dragon_graveyards`. Can you please double-check if this is really not caused by some bugged implementation on your side?

**Comment by paulevsGitch** [comment]
BetterEnd replaces only End biome source and is not affecting other dimensions. I tested several world from singleplayer to servers and everything is fine. Looks like you have another mods that adds biomes - this can be a reason of biome switching as some mods add their own biomes to the oceans (BYG, for example)

Example of modded ocean biome:
![2021-06-01_19 46 07](https://user-images.githubusercontent.com/17707380/120361244-4b97cf80-c312-11eb-81d5-a018b4e29d46.png)

Each world have a biome registry (made by Fabric) located in saves/<world_name>/data folder. It contains all biomes and their IDs
![image](https://user-images.githubusercontent.com/17707380/120361508-93b6f200-c312-11eb-8e77-48edda0301e7.png)

Sometimes if you update mods some IDs of their biomes can overlap, in this case biomes will replace each other in the world too. You can check that Dragon Graveyards biome in registry have unique ID (my prediction - there will be another biome with the same ID). To look/edit registry you can use[ NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases)

**Comment by NebelNidas** [comment]
For whatever reason, many BetterEnd biomes have the ID:
![image](https://user-images.githubusercontent.com/48808497/120374941-78e87b80-c31a-11eb-81d3-a99a477410ca.png)
Which is the same as `minecraft:ocean`'s:
![image](https://user-images.githubusercontent.com/48808497/120374950-7ab23f00-c31a-11eb-9aeb-db550599457b.png)

Do you know what could've caused this? And how to fix it? Should I manually assign the correct IDs?

**Comment by paulevsGitch** [comment]
> Do you know what could've caused this?

Probably a bug on world init after adding a new biomes in registry

> And how to fix it? Should I manually assign the correct IDs?

The simplest way is to assign each biome a new ID in this registry manually. You can chose starting number that doesn't exist in registry (like 300, for example) and simply add each biome incremental ID (like 300, 301, 302, etc). You only need to check that this ID is free in registry (NBTExplorer allows you to search by value)
