### ISSUE TITLE
Infusion Recipe does not trigger without player input

### ISSUE THREAD

**Issue by hugeblank** [paulevsGitch/BetterEnd#200]
Without the player manually placing the last item infusion rituals will not start. This is because [line 106 of InfusionRitual](https://github.com/paulevsGitch/BetterEnd/blob/1ad72cbe88c03b1c85cca0c164d0b9a49a4e55b4/src/main/java/ru/betterend/rituals/InfusionRitual.java#L106) immediately returns if `hasRecipe` is false, which it always is, until the player interacts. This could be very easily circumvented if that `hasRecipe` check is removed, and (for the sake of reducing lag) if the `isValid` method, in addition to checking for the existence of the pedestal and block entity, also checked if the block entity had an item. ~This may also be the cause for #181, but that lacks the information for me to be sure.~

**Comment by paulevsGitch** [comment]
Fixed in 0.9.7
