### ISSUE TITLE
Broken BlockColorProviders (Causes Various Crashes)

### ISSUE THREAD

**Issue by CoolMineman** [paulevsGitch/BetterEnd#201]
Many blocks in this mod such as AuroraCrystalBlock have broken color providers that assume the BlockPos is non-null. This should not be assumed as the getColor method is `int getColor(BlockState state, @Nullable BlockRenderView world, @Nullable BlockPos pos, int tintIndex)`. Causes CoolMineman/BitsAndChisels#63 and TeamAOF/All-of-Fabric-3#401. Also likely causes crashes when they are pushed by pistons, etc.

**Comment by paulevsGitch** [comment]
Fixed in 0.9.7
