### ISSUE TITLE
Corruption when joining on LAN

### ISSUE THREAD

**Issue by Silkaaa** [paulevsGitch/BetterEnd#204]
My brother and I wanted to try out a 100 days  on hardcore as endermen, and decided this would be the perfect mod. When I did this solo, it worked perfectly. However when my brother joined my LAN world, all the blocks were simply messed up. On my screen it was end moss, on his screen it was waterlogged blackstone bricks. Better end blocks did exist on his screen, he could see some blocks corrupted as better end blocks. How do I fix this, we just want to play D:

**Comment by paulevsGitch** [comment]
This means that mods or configs on both clients are different, this is not the issue of the mod
