### ISSUE TITLE
Consider using FallFlyingLib?

### ISSUE THREAD

**Issue by adriantodt** [paulevsGitch/BetterEnd#205]
Would please you consider using FallFlyingLib to solve the compatibility issues with other mods which use FallFlyingLib? 

FallFlyingLib is a library I made and maintain which makes the elytra compatibility between all mods easier, whilst adding a comprehensive pipeline for most mods to tinker with.

If you want an example implementation: https://github.com/CafeteriaGuild/FallFlyingLib/blob/master/src/main/java/net/adriantodt/fallflyinglib/impl/support/VanillaSupport.java

**Comment by Bulldog83** [comment]
I've looked at your library.  Our elytras functionality does not overlap with your library. I see no point in applying it at the moment.
If you mean FFL Trinkets, thats not needed too. Ours elytras combine armor and elytra functionality and do not assume placement in a separate slot.
