### ISSUE TITLE
Registry Remapping failed

### ISSUE THREAD

**Issue by 5ocial** [paulevsGitch/BetterEnd#206]
![unknown](https://user-images.githubusercontent.com/86155332/122643114-f9112e00-d0db-11eb-924d-308f46b04535.png)
Everytime I join my friend's 1.16.5 server this message always appears saying registry remapping failed and there are sounds unknown to the reciever. How do I fix this

**Comment by paulevsGitch** [comment]
Do you have same mod & config version as on server?

**Comment by 5ocial** [comment]
Yes I do

**Comment by paulevsGitch** [comment]
I think that it is not true, as "Registry Remapping failed" means that registry probably don't have the same content as server have, which means that client have outdated mod or wrong config file
