### ISSUE TITLE
Infusion Ritual only works with infusion pedestals

### ISSUE THREAD

**Issue by ElKameleon** [paulevsGitch/BetterEnd#21]
Infusion ritual is supposed to work with any pedestals with an infusion pedestal in the center, but it does not function. There is some quirks here, because I actually DID get it to work as intended, but it seems like you need to place things in a certain order, instead of checking if all things are in place at the time of placing the center item. I just got it to _NOT_ work with all 9 pedestals as infusions ones. I needed to break the center pedestal, replace it, and then it worked as intended. I can provide more if I need to.

**Comment by paulevsGitch** [comment]
Infusion ritual needs only one infusion pedestal in the center and normal ones around it. To activate ritual you need to place item to infuse after all other items or simply right-click on infusion pedestal to activate it
