### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KabMaster** [paulevsGitch/BetterEnd#210]
what does the hammer in BetterEnd mod do specifically? is it just a weapon or can it break 3x3 blocks? pls let me know

**Comment by paulevsGitch** [comment]
It is a crafting tool, mining tool and a weapon

**Comment by KabMaster** [comment]
Could I explain all the uses of it me and the bois are really clueless

**Comment by Fireface677** [comment]
Mining tool and weapon uses should be self-explanatory. For crafting stuff I recommend using REI. It should show you all the recipes the hammer is used for. :)

**Comment by KabMaster** [comment]
For the mining part does it mine like a 3x3 space or no

**Comment by Fireface677** [comment]
Try it out? I'm not sure

**Comment by KabMaster** [comment]
I did try it out it mines a one block space maybe the creator could make a little change and maybe help mine 3x3 space but consumes a bit more durability I say?

**Comment by paulevsGitch** [comment]
It is not supposed to mine 3x3 area. It used to have maximum amount of drops from blocks like glowstone (always 4 dust)

**Comment by KabMaster** [comment]
Ohhhhhhhhhb thank you very much
