### ISSUE TITLE
better-end-0.9.8.3-pre-1.16.5 crash

### ISSUE THREAD

**Issue by SpinnyBoiii** [paulevsGitch/BetterEnd#211]
i was testing and crashed twice in a row while generating new chunks(feels slower than better-end-0.9.6-pre-1.16.5 as well, but that could just be my mind playing tricks on me), both times it blamed the generating of betterend:crashed_ship

**Comment by paulevsGitch** [comment]
Can you please attach your logs?

**Comment by SpinnyBoiii** [comment]
[crash-2021-06-21_19.11.58-server.txt](https://github.com/paulevsGitch/BetterEnd/files/6688396/crash-2021-06-21_19.11.58-server.txt)

**Comment by paulevsGitch** [comment]
Thank you, probably one of blocks require world or pos be not null to check mining speed, this will be fixed in BCLib (as the code is inside it)

**Comment by SpinnyBoiii** [comment]
np, finding bugs in games/mods is pretty much the one thing im good at so im glad to help XD

**Comment by paulevsGitch** [comment]
> feels slower than better-end-0.9.6-pre-1.16.5 as well

It's cave generation, I'm trying to optimize it right now and make generation parallel and fast

**Comment by paulevsGitch** [comment]
Fix for null pointer is out (BCLib 0.1.43), cave generation optimisation will be released soon
