### ISSUE TITLE
Superflat World Loading Fails

### ISSUE THREAD

**Issue by The-Unkindness** [paulevsGitch/BetterEnd#212]
When attempting to load up a previously exited superflat world, the game refuses to and instead requests using safe mode due to an invalid datapack. However, when clicking the 'safe mode' mode button nothing happens. I have used no datapacks when attempting to play in a superflat world. What's even more bizarre, is that non superflat worlds load just fine. 

Included Log: [2021-06-23-2.log.gz](https://github.com/paulevsGitch/BetterEnd/files/6705959/2021-06-23-2.log.gz)
Safe Mode: ![SafeModeExample](https://user-images.githubusercontent.com/86392034/123196221-8905fd80-d477-11eb-96f7-6cf05412fe41.png)

**Comment by paulevsGitch** [comment]
Hi, I tested this and I couldn't get the same error. I tested superflat worlds created with vanilla & old BE - both worked correctly and loaded fine (twice) with modern BE. Probably your level.dat or fabricDynamicRegistry.dat are corrupted, can you please check them or attach them here?

**Comment by RDKRACZ** [comment]
This seems strangely similar to this issue https://github.com/svenhjol/Charm/issues/593#issuecomment-867221139

**Comment by Bazyliii** [comment]
You are right, I have the same issue as you.

**Comment by The-Unkindness** [comment]
Level.dat: [level.dat.zip](https://github.com/paulevsGitch/BetterEnd/files/6710941/level.dat.zip)
Fabric Registry.dat: [fabricRegistry.dat.zip](https://github.com/paulevsGitch/BetterEnd/files/6710947/fabricRegistry.dat.zip)

**Comment by The-Unkindness** [comment]
> Hi, I tested this and I couldn't get the same error. I tested superflat worlds created with vanilla & old BE - both worked correctly and loaded fine (twice) with modern BE. Probably your level.dat or fabricDynamicRegistry.dat are corrupted, can you please check them or attach them here?

Fabric Dynamic Registry: [fabricDynamicRegistry.dat.zip](https://github.com/paulevsGitch/BetterEnd/files/6711178/fabricDynamicRegistry.dat.zip)

Level.dat: [level.dat.zip](https://github.com/paulevsGitch/BetterEnd/files/6711185/level.dat.zip)

**Comment by paulevsGitch** [comment]
Your DynamicRegistry is fine, I tried to fix your level.dat, now it should probably work fine
[level.dat.zip](https://github.com/paulevsGitch/BetterEnd/files/6720688/level.dat.zip)

**Comment by paulevsGitch** [comment]
Looks like this issue was finally located and fixed in dev code

**Comment by paulevsGitch** [comment]
Fixed in 0.10.3
