### ISSUE TITLE
End Stone Smelter Displays Smelting Texture and Particles even when empty.

### ISSUE THREAD

**Issue by Viotomix** [paulevsGitch/BetterEnd#216]
If you place a new End Stone smelter it does not display the smelting texture and particles, however if you smelt something and it finishes smelting whatever is inside it continues to show the smelting texture and particles.

As far as I can tell this is unaffected by if there is any fuel left inside the furnace when it finishes.

Emptying the furnace does not fix this, destroying it and placing it back down does.

Version: 0.9.8.5-pre

**Comment by Bulldog83** [comment]
Smelter (like Furnaces) shows the smelting texture and particles while it has fuel time. As soon as you start smelting something, the Smelter consumes 1 unit of fuel. Fuel has a specific burning time. And until this time expires, the Smelter displays the combustion process, i.e. fire texture and particles.
