### ISSUE TITLE
Structure Names

### ISSUE THREAD

**Issue by SlimeBoi2006** [paulevsGitch/BetterEnd#218]
Hello, I recently removed Better End from my server due to the server updating to 1.17. I am trying to clean out all the structure files put in by the mod. Is there any way I can get a list of these structure names? I will include an example of what I mean.
image
![image](https://user-images.githubusercontent.com/84562128/123530292-63623980-d6ad-11eb-9874-87adbfc8f1d6.png)

**Comment by paulevsGitch** [comment]
[Features List](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/registry/EndFeatures.java)
[Structures List](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/registry/EndStructures.java)
