### ISSUE TITLE
Could not find required mod: betterend requires {fabric @ [>=0.32.0]}?

### ISSUE THREAD

**Issue by rustedgoldmc** [paulevsGitch/BetterEnd#220]
![image](https://user-images.githubusercontent.com/83943239/123725674-18365b00-d854-11eb-9634-6ddb912f5ab0.png)
I posted this in the BC library mod issues page, but I'm posting it again here because it's referencing Better End specifically now. I am currently running version 0.9.6 I think, to see if not having to use the BCLib would make it better. It did not make it better.

**Comment by paulevsGitch** [comment]
You don't have Fabric API 0.32 or newer
