### ISSUE TITLE
Incompatibility with Custom Fog mod

### ISSUE THREAD

**Issue by VoidLock92** [paulevsGitch/BetterEnd#222]
I'm not sure why but I narrowed it down to Better End causing my Custom Fog mod (https://www.curseforge.com/minecraft/mc-mods/custom-fog) To stop working. I think it is just the most recent update but I cannot be sure without testing other versions side by side.

I already tried going into the client settings for this mod and disabling the ("useFogDensity [default: true]": true) but this did not help. Any ideas?

**Comment by VoidLock92** [comment]
Just noticed it also stopped the Fog from showing everywhere as far as I can tell. The nether from BetterNether has no fog when BetterEnd is installed. You can see clear as day to the end of the chunks.

**Comment by paulevsGitch** [comment]
Hi, the reason why fog is not changing is [here](https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/mixin/client/BackgroundRendererMixin.java#L64-L102)

> Just noticed it also stopped the Fog from showing everywhere as far as I can tell

I tested this in Oveworld and the Nether, both world have fog. It has a bit incorrect rendering as in different dimensions fog have different distance, I will fix this (before code became universal it was used only in the End and the problem didn't exist)

![2021-06-30_12 52 02](https://user-images.githubusercontent.com/17707380/123940694-17134400-d9a2-11eb-922c-f0ea1eeefb04.png)

I can try to modify BCLib a bit to have support for Custom Fog, and I will fix bug with wrong fog density

**Comment by VoidLock92** [comment]
Alright, thanks for the reply! I look forward to seeing how the fix will work with this other mod once it is released. Thanks so much for taking the time to address this issue. It might be with the render distance I have set for my server and ModPack it makes it seem as if fog is just not even there.

**Comment by paulevsGitch** [comment]
BCLib 0.2.1 now have a small fix - if biome is not from BCLib it will not control its fog. I don't know how to make it fully compatible with Custom Fog, probably the best solution is to move functions from mixin into separate classes, so other mods can mixin into them and change behaviour if rendering

**Comment by paulevsGitch** [comment]
This should work fine now with BCLib 0.2.2 or later

**Comment by VoidLock92** [comment]
So it should be fixed now with latest version? I will give it a try! thanks so much for your work on this :) I will also check if this version works with 1.16.5 as a lot of the mods we use are not yet updated to 1.17.1.
