### ISSUE TITLE
Can you do magic for 1.12.2?

### ISSUE THREAD

**Issue by iDantler** [paulevsGitch/BetterEnd#224]
Hi, I was wondering, if there are ways to put make this mod playable in version **1.12.2**

I am very excited to play it there, because there is a great variety of mods that are only and only played in that version (**1.12.2**) and I would like to include that Better End will be played... I have looked for other mods that change a bit the biome, but I really can't find one that makes it as complete as the Better End.

If there is a way to edit the files inside the mod so that it can be executed in **1.12.2** please, I would like to know how to do it, a very special greeting to all of you.

**Comment by paulevsGitch** [comment]
It is technically impossible. And we are not developing for 1.12 anymore, it is outdated game version
