### ISSUE TITLE
BetterEnd wont generate chunks with Oh The Biomes You'll Go

### ISSUE THREAD

**Issue by mmantas5** [paulevsGitch/BetterEnd#225]
BetterEnd wont generate new biomes with Oh The Biomes You'll Go. All the biomes are from byg or just big endstone islands on a server. added BetterEnd after the word was generated with byg.

https://user-images.githubusercontent.com/86912905/124382020-0b8b8a00-dcce-11eb-99e1-f45c5ae9406e.png

**Comment by mmantas5** [comment]
> BetterEnd wont generate new biomes with Oh The Biomes You'll Go. All the biomes are from byg or just big endstone islands
> 
> https://user-images.githubusercontent.com/86912905/124382020-0b8b8a00-dcce-11eb-99e1-f45c5ae9406e.png

**Comment by paulevsGitch** [comment]
Better End works fine with BYG

![2021-07-04_18 40 57](https://user-images.githubusercontent.com/17707380/124391057-671e3d80-dcf7-11eb-9f89-5375e1f8979f.png)
