### ISSUE TITLE
Compatibility issue with extreme sound muffler

### ISSUE THREAD

**Issue by AtelierAmber** [paulevsGitch/BetterEnd#23]
Since this is a compatibility issue I'm going to leave it up to you and the developer of ESM
 (which I am also opening an issue with) to discuss the problem and whether or not it is worthwhile to fix.

While in the end, dying, killing the dragon, and going through the portal crash the game *sort of* reproducibly. Sometimes the save may fix itself and stop crashing but creating a new world seemed to bring the crashes back. Some, all or rarely none of the crashes occur for the world, and some, all or none occur for different players on a server.

See attached log for more details. 
[2020-11-28-7.log](https://github.com/paulevsGitch/BetterEnd/files/5611055/2020-11-28-7.log)

**Comment by paulevsGitch** [comment]
Looks like getVolume() method from SoundInstance returns null. I actually don't know why, probably issue is on ESM side

**Comment by paulevsGitch** [comment]
As this issue is (probably) on ESM side and there are no changes I close this issue
