### ISSUE TITLE
Eternal Reload with mod installed

### ISSUE THREAD

**Issue by UnusedCactus** [paulevsGitch/BetterEnd#233]
When I opened up Minecraft to play this mod, the title screen kept reloading, and all text was replaced with "Missing Letter" squares. The only thing that changed was that I had put this mod into the game (as well as BCLib) and a Windows update.(I do not think that the windows update is the cause)(If it is I will report back saying that it isn't the mod causing this)
Version is 1.17.1

**Comment by UnusedCactus** [comment]
I removed BCLib as well as Better End and minecraft loaded properly.

**Comment by UnusedCactus** [comment]
Not BCLib's fault either.

**Comment by paulevsGitch** [comment]
Can you please send your logs?

**Comment by UnusedCactus** [comment]
I do not know what you are asking after, but if it makes any difference I had to exit out of the game manually. (NO buttons worked)( I had the game windowed because of a mod)

**Comment by UnusedCactus** [comment]
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/6796012/latest.log)
I  _think_ this is what you want? I'm not totally sure.

**Comment by paulevsGitch** [comment]
> ConcurrentModificationException

in

> team.chisel.**ctm**.client.handler

The real reason of crash is CTM, disable it and it will work fine

**Comment by UnusedCactus** [comment]
I... Don't know what CTM is. Nor do I know what mod it's hiding with.

**Comment by UnusedCactus** [comment]
Oh wait it's connected textures mod isn't it?

**Comment by UnusedCactus** [comment]
The game works now! Thanks
