### ISSUE TITLE
Crash while loading the game with Emotecraft mod

### ISSUE THREAD

**Issue by adriancpp** [paulevsGitch/BetterEnd#234]
Crash report in the attached file
Emotecraft -> https://www.curseforge.com/minecraft/mc-mods/emotecraft
better end version - better-end-0.10.2-pre

[crash-2021-07-10_08.57.12-client.txt](https://github.com/paulevsGitch/BetterEnd/files/6794812/crash-2021-07-10_08.57.12-client.txt)

**Comment by paulevsGitch** [comment]
Looks like its library use [incompatible mixins](https://github.com/KosmX/bendy-lib/blob/27ece8906ba2eda87fb3df55cb22075773c352e8/src/main/java/io/github/kosmx/bendylib/mixin/IModelPartMixin.java#L65), please report this issue to Emotecraft developers

**Comment by KosmX** [comment]
This issue can be closed, it was caused by [KosmX/bendy-lib#17](https://github.com/KosmX/bendy-lib/issues/17)
It is fixed and tested. I'll release the fix soon.

**Comment by paulevsGitch** [comment]
Thank you for quick fix
