### ISSUE TITLE
[Bug] Duplicate recipes + logspam

### ISSUE THREAD

**Issue by SZUMASTER** [paulevsGitch/BetterEnd#236]
Hello,
1. Got weird problem with betterend. The anvils are doubled in REI 
<a href="https://imgur.com/haYYEjF"><img src="https://i.imgur.com/haYYEjF.png" title="source: imgur.com" /></a>

2. spam-logs with errors: "**Unable to load material**" (that errors generate 6mb txt files)
- logs: https://pastebin.pl/view/4999a05a

Could you look at this please and let me know what is wrong? 

**Thanks**

**Comment by paulevsGitch** [comment]
65k lines of errors from different mods, most are from FREX library (which couldn't load materials). Looks like you have many different mod conflicts, and this is not relative to BetterEnd

**Comment by SZUMASTER** [comment]
ok, But what about anvil recipes, you fix it in 1.17, 1.16.5 will not receive an update?

**Comment by paulevsGitch** [comment]
On 1.16.5 anvil recipes works fine

**Comment by SZUMASTER** [comment]
> Hello,
> 
> 1. Got weird problem with betterend. The anvils are doubled in REI
>    [![](https://camo.githubusercontent.com/52366d6d7d645706c804d9ebb2c018ebb8478e9c8d36db058e2a3b8c0a9183e4/68747470733a2f2f692e696d6775722e636f6d2f68615959456a462e706e67)](https://imgur.com/haYYEjF)

This is screenshot from 1.16.5 ; o, you think its from different mod conflict?

**Comment by paulevsGitch** [comment]
Yes, all recipes shown fine in BE + REI without other mods

**Comment by SZUMASTER** [comment]
Thanks, have a nice day :)
