### ISSUE TITLE
Issue with Hydrogen biome arrays (1.17, again)

### ISSUE THREAD

**Issue by DeeChael** [paulevsGitch/BetterEnd#237]
BetterEnd will loop print when player in the end.
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/6796457/latest.log)

**Comment by paulevsGitch** [comment]
What version are you using?

**Comment by cuire** [comment]
I had same problem with - betterend@0.10.1-pre (1.17)

**Comment by paulevsGitch** [comment]
I know where the reason is, it is [this warning](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/mixin/common/ChunkBiomeContainerMixin.java#L68)
Looks like Hydrogen changed its format again, I need to check this

**Comment by paulevsGitch** [comment]
Looks like this biome changes was not ported to 1.17 in Hydrogen, so I can disable them (temporary)

**Comment by paulevsGitch** [comment]
Fixed in 0.10.3
