### ISSUE TITLE
Pedestal Crash

### ISSUE THREAD

**Issue by UnhappyWithMyUsername** [paulevsGitch/BetterEnd#24]
When an item is placed on any pedestal and you break the block without taking the item from the pedestal, the game always crashes.

[crash-2020-11-29_00.04.54-client.txt](https://github.com/paulevsGitch/BetterEnd/files/5611356/crash-2020-11-29_00.04.54-client.txt)

**Comment by paulevsGitch** [comment]
This is Optifine issue, we will look what we can do

**Comment by paulevsGitch** [comment]
Looks like it was fixed

**Comment by paulevsGitch** [comment]
Fixed in 0.8.0
