### ISSUE TITLE
[Bug] Anvil item duplication in search and REI

### ISSUE THREAD

**Issue by szumaster** [paulevsGitch/BetterEnd#240]
#236, you boy check what you write?

## duplicates:

<a href="https://imgur.com/urPTGpg"><img src="https://i.imgur.com/urPTGpg.png" title="source: imgur.com" /></a>

## mods:

<a href="https://imgur.com/sxbny0e"><img src="https://i.imgur.com/sxbny0e.png" title="source: imgur.com" /></a>

regards,
css

**Comment by paulevsGitch** [comment]
I already noticed item duplication in the latest BE, it is only visual glitch (items are added to both tabs in creative and shown as unique items), I will fix this

**Comment by cssigor** [comment]
Hello, could you merge all changes/fixes to 1.16.5 branch?

**Comment by paulevsGitch** [comment]
No, fix is only available for 1.17.1

**Comment by szumaster** [comment]
so you abandon the 1.16.5 version?

**Comment by paulevsGitch** [comment]
Yes, the actual development version is for 1.17.1
