### ISSUE TITLE
Crash/Un-launchahble when in custom Modpack

### ISSUE THREAD

**Issue by snowboundmage2** [paulevsGitch/BetterEnd#241]
Makes my modpack crash on bootup
Im not a genius but it seems to be fabrics fault maybe?
[latest - Copy.log](https://github.com/paulevsGitch/BetterEnd/files/6803860/latest.-.Copy.log)

**Comment by paulevsGitch** [comment]
It is a mod conflict. One of your mods redirects important function that BetterEnd mixin requires to operate with. Try to find this mod and if you locate it - please report issue to its authors (as redirects are not compatible mixins)

**Comment by snowboundmage2** [comment]
More Commands
https://www.curseforge.com/minecraft/mc-mods/morecommands

let them know on their modpage, apparently they conflict with a bit, but don't feel like putting it in their description
