### ISSUE TITLE
New Pillars/Bedrock Portal generate on top of old ones when respawning/killing dragon.

### ISSUE THREAD

**Issue by SiliconEnt** [paulevsGitch/BetterEnd#245]
Minecraft 1.17.1
Fabric API 0.37.0
BCLib 0.2.2
BetterEnd 0.10.4-pre
RetinaPotato 1.0.1

When respawning the dragon, new pillars generate on top of the old ones. This happens fairly reliably. While some of my test worlds didn't have this effect, 5 in a row did.

![glitched-pillars](https://user-images.githubusercontent.com/46073934/125510543-73c0fc5e-7aeb-4cde-9c49-320e2617b939.png)
![more-glitched-pillars](https://user-images.githubusercontent.com/46073934/125510865-56fc819e-b6ed-4eff-862c-b96106d5e883.png)

Sometimes, the central bedrock portal does the same, although this occurs upon dragon death, not upon dragon respawn.

![glitched-center-portal](https://user-images.githubusercontent.com/46073934/125511969-25672d31-f0bc-42df-9902-c9e1816174c3.png)

**Comment by paulevsGitch** [comment]
This was discussed on Discord server - the problem is with BetterEnd cache file located in world data folder. Resetting this file and central island region will fix this issue

**Comment by MoZarka** [comment]
> 
> 
> This was discussed on Discord server - the problem is with BetterEnd cache file located in world data folder. Resetting this file and central island region will fix this issue

How do I reset the "central island region"?
