### ISSUE TITLE
[BUG] Conflicts With Immersive Portals and Optifine

### ISSUE THREAD

**Issue by Phoupraw** [paulevsGitch/BetterEnd#247]
Version: 1.17.1 - 0.10.4
How to reproduce: Build an end portal or enter a world where player is in the end.
Immersive Portals: https://github.com/qouteall/ImmersivePortalsMod/issues
Log: [latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/6819038/latest.log)

**Comment by paulevsGitch** [comment]
Looks like issue happens somewhere in portals rendering, I'm not sure

**Comment by paulevsGitch** [comment]
I changes sky rendering code, it will probably will work

**Comment by paulevsGitch** [comment]
This should also fix issues with optifine (probably), this requires testing

**Comment by paulevsGitch** [comment]
This probably should work in latest release, if not - please reopen this issue
