### ISSUE TITLE
Pearlberry seed missing texture 

### ISSUE THREAD

**Issue by SkullDiamond** [paulevsGitch/BetterEnd#248]
Dont know what cause this, I have no resourcepacks installed 

![misstexture](https://user-images.githubusercontent.com/79324102/125871491-3521ce96-7a1e-435d-ae93-77e8843c7aa3.png)

**Comment by SkullDiamond** [comment]
I just installed only betterend and still have the same problem. I dont know why you close it....

**Comment by paulevsGitch** [comment]
> I dont know why you close it....

![image](https://user-images.githubusercontent.com/17707380/125935332-2e6b2eb0-c47a-46cc-9ae1-22532e25cf85.png)

It is a **Fabric** mod and it doesn't have missing blocks

**Comment by SkullDiamond** [comment]
then is a bug. I just installed clean only betterEndForge and still have missingtextures on the pearlberry

**Comment by paulevsGitch** [comment]
This a **Fabric** mod, not a **Forge** mod

**Comment by SkullDiamond** [comment]
oooooooooh my bad. I just relice. So sorry
