### ISSUE TITLE
Missing Model for Variant : Door

### ISSUE THREAD

**Issue by leon7104** [paulevsGitch/BetterEnd#249]
Warn Exception loading blockstate definition: betterend:blockstates/terminite_door.json: java.io.FileNotFoundException: betterend:blockstates/terminite_door.json

**Comment by paulevsGitch** [comment]
There are no Json files for all doors, are you using other mods?

**Comment by leon7104** [comment]
yes
i used it in modpack

paulevsGitch ***@***.***> 於 2021年7月18日 週日 上午10:14寫道：

**Comment by paulevsGitch** [comment]
This means that another mod breaks model loading, this is not BE issue. If you are using mods like ctm - they may break correct model init, you can find these mods and disable them or write a report to their authors

**Comment by leon7104** [comment]
Awesome, thanks!

paulevsGitch ***@***.***> 於 2021年7月18日 週日 下午7:11寫道：

**Comment by leon7104** [comment]
Thank you!

paulevsGitch ***@***.***> 於 2021年7月18日 週日 下午7:11寫道：
