### ISSUE TITLE
Crashing the client but not the server

### ISSUE THREAD

**Issue by Muamer00** [paulevsGitch/BetterEnd#25]
We already have a world and we decided to add betterend but when we do the server boots up just fine but the client just crashes saying Signature "not proper gpu matches".
[tlauncher_11_29_2020_12_22_13.log](https://github.com/paulevsGitch/BetterEnd/files/5612054/tlauncher_11_29_2020_12_22_13.log)

**Comment by paulevsGitch** [comment]
"at dev.bodner.jack.betterslabs.client.BetterslabsClient.lambda$createPack$2(BetterslabsClient.java:55)" - looks like bug is in Betterslabs

**Comment by paulevsGitch** [comment]
One important thing - looks like you are using mod for 1.16.4 on 1.16.3, we will not accept issues with wrong API if they will exist

**Comment by Muamer00** [comment]
I tried older versions with 1.16.3 same thing
