### ISSUE TITLE
Recipe tag?

### ISSUE THREAD

**Issue by Fabizocker456** [paulevsGitch/BetterEnd#253]
It would be great if you could craft the vanilla crafting table from all the custom ones. They aren't in a tag (#minecraft:crafting_tables?) so custom recipes need to tag each one individually. My idea would be to either add a tag, if possible put it into some unified namespace so other mods could add their crafting tables, or allow crafting the original table from all the custom ones. Same for chests, ladders etc.

**Comment by paulevsGitch** [comment]
I will add a c:workbench tag to them

**Comment by paulevsGitch** [comment]
Added in 0.11.0
