### ISSUE TITLE
OpenGL Errors

### ISSUE THREAD

**Issue by Raavea** [paulevsGitch/BetterEnd#254]
Hiya,
 I've been trying to build a modpack in the latest fabric, with mc version 1.17 and getting HUGE spam in my error logs about OpenGL errors; one log file is over 4GB and I can't even open it; the last one I could open was 804MB and most of that was this one error being spammed over and over again.
 
 I decided to try building the modpack from scratch, one mod at a time, in a more recent version of MC - 1.17.1 - partly bc I wanted to include tinkers construct (which wasn't available in the curseforge app for 1.17) and partly bc this way I can test every mod individually as I add it.

 I'm doing this by 
installing a mod, 
opening minecraft, 
deleting all previous worlds, 
starting a new one, 
running around a bit, 
diving into water, 
breaking and placing a block, 
and then going into creative mode and searching for the new mod's blocks*.

 (*one error I traced in my previous modpack buildup was a problem with the cows in aether reborn - searching for cow would crash mc completely, which I only realised bc I couldn't find any cows and wanted to see if i could spawn one or if a mod i'd added which added different flowery cows might be causing it; was surprised it was aether reborn and not the mooblooms mod I expected). This error is what made me start checking the error logs and how I noticed the OpenGL error spam and that the files were H U G E bc of them.

Anyway, I started (mc 1.17.1 modpack build) with Expanded Storage - worked fine - then Better Nether - worked fine - then REI - worked fine - and then Better End - the error started appearing in the logs.

So I've just removed everything EXCEPT Better End and tested it - and that OpenGL error appears.
I hope this wasn't too much information, I just figured I'd walk through what I've done to try to figure out what mod is causing the error and why I think it's yours. I've never built a modpack before and was losing my mind with the problems with the first version.

It might be noted that this error is not causing my game to crash; I notice nothing out of the ordinary in terms of game playability, world generates in normal timeframes, game loads and saves and exits normally. But if my latest.log is gonna be swelling up by GBs from this one error, my hard disk is gonna explode.

Here's my latest.log from making a new world and running around for a few minutes as previously described with just BetterEnd installed (and BC Lib, which comes with it).

Specifically, the error which is repeated ad nauseum the longer I play is the `OpenGL debug message: id=1282` which seems to be kicked off from about here:
` OpenGL debug message: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 93, "": The � shader uses varying overlayColor, but previous shader does not write to it.
Out of resource error.
'
[16:41:39] [Render thread/WARN]: Error encountered when linking program containing VS rendertype_item_entity_translucent_cull and FS rendertype_item_entity_translucent_cull. Log output:
[16:41:39] [Render thread/WARN]: The � shader uses varying overlayColor, but previous shader does not write to it.
Out of resource error.
[16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'`

Full log;

> [16:40:56] [main/INFO]: Loading for game Minecraft 1.17.1
> [16:40:56] [main/INFO]: [FabricLoader] Loading 50 mods:
> 	- bclib@0.2.4
> 	- betterend@0.10.5-pre
> 	- fabric@0.37.0+1.17
> 	- fabric-api-base@0.3.0+a02b446318
> 	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
> 	- fabric-biome-api-v1@3.1.11+c345aea818
> 	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
> 	- fabric-command-api-v1@1.1.2+6cefd57718
> 	- fabric-commands-v0@0.2.2+92519afa18
> 	- fabric-containers-v0@0.1.12+a02b446318
> 	- fabric-content-registries-v0@0.2.2+a02b446318
> 	- fabric-crash-report-info-v1@0.1.5+be9da31018
> 	- fabric-dimensions-v1@2.0.11+6cefd57718
> 	- fabric-entity-events-v1@1.1.0+a02b446318
> 	- fabric-events-interaction-v0@0.4.9+a722d8c018
> 	- fabric-events-lifecycle-v0@0.2.1+92519afa18
> 	- fabric-game-rule-api-v1@1.0.7+6cefd57718
> 	- fabric-item-api-v1@1.2.4+a02b446318
> 	- fabric-item-groups-v0@0.2.10+b7ab612118
> 	- fabric-key-binding-api-v1@1.0.4+a02b446318
> 	- fabric-keybindings-v0@0.2.2+36b77c3e18
> 	- fabric-lifecycle-events-v1@1.4.4+a02b446318
> 	- fabric-loot-tables-v1@1.0.4+a02b446318
> 	- fabric-mining-levels-v0@0.1.3+92519afa18
> 	- fabric-models-v0@0.3.0+a02b446318
> 	- fabric-networking-api-v1@1.0.12+6cefd57718
> 	- fabric-networking-blockentity-v0@0.2.11+a02b446318
> 	- fabric-networking-v0@0.3.2+92519afa18
> 	- fabric-object-builder-api-v1@1.10.9+b7ab612118
> 	- fabric-object-builders-v0@0.7.3+a02b446318
> 	- fabric-particles-v1@0.2.4+a02b446318
> 	- fabric-registry-sync-v0@0.7.10+e2961fee18
> 	- fabric-renderer-api-v1@0.4.4+5f02c96918
> 	- fabric-renderer-indigo@0.4.8+a02b446318
> 	- fabric-renderer-registries-v1@3.2.0+a02b446318
> 	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
> 	- fabric-rendering-fluids-v1@0.1.13+a02b446318
> 	- fabric-rendering-v0@1.1.2+92519afa18
> 	- fabric-rendering-v1@1.6.0+a02b446318
> 	- fabric-resource-loader-v0@0.4.7+b7ab612118
> 	- fabric-screen-api-v1@1.0.4+155f865c18
> 	- fabric-screen-handler-api-v1@1.1.8+a02b446318
> 	- fabric-structure-api-v1@1.1.12+6cefd57718
> 	- fabric-tag-extensions-v0@1.1.4+a02b446318
> 	- fabric-textures-v0@1.0.6+a02b446318
> 	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
> 	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
> 	- fabricloader@0.11.6
> 	- java@16
> 	- minecraft@1.17.1
> [16:40:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/Curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
> [16:40:57] [main/INFO]: Compatibility level set to JAVA_16
> [16:40:58] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
> [16:41:04] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
> [16:41:05] [Render thread/INFO]: Setting user: Etheiy
> [16:41:05] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zzn000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
> [16:41:19] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
> [16:41:20] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
> [16:41:21] [Render thread/INFO]: Narrator library for x64 successfully loaded
> [16:41:22] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, BCLib, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Item API (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Better End, Fabric Object Builders (v0))
> [16:41:37] [Render thread/INFO]: OpenAL initialized.
> [16:41:37] [Render thread/INFO]: Sound engine started
> [16:41:37] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/blocks.png-atlas
> [16:41:37] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
> [16:41:37] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
> [16:41:37] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
> [16:41:37] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
> [16:41:37] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
> [16:41:37] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 93, "": The  shader uses varying overlayColor, but previous shader does not write to it.
> Out of resource error.
> '
> [16:41:39] [Render thread/WARN]: Error encountered when linking program containing VS rendertype_item_entity_translucent_cull and FS rendertype_item_entity_translucent_cull. Log output:
> [16:41:39] [Render thread/WARN]: The  shader uses varying overlayColor, but previous shader does not write to it.
> Out of resource error.
> 
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find sampler named Sampler0 in the specified shader program.
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find sampler named Sampler2 in the specified shader program.
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find uniform named ModelViewMat in the specified shader program.
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find uniform named ProjMat in the specified shader program.
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find uniform named ColorModulator in the specified shader program.
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find uniform named Light0_Direction in the specified shader program.
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find uniform named Light1_Direction in the specified shader program.
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find uniform named FogStart in the specified shader program.
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find uniform named FogEnd in the specified shader program.
> [16:41:39] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 93, "" is not linked'
> [16:41:39] [Render thread/WARN]: Shader rendertype_item_entity_translucent_cull could not find uniform named FogColor in the specified shader program.
> [16:41:39] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
> [16:41:39] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
> [16:41:39] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
> [16:41:51] [Render thread/INFO]: Attempt 1...
> [16:41:51] [Render thread/INFO]: Applied 0 biome modifications to 0 of 105 new biomes in 3.105 ms
> [16:41:51] [Render thread/INFO]: Applied 0 biome modifications to 0 of 105 new biomes in 262.9 ?s
> [16:41:58] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
> [16:41:58] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
> [16:41:58] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
> [16:41:58] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
> [16:41:58] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
> [16:41:58] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1), Better End)
> [16:41:58] [Render thread/INFO]: Loaded 7 recipes
> [16:41:59] [Render thread/INFO]: Loaded 1137 advancements
> [16:42:00] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
> [16:42:00] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
> [16:42:00] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
> [16:42:00] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
> [16:42:00] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
> [16:42:00] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1), Better End)
> [16:42:01] [Render thread/INFO]: Loaded 7 recipes
> [16:42:01] [Render thread/INFO]: Loaded 1137 advancements
> [16:42:02] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
> [16:42:02] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
> [16:42:02] [Server thread/INFO]: Generating keypair
> [16:42:05] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
> [16:42:06] [Render thread/INFO]: Preparing spawn area: 0%
> [16:42:06] [Render thread/INFO]: Preparing spawn area: 0%
> [16:42:06] [Render thread/INFO]: Preparing spawn area: 0%
> [16:42:07] [Render thread/INFO]: Preparing spawn area: 1%
> [16:42:07] [Render thread/INFO]: Preparing spawn area: 1%
> [16:42:08] [Render thread/INFO]: Preparing spawn area: 4%
> [16:42:08] [Render thread/INFO]: Preparing spawn area: 5%
> [16:42:09] [Render thread/INFO]: Preparing spawn area: 6%
> [16:42:09] [Render thread/INFO]: Preparing spawn area: 9%
> [16:42:10] [Render thread/INFO]: Preparing spawn area: 12%
> [16:42:10] [Render thread/INFO]: Preparing spawn area: 13%
> [16:42:11] [Render thread/INFO]: Preparing spawn area: 17%
> [16:42:11] [Render thread/INFO]: Preparing spawn area: 20%
> [16:42:12] [Render thread/INFO]: Preparing spawn area: 20%
> [16:42:12] [Render thread/INFO]: Preparing spawn area: 25%
> [16:42:13] [Render thread/INFO]: Preparing spawn area: 30%
> [16:42:13] [Render thread/INFO]: Preparing spawn area: 33%
> [16:42:14] [Render thread/INFO]: Preparing spawn area: 36%
> [16:42:14] [Render thread/INFO]: Preparing spawn area: 42%
> [16:42:15] [Render thread/INFO]: Preparing spawn area: 44%
> [16:42:15] [Render thread/INFO]: Preparing spawn area: 51%
> [16:42:16] [Render thread/INFO]: Preparing spawn area: 57%
> [16:42:16] [Render thread/INFO]: Preparing spawn area: 62%
> [16:42:17] [Render thread/INFO]: Preparing spawn area: 69%
> [16:42:17] [Render thread/INFO]: Preparing spawn area: 74%
> [16:42:18] [Render thread/INFO]: Preparing spawn area: 80%
> [16:42:18] [Render thread/INFO]: Preparing spawn area: 85%
> [16:42:19] [Render thread/INFO]: Preparing spawn area: 90%
> [16:42:19] [Render thread/INFO]: Preparing spawn area: 97%
> [16:42:20] [Render thread/INFO]: Time elapsed: 14232 ms
> [16:42:20] [Server thread/INFO]: Changing view distance to 5, from 10
> [16:42:20] [Server thread/INFO]: Etheiy[local:E:4396e9ec] logged in with entity id 249 at (241.5, 71.0, 234.5)
> [16:42:20] [Server thread/INFO]: Etheiy joined the game
> [16:42:20] [Netty Local Client IO #0/INFO]: Applied 0 biome modifications to 0 of 105 new biomes in 284.6 ?s
> [16:42:21] [Server thread/INFO]: Saving and pausing game...
> [16:42:21] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
> [16:42:21] [Render thread/INFO]: Loaded 0 advancements
> [16:42:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
> [16:42:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
> [16:42:40] [Render thread/INFO]: Loaded 7 advancements
> [16:42:50] [Server thread/INFO]: [Etheiy: Set own game mode to Creative Mode]
> [16:42:50] [Render thread/INFO]: [CHAT] Set own game mode to Creative Mode
> [16:42:56] [Server thread/INFO]: Saving and pausing game...
> [16:42:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
> [16:42:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
> [16:42:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
> [16:42:57] [Server thread/INFO]: Etheiy lost connection: Disconnected
> [16:42:57] [Server thread/INFO]: Etheiy left the game
> [16:42:57] [Server thread/INFO]: Stopping singleplayer server as player logged out
> [16:42:57] [Server thread/INFO]: Stopping server
> [16:42:57] [Server thread/INFO]: Saving players
> [16:42:57] [Server thread/INFO]: Saving worlds
> [16:42:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
> [16:42:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
> [16:42:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
> [16:42:57] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
> [16:42:57] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
> [16:42:57] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
> [16:42:57] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
> [16:42:59] [Render thread/INFO]: Stopping!

ETA: I have just gone back to the 1.7 modpack, removed BetterEnd, made a new world and all of that, quit out and checked the log - no OpenGL errors appear. So it's either this or BC Lib which comes with it as far as I (a noob to this new way modding works) am aware.

**Comment by paulevsGitch** [comment]
You can downgrade bclib to 0.2.3, this is not a BE issue

**Comment by Raavea** [comment]
Oh wow you replied so quickly, okay, thank you! I'll go try that now, I'm pleased it's so simple :)
