### ISSUE TITLE
End portal isn't functioning properly

### ISSUE THREAD

**Issue by SpartanNamor** [paulevsGitch/BetterEnd#255]
The End portals will not teleport you to the End. I also have the BetterNether mod installed and Nether travel is not working eiter. I'm currently on a 1,16.5 server I made, the same thing is happening to other players.

**Comment by paulevsGitch** [comment]
If you mean vanilla End portals you probably need to check [this](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-missing-end-dimension)

**Comment by SpartanNamor** [comment]
Thanks, but I'm currently working on an Aternos server, and I don't know how to make that work. could you help please?

**Comment by paulevsGitch** [comment]
Download level.dat to local machine, edit it and upload it back when server if off
