### ISSUE TITLE
[Bug] Impossible to Create Aeternium Hammer

### ISSUE THREAD

**Issue by PartyPan** [paulevsGitch/BetterEnd#256]
Tell me if I am wrong but it is impossible to create the aeternium hammer if it is I have created a way to fix it using a data pack.

You can create the aeternium byt upgrading the netherite hammer using a aeternium ingot.

[Better End Craftable Aeternium Hammer.zip](https://github.com/paulevsGitch/BetterEnd/files/6866270/Better.End.Craftable.Aeternium.Hammer.zip)

**Comment by paulevsGitch** [comment]
Already known, already fixed

**Comment by paulevsGitch** [comment]
Fixed in 0.11.0
