### ISSUE TITLE
[Enhancement] Block seeing through Aurora crystals in 3rd person perspective

### ISSUE THREAD

**Issue by MaxwithanAxe** [paulevsGitch/BetterEnd#257]
You can just look through the crystals in the latest version of BetterEnd.
![2021-07-24_21 42 45](https://user-images.githubusercontent.com/68924364/126885048-51d7bb91-6e30-444d-be25-4513d449ab85.png)
![2021-07-24_21 42 57](https://user-images.githubusercontent.com/68924364/126885051-78e2e652-8029-40be-986d-d88bda1a31af.png)

**Comment by paulevsGitch** [comment]
This is a normal behaviour for all glass-like blocks

**Comment by paulevsGitch** [comment]
Implemented in 0.11.0
