### ISSUE TITLE
can't figure out how to make a custom recipe with infushion pedistal

### ISSUE THREAD

**Issue by Lostdinosour** [paulevsGitch/BetterEnd#258]
i can't figure out how to make a custom recipe with infushion pedistal. i used the template but still cant figure it out.

**Comment by seishin4real** [comment]
did you figure it out?
I'm trying to add a recipe for a book with a modded enchantment

currently I've got an enchanted_book.json file - I've tried placing it in `data/minecraft/recipes/`, `data/veinmining/recipes/` and `data/custom-pack/recipes/`, but it's not working
`{
	"type": "betterend:infusion",
	"input": "minecraft:book",
	"result": {
		"item": "minecraft:enchanted_book",
		"count": 1,
		"nbt": "{StoredEnchantments:[{id:\"veinmining:vein_mining\",lvl:1}]}"
	},
	"time": 10,
	"catalysts": {
		"north":      "minecraft:diamond_pickaxe",
		"north_east": "minecraft:lapis_lazuli",
		"east":       "betterend:amber_gem",
		"south_east": "minecraft:lapis_lazuli",
		"south":      "minecraft:hanging_roots",
		"south_west": "minecraft:lapis_lazuli",
		"west":       "betterend:amber_gem",
		"north_west": "minecraft:lapis_lazuli"
	}
}
`
also tried dirt.json with 
`{
	"type": "betterend:infusion",
	"group": "infusion",
	"input": "minecraft:book",
	"result": {
		"item": "minecraft:dirt",
		"count": 1
	},
	"time": 10,
	"catalysts": {
		"north":      "minecraft:diamond_pickaxe",
		"east":       "minecraft:hanging_roots",
		"south":      "minecraft:hanging_roots",
		"west":       "minecraft:hanging_roots"
	}
}
` - still nothing..

**Comment by paulevsGitch** [comment]
Example of simple and correct recipe:
```
{
	"type": "betterend:infusion",
	"input": {
		"item": "minecraft:apple"
	},
	"result": {
		"item": "minecraft:stone",
		"count": 1
	},
	"time": 10,
	"catalysts": {
		"north": "minecraft:apple",
		"south": "minecraft:apple",
		"east": "minecraft:apple",
		"west": "minecraft:apple"
	}
}
```
