### ISSUE TITLE
[Enhancement] Update recipes on wiki

### ISSUE THREAD

**Issue by Lostdinosour** [paulevsGitch/BetterEnd#259]
i can't figure out how to make a custom infusion recipe. i tried using the template but it did not work.
{
     "group": "infusion",
    "input": "betterend:terminite_block",
    "result": {
        "item": "minecraft:ghast_tear",
        "nbt": "{}" 
    },
    "catalysts": {
        "north":      "betterend:enchanted_petal",
        "north_east": "betterend:ender_dust",
        "east":       "betterend:crystal_shards",
        "south_east": "betterend:ender_dust",
        "south":      "betterend:crystal_shards",
        "south_west": "betterend:ender_dust",
        "west":       "betterend:crystal_shards",
        "north_west": "betterend:ender_dust"
    }
}

**Comment by Lostdinosour** [comment]
there are spaces before the lines but i dont know how to make it in a code thingy

**Comment by paulevsGitch** [comment]
Template on wiki is a bit outdated, example:
```
{
	"type": "betterend:infusion",
	"input": {
		"item": "minecraft:apple"
	},
	"result": {
		"item": "minecraft:stone",
		"count": 1
	},
	"time": 10,
	"catalysts": {
		"north": "minecraft:apple",
		"south": "minecraft:apple",
		"east": "minecraft:apple",
		"west": "minecraft:apple"
	}
}
```
Also NBT tag is not required if your item don't have any NBT

**Comment by Lostdinosour** [comment]
oh ok thanks

**Comment by paulevsGitch** [comment]
Done, wiki is now updated
