### ISSUE TITLE
[Compatibility] Smith Hammers for BetterNether

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#26]
Given that you are the developer of both BetterNether and BetterEnd, I would love to see this mod's smith hammers be made available for BetterNether's tool material types: Cincinnasite, Cincinnasite-diamond and Nether ruby.~

**Comment by paulevsGitch** [comment]
As this should be done from BetterNether side I put this suggestion [here](https://github.com/paulevsGitch/BetterNether/issues/255)
