### ISSUE TITLE
[Bug] Dry Shrubland in overworld and scuffed terrain in the End

### ISSUE THREAD

**Issue by dustplayschaos** [paulevsGitch/BetterEnd#260]
Hey! So, I updated my 1.16.5 world (which had the 1.16.5 better end mod) to 1.17.1 with the better end mod and a series of problems started happening. First, I kept getting a error message from optifine. Then, when going through the end portals around the end island, some of the portals (which I had never been through) had the regular minecraft end, then when hitting the chunk border, switched to the Better End, creating some really scuffed end islands and cliffs. Finally, when loading in new chunks in the overworld, there were sections of ocean and river that were biome changed to Better End Dry Shrubland. These problems don't show up in worlds that I start in 1.17.1, so I think it might be because of the updating to 1.17.1, but I don't know how to fix it. Is there a way to fix it?

**Comment by paulevsGitch** [comment]
> First, I kept getting a error message from optifine

I think that this is optifine issue, but can you please show it?

> regular minecraft end, then when hitting the chunk border, switched to the Better End

Different mod versions are different not only in MC version, but in content too. The same will happen if you update MC world from 1.6 to 1.12 or 1.17 - world generation and biome generation are different, and there will be borders between old and new chunks

> there were sections of ocean and river that were biome changed to Better End Dry Shrubland

You can check your fabricDynamicRegistry.dat in world/data folder with NBTExplorer, some biomes can have zero ID (ocean) or wrong overlapping IDs, you can fix this manually by changing them.

> These problems don't show up in worlds that I start in 1.17.1

All these problems are related to updating old world to new version, but they are mostly fixable. You can also keep the main island and reset outer end to allow it regenerate. Central island has a set of regions: -1 -1, -1 0, 0 -1, 0 0

**Comment by Fabizocker456** [comment]
But why tf are you using optifine when there is sodium and ctm?

**Comment by dustplayschaos** [comment]
The optifine error said OpenGL Error: 1281, but when I went and fixed that error, it changed to OpenGL Error: 1282. I think they are just optifine issues, but it's something that if it's not fixable is just able to be turned off and ignored. The only weird thing about the optifine error is that it only happens in the world with the other issues I mentioned, which to me says it'll probably get fixed when I do the fixes you said. Thank you for the help! (also, I use optifine because I like it and it lets me have a custom cape for my elytra wings)
