### ISSUE TITLE
[Bug] Regeneration on the Crystalite Armor set not working

### ISSUE THREAD

**Issue by Aljabe** [paulevsGitch/BetterEnd#262]
Currently the armor constantly re-applies the effect. However, regeneration requires a set amount of uninterrupted time to work and because the effect is continually reset the regeneration never occurs. Please fix.

**Comment by Aljabe** [comment]
It's a known issue modders have, there is advice available online if that helps.

**Comment by LifeWatcher123** [comment]
> It's a known issue modders have, there is advice available online if that helps.

Do you still have a link to said advice online? I would like to learn that.

**Comment by paulevsGitch** [comment]
> Do you still have a link to said advice online? I would like to learn that

Don't apply effect on each entity tick, that's all

**Comment by paulevsGitch** [comment]
Fixed in 0.11.0
