### ISSUE TITLE
hanhandleDisconnection() called twice

### ISSUE THREAD

**Issue by ohGunter** [paulevsGitch/BetterEnd#265]
when I try to join my local Fabric server, I get disconnected and the console shows this error: handleDisconnection () called twice
Fabric 1.17.1

**Comment by paulevsGitch** [comment]
BE doesn't handle disconnection, can you please send your logs?

**Comment by ohGunter** [comment]
> BE doesn't handle disconnection, can you please send your logs?

Sure. 
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/6911875/latest.log)

**Comment by paulevsGitch** [comment]
Thank you, can you please send client logs too? Are mods and configs same on client and server?

**Comment by ohGunter** [comment]
![37357002_2010772552307885_3818251391005097984_n](https://user-images.githubusercontent.com/73723099/127754294-9882074d-6fa6-40ad-a2f2-5a39f96b0c9d.jpg)
I forgot to install the mods on the client side :c
My bad
