### ISSUE TITLE
Error rendering semi transparent entites

### ISSUE THREAD

**Issue by darkreality952** [paulevsGitch/BetterEnd#268]
When using the better end mod there is an issue that causes semi tranpsarent entites such as experience orbs or the phantom from the origins mod to render incorrectly and appear full white with some visual bugs, however this only happens sometimes as sometimes in the case of the phantom the entity just renders fully opaque instead. i tested this with the latest version of the better end mod and bclib on fabric 1.17.1 here is my log file:
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/6912615/latest.log)

**Comment by paulevsGitch** [comment]
This is already fixed in BCLib 0.3.0, it is just not out yet. Try to move vanilla resourcepack above others - it should fix this issue
