### ISSUE TITLE
New Chorus flower model doesn't line up with sideways plants

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#27]
I noticed, growing Chorus plants with this mod installed, that your lovely new Chorus flower model doesn't connect to the plant if the flower grows sideways. The flower in the screenshot below generated naturally.
![2020-11-29_22 01 04](https://user-images.githubusercontent.com/69029346/100574350-b1859a80-328e-11eb-9a0d-52e378f07153.png)

**Comment by paulevsGitch** [comment]
I think I can fix this with some model modification

**Comment by paulevsGitch** [comment]
Fixed in 0.8.0 (I think)
