### ISSUE TITLE
Fabric crashing with BetterEnd

### ISSUE THREAD

**Issue by topbun92** [paulevsGitch/BetterEnd#270]
Game launches without BE, but crashes with it. no idea why.

[BE crash report.txt](https://github.com/paulevsGitch/BetterEnd/files/6913384/BE.crash.report.txt)

**Comment by paulevsGitch** [comment]
This looks like a mod conflict:
> Caused by: java.lang.ArrayIndexOutOfBoundsException
> ...
> io.github.**kosmx.bendylib**.ModelPartAccessor.getCuboid
> at net.minecraft.class_572.handler$dde000$**initBend**(class_572.java:564)

> 	Fabric Mods: 
		...
		**bendy-lib: Bendy api 2.0.1**
		...

Can you please try it without this mod?

**Comment by topbun92** [comment]
sorry, just got a chance to try it. took a while to find out what the bendy api was from but its emotecraft. updated that mod and everything works fine.

**Comment by paulevsGitch** [comment]
Ok, thank you, I will close this issue
