### ISSUE TITLE
betterend biome names stuck on Blossoming Spires??  

### ISSUE THREAD

**Issue by JonCaver** [paulevsGitch/BetterEnd#272]
I have an interesting problem. When I am traveling through different end biomes  the F3 Biome name always says Blossoming Spires regardless of which (Better End) biome i am in.  It still works fine for the minecraft original biomes in the end but all of the Better End biomes say Blossoming Spires?? Any thought??

1.17.1 current version of mod and bclib.
World (save) was made with mods installed on 1.17 and has only upgraded to 1.17.1 with no problems.

**Comment by paulevsGitch** [comment]
Can you please check your fabricDynamicRegistry.dat in world data folder (with NBT Explorer) and your biome source in level.dat like described [here](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source)? In fabricDynamicRegistry all biomes should have different ID (and larger then zero), biome source must be "betterend:better_end_biome_source"

**Comment by JonCaver** [comment]
All of the betterend biomes are 0 in the fabricDynamicRegistry.dat 
The biome source is correct tho!

**Comment by JonCaver** [comment]
The new world works fine so something must have gotten corrupted with this save I'm thinking!! Any ideas on a fix??

**Comment by JonCaver** [comment]
Fixed itself once I left the end, saved, reloaded the game, went into the end again!!

**Comment by paulevsGitch** [comment]
> All of the betterend biomes are 0 in the fabricDynamicRegistry.dat

0 is "minecraft:ocean" biome ID, all biome IDs must be unique numbers. If some values are wrong you can correct them manually. All these operations should be done when MC is inactive
