### ISSUE TITLE
game crashes when running fabric 1.17.1 with BetterEnd

### ISSUE THREAD

**Issue by gmZynx** [paulevsGitch/BetterEnd#278]
i tried this without any other mods and the game crashes every time i try to launch it

it says this on the minecraft launcher:
> The game crashed whilst initializing game
> Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
> Exit Code: -1

crash report
[crash-2021-08-10_12.48.01-client.txt](https://github.com/paulevsGitch/BetterEnd/files/6960663/crash-2021-08-10_12.48.01-client.txt)

**Comment by paulevsGitch** [comment]
You are using BCLib 0.3.0 with Better End 0.10.5-pre, they are not compatible. Please use BCLib 0.2.4 for this version
