### ISSUE TITLE
Better End structures engulfing End Cities

### ISSUE THREAD

**Issue by Greg-J** [paulevsGitch/BetterEnd#28]
Seed: 1083719637794
Version: Fabric 1.16.4

Half of the End Cities I have found so far on this seed are engulfed in structures (mountains/pillars) that Better End generates making exploring The End more frustrating than vanilla.

**Comment by paulevsGitch** [comment]
Can you please send some screenshots and seed + coordinates?

**Comment by Orb-2** [comment]
I've experienced a similar issue
the seed is 3577979566503665858 and the coordinates are -6630 / ~ / -7293

![Intersection 2](https://user-images.githubusercontent.com/75752187/101675071-358b0f80-3a51-11eb-87ce-0f1033dc2536.png)

**Comment by paulevsGitch** [comment]
Thing on screenshot above is a normal MC structure behaviour, so I will close this
