### ISSUE TITLE
[Bug] Some fields in generator.json don't have any effect

### ISSUE THREAD

**Issue by donaastor** [paulevsGitch/BetterEnd#280]
I have changed a few settings in config/betterend/generator.json file, but none of them has made any change in the game. I have changed: dragon fight to false, swap overworld with end to true, no ring void to true. I am using 1.17.1 version of minecraft and 0.11-0 fabric version of the mod.

Same happens when I downgrade the mod to 0.10.5 fabric version and BClib to 0.2.4.

**Comment by paulevsGitch** [comment]
Did you change the cofig when your game was off?

**Comment by donaastor** [comment]
> Did you change the cofig when your game was off?

yes

**Comment by paulevsGitch** [comment]
Can you please send your config file?

**Comment by donaastor** [comment]
> Can you please send your config file?
Yes. You can see them all on this google drive link: https://drive.google.com/drive/folders/1a9qe9Wxuf6BgpTG3rJe0r-jjGJvVnH8B?usp=sharing
![othermods](https://user-images.githubusercontent.com/45340801/129027374-87351a2e-349d-407f-b242-e16716fb6e06.png)
I have also shared a photo of other mods that I have installed. Of course, I would choose only one version per test.

**Comment by paulevsGitch** [comment]
Sorry for the late response

I tested this values, and seems like swap and noRingVoid are not working. Swap was tested earlier and it causes too many bugs in 1.17, so this feature will be removed later. I recommend you to use [this mod](https://www.curseforge.com/minecraft/mc-mods/globalspawn) as it allows to change spawn dimension. (It is a Fabric mod, but for unknown reasons it don't have this tag on CurseForge)

To disable void ring you need to set its value to some numerical value, example:
> "voidRingSize [default: 1000]": 50

I will look into code, probably when I added configurable size I suddenly disabled possibility to remove void. Actually boolean value for void is unnecessary now as you can just change its size to small value (its better to use values above 0 if you want to have central island - if you will use 0 islands can generate inside central island)

![2021-08-13_19 11 47](https://user-images.githubusercontent.com/17707380/129388500-5e49a01e-989f-40d5-8de2-f0ee54399c43.png)

**Comment by paulevsGitch** [comment]
Fixed in 0.12.1
