### ISSUE TITLE
Can't make Better End tool handles in any anvils

### ISSUE THREAD

**Issue by VexenStick** [paulevsGitch/BetterEnd#284]
Whenever I try make a tool handle out of any material for the Better End, it doesn't work.

**Comment by paulevsGitch** [comment]
Do you have anvil and hammer of proper level?

**Comment by VexenStick** [comment]
I have been doing it by just getting an anvil out of creative and a hammer, such as diamond. There aren't many tutorials out there for the mod so I've been a bit clueless.

**Comment by paulevsGitch** [comment]
> There aren't many tutorials out there for the mod so I've been a bit clueless.

You can use [REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items). If you are using ordinal anvil and diamond hammer - most tool parts will be not available for crafting
