### ISSUE TITLE
[1.16.5] Anvil Crash

### ISSUE THREAD

**Issue by szumaster** [paulevsGitch/BetterEnd#285]
https://pastebin.com/xYhL730M

More than 5 bugs ahead, + new when I'm put the anvil on floor - game crash'd.

Can you backport some fixes?

Regards,
team.css/szu

**Comment by paulevsGitch** [comment]
All bugs with anvils were fixed in newer BCLib versions. 1.16.5 is not supported anymore. If you want you can use BetterEnd 0.9.6 (the last version before BCLib dependency)

**Comment by szumaster** [comment]
Thanks :)
