### ISSUE TITLE
End Main Island (Forge 1.16.5)

### ISSUE THREAD

**Issue by ohGunter** [paulevsGitch/BetterEnd#286]
When I make a new world, the main island of the End does not generate like in Fabric.
![2021-08-14_14 48 56](https://user-images.githubusercontent.com/73723099/129460271-8a235671-74ad-4f92-9bc5-63d8c92936f1.png)
![2021-08-14_15 16 51](https://user-images.githubusercontent.com/73723099/129460276-5606d5ef-ba60-4f27-9b41-9f36795e269e.png)

**Comment by paulevsGitch** [comment]
BetterEnd is a Fabric mod. All Forge port issues are not related to BE
