### ISSUE TITLE
[1.17.1] Ores can be broken with any vanilla pickaxe

### ISSUE THREAD

**Issue by kwpugh** [paulevsGitch/BetterEnd#287]
Hi,

Not sure if this was intended or not, but the three ores in BetterEnd can be broken with any vanilla pickaxe (wood, stone, iron, etc.).   

Using latest of BettterEnd and BCL

WHIT also shows it as harvestable.

![2021-08-15_20 41 14](https://user-images.githubusercontent.com/8809210/129500936-ad779cd2-8436-4d3b-86bf-8e98860cc393.png)

**Comment by paulevsGitch** [comment]
All ores have same level of mining, and it is the same as stone, this is intended
