### ISSUE TITLE
[Bug] not compatible with dashloader, the textures become missing.

### ISSUE THREAD

**Issue by dandaifuku** [paulevsGitch/BetterEnd#289]
Most textures, seemingly picked at random from the better end mod are missing in the end. It just shows pink and black checkered blocks. (terrain gen was working fine). I was testing compatibility with all the other mods I had installed and I found that it was the dashloader mod that was causing the missing textures issue. I had it installed in my custom modpack from the better minecraft modpack I picked apart. I have no attachment to it except that it promises faster loading by using caches, (I'm no techy sorry) so I'll just play without it. I figured you guys might've wanted to know! :)

**Comment by paulevsGitch** [comment]
Dashloader use system that is compatible only with vanilla models and not compatible with Fabric API models or custom models. This compatibility is completely on Dashloader side
