### ISSUE TITLE
[Enhancement] Enhance moth AI to prevent large distant flights from nest

### ISSUE THREAD

**Issue by Britterscotch** [paulevsGitch/BetterEnd#292]
When a nest is placed overland silk moth's spawn continuously and never return to the nest. 
1. The nest was on a high elevation, they fluttered down to a swamp at much lower elevation and took residence. 
2. They went on an exploration across the swamp to spread their mothy ways. 
3. The nests pointed this direction never made any silk.
![2021-08-23_18 43 34](https://user-images.githubusercontent.com/30934532/130535335-521d6b6a-e1b3-479c-b45d-2cb60e091db3.png)

**Comment by paulevsGitch** [comment]
Looks like you have problems with biome registry, you need to check fabricDynamicRegistry.dat in world data folder, all biome entries should have unique ID

**Comment by paulevsGitch** [comment]
Moths from nests have a check if they are far away from nest, and they should return to it after some time

**Comment by paulevsGitch** [comment]
Now they will try to return into nest more frequently and will detect it on larger distance

**Comment by paulevsGitch** [comment]
Fixed in 0.12.5
