### ISSUE TITLE
All Oceans in the Overworld are suddently turned into Blossoming Spires

### ISSUE THREAD

**Issue by JalapenoGremlin** [paulevsGitch/BetterEnd#293]
Apparently The BetterEnd uses id == 0 for the Blossoming Spires Biome which conflicts with the Vanilla id for the Ocean Biome. So all of the Ocean Biomes in the overworld are turning into Blossoming Spires. 

How to reproduce:
create a world. 
/tp to the neareset ocean (not cold ocean, or warm ocean, but "minecraft:ocean")
Observe that the biiome is Blossoming spires (complete with Silk Moths).

**Comment by paulevsGitch** [comment]
BetterEnd does not assing ID to its biomes, this is a bug in fabricDynamicRegistry.dat in your world/data folder. You need to fix it manually

**Comment by JalapenoGremlin** [comment]
So use NBTExplorer on fabricDynamicRegistry.dat and remove all the entries in minecraft:worldgen/biome?

That is remove the keys like the following:
`betterend:amber_land: 0`
`betterend:blossoming_spires: 0`
etc.
