### ISSUE TITLE
Crafting is broken

### ISSUE THREAD

**Issue by Imburdalinix** [paulevsGitch/BetterEnd#294]
I can't craft Aeternium armor or tools, because a Aeternium Hammer is required, but to craft one I need an Aeternium hammer. so I need a hammer to craft a hammer... that's not logical. can someone help me?
<img width="524" alt="Bildschirmfoto 2021-08-25 um 15 37 19" src="https://user-images.githubusercontent.com/85232768/130800718-ec00b758-189e-41c6-8262-aa92ea0edd3b.png">

**Comment by paulevsGitch** [comment]
Your mod version is outdated

**Comment by Imburdalinix** [comment]
I mean like, losing my items from the better end mod or is it like an Update? do I lose the stuff from better end when updating?

**Comment by paulevsGitch** [comment]
It depends on how you are updating. What stops you from just making a backup?
