### ISSUE TITLE
a advice

### ISSUE THREAD

**Issue by lkqyyds** [paulevsGitch/BetterEnd#297]
There is no decoration on the main island

**Comment by lkqyyds** [comment]
i wonder if you would like to add decoration on the main island

**Comment by paulevsGitch** [comment]
Can you please explain what do you mean under decoration?

**Comment by lkqyyds** [comment]
Decorate Obsidian columns and squares on the main island with beautiful squares

**Comment by paulevsGitch** [comment]
Main island already have decoration for columns and portal
