### ISSUE TITLE
logs explode with dash loader.

### ISSUE THREAD

**Issue by jklw10** [paulevsGitch/BetterEnd#298]
![image](https://user-images.githubusercontent.com/8884828/131528229-6f5ed938-0882-4627-bd2f-281978462e0c.png)
i'll post the full logs if needed but i'm still trying to see if i can even launch the game.

**Comment by Fireface677** [comment]
Dash loader is incompatible.

**Comment by jklw10** [comment]
is there a way you could fix this on your side or is it more feasible for dashloader?

**Comment by Fireface677** [comment]
The problem is on their side
![image](https://user-images.githubusercontent.com/62745466/131529149-a7e08ef3-8ffa-4c4e-8fca-285a3dbd3f6c.png)

**Comment by jklw10** [comment]
ah i see it's marked as a wont fix. thanks anyways. i'll see if someone on dashloaders side is able to do something about this.

**Comment by jklw10** [comment]
actually it seems opening is possible just very slow. for the first time.

**Comment by Fireface677** [comment]
yes

**Comment by paulevsGitch** [comment]
Duplicate of #289
