### ISSUE TITLE
BetterEndForge-1.16.4-1.6.0 crashes when teleport to the end islands

### ISSUE THREAD

**Issue by WiRyFo** [paulevsGitch/BetterEnd#299]
Minecraft crashes when I teleport to the end islands after defeating the Ender Dragon. I manage to upload a few chunks, but then the game just crashes.
P.S. I don't speak English and use Google Translate.
Crashlog file:
[crash-2021-08-31_21.03.58-server.txt](https://github.com/paulevsGitch/BetterEnd/files/7085199/crash-2021-08-31_21.03.58-server.txt)

**Comment by paulevsGitch** [comment]
BetterEnd is a Fabric mod

**Comment by Fireface677** [comment]
What he wants to say is that you have to ask questions about the forge version on their github page because it's a completely different team working on it so we can't help you and are not responsible for that.
