### ISSUE TITLE
Rename function in ChunkSerializerMixin

### ISSUE THREAD

**Issue by linzexin022** [paulevsGitch/BetterEnd#3]
Hi there, I found a tip in game log:

`Method overwrite conflict for method_12385 in betternether.mixins.common.json:ChunkSerializerMixin, previously written by ru.betterend.mixin.common.ChunkSerializerMixin. Skipping method.`

Shouldn't be a big issue :)

**Comment by paulevsGitch** [comment]
This mixins do the same thing, so this is not an issue

**Comment by paulevsGitch** [comment]
I can rename function to prevent this message appearing

**Comment by paulevsGitch** [comment]
Renamed in 0.3.0
