### ISSUE TITLE
End Portal Disabled

### ISSUE THREAD

**Issue by Sageverse** [paulevsGitch/BetterEnd#30]
Im Pairing this mod with the BetterNether mod, The Nether Portal works absolutely fine but the End Portal is disabled, i can place eyes and turn it on but going through the portal isnt working, its like its an air block or such

**Comment by paulevsGitch** [comment]
Looks like you End dimension entry is missing, you can check your level.dat it with NBTEditor, it should look like [this](https://github.com/paulevsGitch/BetterEnd/issues/10#issuecomment-722599621). If this entry is missing you can add it manually with NBTEditor

**Comment by paulevsGitch** [comment]
As there is no response I’m closing this
