### ISSUE TITLE
When loading specific chunks in 1.17.1 on the latest version, the internal server hangs.

### ISSUE THREAD

**Issue by Alkiasan** [paulevsGitch/BetterEnd#301]
Here's a crash report... is this betterend related? I see it in the report but i'm not sure.
https://gist.github.com/Alkiasan/42d9d03811ef3e6691b5278528df3441

**Comment by paulevsGitch** [comment]
> at net.minecraft.class_1937.**getChunkLithium**(class_1937.java:2096)

Do you have Lithium installed? Looks like one of its mixins failed

**Comment by Alkiasan** [comment]
Yes, I do

**Comment by Alkiasan** [comment]
It's a 1.16 world that i've upgraded to 1.17, i'm trying --ForceUpgrade atm to see if it fixes it..

**Comment by Alkiasan** [comment]
Issue still persists...

**Comment by Alkiasan** [comment]
Did some testing.
Got betterend 1.16.5, created a new world, and placed an Infusion Pedestal.
Closed the world, downloaded the latest BetterEnd for 1.17.1, and attempted to load the same world, then it just hung upon loading the infusion pedestal's chunks...
Is there a way to fix this?

**Comment by paulevsGitch** [comment]
Sounds like vanilla entity bug as the ID of entity is the same. You can remove pedestal from chunk with NBTExplorer

**Comment by Alkiasan** [comment]
Hi, sorry, can you explain to me how to do this? I'm not too experienced
with nbt explorer

**Comment by paulevsGitch** [comment]
Simple way of how to do this:
- Open you region files (in region folder) with NBTExplorer, if you have only one region in world - you can open only it, region numbers will be block position X and Z divided by 512 and rounded to lower value (23.5 -> 23, for example)
- Search for the value "betterend:infusion_pedestal" with NBTExplorer search, it will find it in chunk section palettes
- Replace it with minecraft:air and remove Properties compound tag near it (if it exists)

After world loading the block will be replaced to air. Don't forget to make a backup

Example of block in palette, with properties and without:
![image](https://user-images.githubusercontent.com/17707380/131704452-2f59ff9d-d083-4efb-a273-d50a2f47a5b2.png)

**Comment by Alkiasan** [comment]
It also comes up as a result here.. Do i do anything with this? 
![image](https://user-images.githubusercontent.com/62717881/131705260-376547f8-75b2-4f66-8017-97a9a1107161.png)

**Comment by paulevsGitch** [comment]
Replace id with "minecraft:air" and remove all tags except id in this group

**Comment by Alkiasan** [comment]
It worked, thank you! I need to ask my players to see who else had infusion pedestals placed somewhere and try and get them all removed hahah. Strange how this doesn't happen with normal pedestals though..

**Comment by Alkiasan** [comment]
Closing the issue, as a solution has been found
