### ISSUE TITLE
silk moths spawn randomly in the overworld

### ISSUE THREAD

**Issue by LolXD89** [paulevsGitch/BetterEnd#302]
Hello as it says in the title those weird pink  flying creatures spawn randomly in the overworld above the cold and luke_warm oceans and some other biomes when I open the debug screen it says blossoming_spires instead of the current biome in the overworld

**Comment by paulevsGitch** [comment]
You need to fix your fabricDynamicRegistry.dat in your world/data folder, it was already explained in some older reports: #293, #272, #195
