### ISSUE TITLE
[Fabric, 1.17.1] Better End Biomes missing

### ISSUE THREAD

**Issue by squidflex** [paulevsGitch/BetterEnd#304]
Greetings!
I'm running a slightly tweaked AoF4 1.17.1 server. 
We immediately noticed that that the Better End biomes are missing from the End dimension.
After following the tutorial here to correct the biome source, the end dimension disappeared from the level.dat.
I restored it from a backup, but I cannot set the biome source type without getting an error. 
This appears to be the cause of the End being removed from the level.dat.
I'm assuming there is a mod conflict or something, but i'm at a loss...
Any assistance is greatly appreciated!

Here's the error:
https://pastebin.com/qN7EcFnY

Here's my list:
https://pastebin.com/dwQNN6jX

Thanks!

**Comment by paulevsGitch** [comment]
Hi, your error is:

> ResourceKey[minecraft:dimension_type / betterend:better_end_biome_source] missed

Looks like you changed the dimension type from "minecraft:the_end" to "betterend:better_end_biome_source" which is incorrect, and MC just removed invalid dimension entry. This is not mod conflict, this is just incorrectly replaced biome source. Please change it to the same format as [shown on the wiki](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source). Biome source string should replace only biome source, all other generator values should be the same as in vanilla.

![image](https://user-images.githubusercontent.com/17707380/132588395-d1137789-543b-4df2-a799-37d3b1c53a11.png)

**Comment by squidflex** [comment]
Hi @paulevsGitch - thanks for your assistance.
That was probably the issue at for that error message - however, my End dimension still isn't generating any of the BetterEnd biomes, etc.
I've followed the tutorial and recreated the dimension numerous times, but all i get is a single End island with the Dragon.
Again, I'm assuming something is preventing your generator from running, but I don't know what.

Just for the sake of testing, i create a new Minecraft 1.17.1 instance with only Fabric, BetterEnd, & BCLib. I'm still only getting the central Dragon island. Aren't there supposed to be a bunch of other islands with a variety of biomes?

Mods:
bclib-0.2.4.jar
better-end-0.10.5-pre.jar
fabric-api-0.37.2+1.17.jar
&
bclib-0.3.1.jar
better-end-0.11.0-pre.jar
fabric-api-0.37.2+1.17.jar

Here's a screenshot:
![2021-09-14_10 27 27](https://user-images.githubusercontent.com/30320565/133276617-40ae44df-a46f-4696-8c34-f4e256d44bf6.png)

**Comment by paulevsGitch** [comment]
> I've followed the tutorial and recreated the dimension numerous times, but all i get is a single End island with the Dragon.

All outer End islands are 1000 blocks away from central island ([like in vanilla](https://minecraft.fandom.com/wiki/The_End?file=EnderIslandsRender.jpg)), if you want them to generate closer - change voidRingSize in minecraft/config/betterend/generator.json to lower value

**Comment by squidflex** [comment]
@paulevsGitch - that was it! 
i had to travel out about 63 chunks before anything generated. The AoF3 pack must've decreased the generation distance - which is what I'll do as well. Thanks again!

**Comment by paulevsGitch** [comment]
63 * 16 = 1008, BE has default value 1000, so this is just default config value
