### ISSUE TITLE
New slime

### ISSUE THREAD

**Issue by Samisaprogrammer** [paulevsGitch/BetterEnd#305]
Can there be new blue slime you get from killing the end slimes? Would be nice to have

**Comment by Fireface677** [comment]
And what special properties should it have?

**Comment by Samisaprogrammer** [comment]
nothing. Just an aesthetic thing to match the entity

**Comment by Fireface677** [comment]
But all end slimes have different colors.

**Comment by Samisaprogrammer** [comment]
Wait, they do? I've only seen blue ones. Might be worth filing a bug report if I can provide screenshots when I have time.

**Comment by Fireface677** [comment]
Different biomes have different slimes

**Comment by Fireface677** [comment]
Like purple in chorus forest or yellow in amberlands

**Comment by Samisaprogrammer** [comment]
Ah. That. I haven't gotten around to exploring, sorry. I still think it would be a cool idea

**Comment by paulevsGitch** [comment]
All slimes drop vanilla slimeballs, this is unlikely to be changed, there are no valuable reasons to add custom slimeballs only for color difference
