### ISSUE TITLE
ALL Biomes are long and skinny microbiomes in Multiplayer!

### ISSUE THREAD

**Issue by Theobot3782** [paulevsGitch/BetterEnd#307]
I saw how In singleplayer biomes generate just fine, but when I play multiplayer, the biomes are long and skinny, and not all of them even generate at all,  I love this mod, but pls fix this bug! :)

**Comment by paulevsGitch** [comment]
Fix your biome source, this was already mentioned in FAQ, [on Wiki](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source) and Discord server
