### ISSUE TITLE
[Suggestion] Add bone meal to gunpowder recipe match Education Edition

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#31]
In the *Education Edition* of Minecraft, gunpowder can be assembled using coal or charcoal, bone meal, and the *Education Edition's* sulfur item. *Better End's* gunpowder recipe comes very close to this, so I would like to suggest adding bone meal to this recipe to match the Minecraft 'canon' presented in Education Edition.~

**Comment by paulevsGitch** [comment]
Added in 0.8.1
