### ISSUE TITLE
Can't remove recipes

### ISSUE THREAD

**Issue by Muffintiem** [paulevsGitch/BetterEnd#310]
Recipes are still working in the game despite setting them to false in the config. This worked fine in Better Nether.

**Comment by paulevsGitch** [comment]
This thing requires testing

**Comment by paulevsGitch** [comment]
This is a bug on BClib side, will be fixed later

**Comment by paulevsGitch** [comment]
https://github.com/paulevsGitch/BCLib/issues/50
