### ISSUE TITLE
Vanilla biomes don't have all entries in the config

### ISSUE THREAD

**Issue by HadrianFaerwald** [paulevsGitch/BetterEnd#311]
Unlike the rest of the file, the center island portion doesn't come with any of the other "settings" that the modded biomes come with. I was going to disable the caves that the center island had, but cannot due to this bug 
![image](https://user-images.githubusercontent.com/84944874/134631687-2ae945fe-997a-4528-8fe3-7619115145af.png)
Also forgive me if I didn't format this correctly, as I've never used GitHub before

**Comment by paulevsGitch** [comment]
Fixed in 0.12.1
