### ISSUE TITLE
Is this a texture bug? please help me

### ISSUE THREAD

**Issue by Nanszin** [paulevsGitch/BetterEnd#312]
I'm playing Better Minecraft 1.17.1 0.11.6 and the BetterEnd have a lot of items (most of the itens) with this bug
![2021-09-26_15 24 21](https://user-images.githubusercontent.com/91431594/134819653-abdee986-b528-41ac-9c23-6a36d03ebbb4.png)
![2021-09-26_15 24 47](https://user-images.githubusercontent.com/91431594/134819655-b0efc2ae-6215-427c-ab33-e7670e587923.png)
.

**Comment by MaNDaNgEr** [comment]
can anyone also help me with this same problem ?

**Comment by Nanszin** [comment]
@MaNDaNgEr  Hey, i I managed to solve this excluding dashloader-2.0 from mods.

**Comment by paulevsGitch** [comment]
It is a Dashloader issue, not BE one

**Comment by alphaqu** [comment]
It is a BE issue, not a DashLoader one

**Comment by paulevsGitch** [comment]
No, its only Dashloader issue as it can't properly work with Fabric API models

**Comment by alphaqu** [comment]
You aren't using fabric api models...

**Comment by paulevsGitch** [comment]
No, BCLib uses Fabric API as a model provider

**Comment by MaNDaNgEr** [comment]
yes but when when i removed dashloader mod it was fine then

**Comment by MaNDaNgEr** [comment]
dashloader mod was also affecting some other mods textures like betterend
mod when i removed dashloader than better end was also working fine
