### ISSUE TITLE
Dimension swap not working

### ISSUE THREAD

**Issue by YousifTheGamer1** [paulevsGitch/BetterEnd#313]
I'm trying to swap dimensions so that I spawn in the End but the when I change it in the config I create a new world it doesn't seem to be working. I also am using GDLauncher if that makes a difference.

**Comment by paulevsGitch** [comment]
Did you restart your game after option changes? This thing can be also related to #251, its better to use [this mod](https://www.curseforge.com/minecraft/mc-mods/globalspawn) instead of BE world swap. World swap will be probably removed in the next release due to its buggy behaviour
