### ISSUE TITLE
End platform spawns too far from island causing frequent void death

### ISSUE THREAD

**Issue by SuddenTurmoil** [paulevsGitch/BetterEnd#314]
With the shrinking of the end island the spawn platform is quite far away from the island and the dragon is immediately aggroed on the player. This leads to situations where the player spawns in and is almost immediately sent to the void by a dragon fireball. This does not seem like a fun or better experience.

**Comment by paulevsGitch** [comment]
Hi, the End spawn platform has fixed coordinates (by Mojang design) and this is normal when it is far from End island. If you want to make island bigger you can change layer for the central island (from mediumIslands to bigIslands in generator.json), you can also set a custom spawn point in the same config
