### ISSUE TITLE
Lag Spikes [1.17.1]

### ISSUE THREAD

**Issue by UnusedCactus** [paulevsGitch/BetterEnd#317]
After downloading this mod, I experienced huge lag spikes during gameplay. It happens more or less often based on the amount of mods downloaded, and the amount of world discovered. No cause is seen in the logs. It only occurs in the 0.11.0-pre version.

**Comment by paulevsGitch** [comment]
Code of MC itself in 1.17 is different from 1.16, most code of BE is same except some adaptations, so this is mostly issue of MC itself.

What you can try to do:
- Limit entities spawn to lower values (there are mods that allows this)
- Install optimisation mods (like sodium, phosphor, lithium, hydrogen, ferrite or others)
- Increase you memory limits (as you lags related to amount of mods or worlds this means that you probably just don't have enough memory for all calculations)
- Try different JVM tags

We are trying to optimise BetterEnd as much as we can - parallel calculations and loading, smarter variable usages, code refactoring, but we can work only in MC limits, they are not too wide and we already did most things. So, try to follow steps above, probably they will help you.
