### ISSUE TITLE
Conflict with CTM Fabric

### ISSUE THREAD

**Issue by TestSerber** [paulevsGitch/BetterEnd#319]
Textures don't seem to be available causing them to appear missing in-game
This issue appears to be caused by BCLIB Features? 

I assume the fault lies with BetterEnd since the textures don't seem to follow normal standards texture wise

https://github.com/PepperCode1/ConnectedTexturesMod-Fabric/issues/37
Linked issue

**Comment by paulevsGitch** [comment]
It was fixed many versions ago, update your mod & BCLib version
