### ISSUE TITLE
Adding recipes to the End Stone Smelter?

### ISSUE THREAD

**Issue by Afrocntrik** [paulevsGitch/BetterEnd#32]
Would an example .json be possible, just trying to emulate the additional ingots from ore.

**Comment by paulevsGitch** [comment]
**Simple example:**
```
{
	"type": "betterend:alloying",
	"group": "recipe_group",
	"ingredients": ["input_item_id_1", "input_item_id_2"],
	"result": "item_id",
	"experience": 0.0,
	"smelttime": 350
}
```
**Short variant (without unnecessary tags):**
```
{
	"type": "betterend:alloying",
	"ingredients": ["input_item_id_1", "input_item_id_2"],
	"result": "item_id"
}
```
This recipe serialization can be changed in the future (we will add an output count)

**Comment by paulevsGitch** [comment]
Now updated recipe format for the smelter is on [wiki](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#end-stone-smelter), new recipe format will work in the next version
