### ISSUE TITLE
[1.17.1] No recipes are loading on REI lookup.

### ISSUE THREAD

**Issue by ImAK9** [paulevsGitch/BetterEnd#338]
Upon lookup of any recipes from Better End they dont show at all. Thought this would be fixed with the new update but sadly dosent look like it.

**Fabric API:** 0.41.3
**Better End:** 0.12.1-pre
**BCLib:** 0.4.3

**Comment by quiqueck** [comment]
Hi, and thanks for reporting. 

I have some followup questions:
- Did you have this Problem in previous versions of BetternEnd as well?
- Where do you look up the recipes? in REI or the Vanilla Book?
- Do you have other Mods installed?

**Comment by ImAK9** [comment]
1. It’s present in 0.11 aswell, I’d have too check the others.
2. Like I stated it’s on REI lookup (Either clicking the item or using R button on them)
3. Yes, this is AOF4 and I have not tested BE by itself. I doubt it’d fix it but worth a try. I will try this when home on PC.

**Comment by quiqueck** [comment]
Sorry :D 
It seems that obvious information from the title wasn't obvious enough for me :D

Since there are additional Mods involved, could you please send us your log-files?

**Comment by ImAK9** [comment]
https://paste.alloffabric.com/usakemawit.sql

**Comment by paulevsGitch** [comment]
I think potential reason can be KubeJS  mod, issues with it was fixed some time ago, but probably after updates our fixes are not working, this will require additional tests

**Comment by Dejeh** [comment]
This happens to me when I /reload with REI and kubejs installed, only for better end recipes.

**Comment by ImAK9** [comment]
Issue seems to be fixed in newer builds.
