### ISSUE TITLE
Crystallite Armor

### ISSUE THREAD

**Issue by zKuruta** [paulevsGitch/BetterEnd#344]
Hi, I made a full crystallite armor and it's almost completly broke, but I don't know how to repair it, I tried with crystals and terminite ingots but nothing, can someone tell me how to repair it? Thanks.

**Comment by paulevsGitch** [comment]
This will require some tests, probably something break after 1.17 port

**Comment by paulevsGitch** [comment]
Tested, works fine (or at least will work after release)

![2021-11-30_13 22 40](https://user-images.githubusercontent.com/17707380/144029719-34bd0d3c-7b80-496e-8afe-bd2d8fc11902.png)
