### ISSUE TITLE
Each time i kill the Drake, a new Portals gets formed...

### ISSUE THREAD

**Issue by Anti27** [paulevsGitch/BetterEnd#347]
https://i.imgur.com/Riu2DEl.png
1.17.1, fabric, just another modpack 2.9.2b, better-end-0.11.0-pre.jar

**Comment by paulevsGitch** [comment]
Duplicate of old issues, looks like sometimes file cannot be readed properly or there is an issue in code that are not triggered on each time

**Comment by paulevsGitch** [comment]
Fixed in 0.12.5
