### ISSUE TITLE
Better End crashing in Shadow Forest

### ISSUE THREAD

**Issue by PrudiiGaming** [paulevsGitch/BetterEnd#348]
I've been playing the 1.16.5 Forge version of Better Minecraft, and there is this one specific area that crashes me every time I pass into render distance of it. I can't tell you what is crashing me, because I can't get to the location to find out. I can, however, provide a crashlog. Please message me at prudiigamingofficial@gmail.com for any additional information required.
[2021-11-16-12.log.gz](https://github.com/paulevsGitch/BetterEnd/files/7548018/2021-11-16-12.log.gz)

**Comment by Necrontyrr** [comment]
BetterEnd is a Fabric mod, not a Forge mod. Please report it to the developers of the port.
