### ISSUE TITLE
[Suggestion / Compatibility] Common tags folder Name/ID could be more explicit

### ISSUE THREAD

**Issue by Azagwen** [paulevsGitch/BetterEnd#35]
https://github.com/paulevsGitch/BetterEnd/blob/ca31048ca84480f2199408054563b4ae0e620a86/src/main/java/ru/betterend/registry/EndTags.java#L54

I had to add the commons tags folder to my mod to fix a compatibility issue, but I felt like the folder's name could have been more clear.

Because if anyone finds a folder named **"c"** in my mod they'll have no idea it's to make it compatible with **BetterEnds**

**Comment by paulevsGitch** [comment]
This is an [official Fabric common tag namespace](https://fabricmc.net/wiki/tutorial:tags) used by many mods, it will likely not be changed

**Comment by Azagwen** [comment]
> This is an [official Fabric common tag namespace](https://fabricmc.net/wiki/tutorial:tags) used by many mods, it will likely not be changed

OH, I wasn't aware of that... Thanks for telling me !
