### ISSUE TITLE
There is never a dragon

### ISSUE THREAD

**Issue by zayoood** [paulevsGitch/BetterEnd#351]
Hello

The mod has been successfully installed and works fine, but the dragon never appears, what should I do?

**Comment by paulevsGitch** [comment]
Can you please explain this in more details and provide more information?

**Comment by zayoood** [comment]
The mod has been installed and works perfectly, but there are no dragons at all when entering the end, and I cannot exit from the end either

**Comment by paulevsGitch** [comment]
Under information I mean:
- Game version
- Mod version
- Logs (server/client)
- Is this first time you enter the End or dragon ressurection

**Comment by zayoood** [comment]
its good now after delete old world
