### ISSUE TITLE
World crashes in both singleplayer and on server.

### ISSUE THREAD

**Issue by TheGatesScratch** [paulevsGitch/BetterEnd#357]
Hi!

(This might not be an issue related to BetterEnd, but its worth a shot)
So we are running a server with these mods, with fabric loader version 0.12.5:
![image](https://user-images.githubusercontent.com/69715898/142900779-efffd562-d1ef-4adf-bed5-16b79df311e2.png)
The server worked fine, until recently, it just started running behind on ticks, and then just closed because it ran behind too much.
Currently, when we try to join the world, the server starts lagging after a couple of seconds, and then the client crashes as well, while the server actually stays online when there are no players online.
So I downloaded the map, and on singleplayer, it crashes too after a few seconds.
Below the log of me joining the world, taking some screenshots of f3, leaving, and then joining again until it crashes:
[latest.log](https://github.com/paulevsGitch/BetterEnd/files/7582890/latest.log)

![2021-11-22_17 48 01](https://user-images.githubusercontent.com/69715898/142901979-76e51530-f57d-4007-a351-7af5710e3e01.png)
![2021-11-22_17 47 51](https://user-images.githubusercontent.com/69715898/142901991-c784c8d7-2061-4497-8907-9bd4f3335a4d.png)
![2021-11-22_17 47 57](https://user-images.githubusercontent.com/69715898/142901994-08f80a9b-217e-4c49-a28c-507a0781b326.png)

**Comment by paulevsGitch** [comment]
BetterEnd don't have effect on Overword, looks like your other mods cause this thing. There are also no errors in the console related to BE, all that I can found are:
> Couldn't parse data file endking:team from endking:powers/team.json
> JsonParseException

Which means that one of your json files are wrong, but it is not from BE, looks like it is from origins or its addon

**Comment by TheGatesScratch** [comment]
> Which means that one of your json files are wrong, but it is not from BE, looks like it is from origins or its addon

This is indeed Origins, but does not cause the crash.
I thought it could be a gliched better end block somewhere causing this?

**Comment by TheGatesScratch** [comment]
Seems to be a WorldEdit problem, reset the map :|
