### ISSUE TITLE
Too many Dragonflies

### ISSUE THREAD

**Issue by Lavaheart626** [paulevsGitch/BetterEnd#358]
![Screenshot_71](https://user-images.githubusercontent.com/53801324/143326887-38e4fe33-f7fc-459e-b047-8e4f00011507.png)

Minecraft: 1.17.1 
Version: 0.12.2 fabric

I'm on a server and there are a lot of places where the dragonflies spawn very thickly. We are using the origin mod so the end gets a lot more use than most servers from people who spawn there naturally and build their homes there.

**Comment by paulevsGitch** [comment]
Fixed in 0.12.5
