### ISSUE TITLE
Add recipe format to the wiki

### ISSUE THREAD

**Issue by Tetrajak** [paulevsGitch/BetterEnd#36]
Could you please add examples and explanations for adding recipes via data pack to the various machines/mechanisms in this mod to the wiki of this repo?

**Comment by paulevsGitch** [comment]
We have plans to add recipe examples to wiki

**Comment by Tetrajak** [comment]
That's great to hear! In the mean time, if possible, could you give me an example of an Infusion Altar recipe in data pack json format, if that's possible?

**Comment by paulevsGitch** [comment]
Yes, it will look like this:
```
{
	"group": "infusion",
	"input": "input_item_id",
	"output": "output_item_id",
	"catalysts": [
		"catalyst_id_1",
		"catalyst_id_2",
		"catalyst_id_3",
		"catalyst_id_4",
		"catalyst_id_5",
		"catalyst_id_6",
		"catalyst_id_7",
		"catalyst_id_8"
	]
}
```

**Comment by Tetrajak** [comment]
Thank you!

**Comment by paulevsGitch** [comment]
Yes, you need to use empty strings. We will probably change this format to be more clear. There is also small bug in recipe serializer, so probably recipes will not work correctly, we will fix this

**Comment by paulevsGitch** [comment]
Now updated recipe format is on wiki (updated format will appear in the next release)
[wiki page](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#infusion-ritual)
