### ISSUE TITLE
Loot tables for plants and similar stuff is set to require vanilla shears instead of tag forge:shears, so only vanilla shears work

### ISSUE THREAD

**Issue by Neamow** [paulevsGitch/BetterEnd#360]
betterendforge-1.16.5-1.6.3.jar
Forge-36.2.0

Hello,

something I just noticed while playing is that no shears besides vanilla shears work when trying to break plant blocks like flowers, tail moss, etc.

Noticed in the loot tables the requirement is set to "item": "minecraft:shears". This should be "tag": "forge:shears", otherwise modded shears just don't work (e.g. Botania or Cyclic shears), and the blocks just break without giving the item.

It's easy to override it through a datapack, but this should really be corrected.

Thanks!

**Comment by Fireface677** [comment]
This is a fabric mod. No one here is responsible for the forge port you are referring to.

**Comment by Neamow** [comment]
Ah went to the wrong page on CurseForge.

**Comment by Fireface677** [comment]
Also the fabric port you are using is discontinued. You can try this one: https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked

**Comment by Fireface677** [comment]
Paulevs and the rest of us are still not responsible for it so please use their github and curseforge for futher questions and bug reports

**Comment by paulevsGitch** [comment]
BetterEnd don't have loot tables JSONs at all, it uses code defined tools & Fabric API
