### ISSUE TITLE
Rubinea Texture 

### ISSUE THREAD

**Issue by Pqvel1l** [paulevsGitch/BetterEnd#365]
![image](https://user-images.githubusercontent.com/90570840/145388667-53804e0a-4880-47d5-b9d1-249d33bf996c.png)

**Comment by paulevsGitch** [comment]
Are you playing with graphical mods?

**Comment by paulevsGitch** [comment]
We also require your game & mod version

**Comment by Pqvel1l** [comment]
> We also require your game & mod version

Mod Version:betterendforge-1.16.5-1.6.2
Minecraft Version: 1.16.5 Forge
Without graphical mods/shaders/resourcepacks

**Comment by paulevsGitch** [comment]
betterend**forge**
We are not supporting unofficial ports
