### ISSUE TITLE
0.12.5 no Aeternium gear recipes

### ISSUE THREAD

**Issue by Minionade** [paulevsGitch/BetterEnd#366]
in version 0.12.5, recipes for the following items do not exist:
betterend:aeternium_helmet
betterend:aeternium_chestplate
betterend:aeternium_leggings
betterend:aeternium_boots
betterend:aeternium_shovel
betterend:aeternium_sword
betterend:aeternium_pickaxe
betterend:aeternium_axe
betterend:aeternium_hoe
betterend:aeternium_hammer
betterend:elytra_armored

**Comment by paulevsGitch** [comment]
Update your BCLib
