### ISSUE TITLE
All new generated structures chest are empty

### ISSUE THREAD

**Issue by sl-christopherimbert** [paulevsGitch/BetterEnd#368]
I visited a lot of your new structures and all barrel / chest / furnace are empty. Which clearly limit interest of finding them. 

I'm on better-end-0.12.5.jar

**Comment by paulevsGitch** [comment]
Biome structures don't have loot yet. Loot is is in plans for the next updates

**Comment by sl-christopherimbert** [comment]
Thanks @paulevsGitch. May the force be with you.
