### ISSUE TITLE
Resummoning Dragon Spawns New Portal 

### ISSUE THREAD

**Issue by TalrothNai** [paulevsGitch/BetterEnd#369]
Resummoning the ender dragon is spawning a new portal on top of the old one(s) at random. Sometimes it does, sometimes it doesnt, but more often it does. And when it does, if you happen to be standing in the wrong place (anywhere on the frame) it traps you in bedrock. My players are getting very angry at losing their items due to this. Can this be toggled in the config file somewhere? We're using the Better Minecraft [FABRIC] v19 which has graves, the graves are put beneath bedrock so players cant get their items back.

**Comment by paulevsGitch** [comment]
Can you please provide a mod version?

**Comment by TalrothNai** [comment]
0.12.2 is what the jar file name says

**Comment by paulevsGitch** [comment]
It is outdated, please use the latest one

**Comment by TalrothNai** [comment]
Will updating do anything to the server or what has already been discovered/done and what not?

**Comment by paulevsGitch** [comment]
It will only fix bugs
