### ISSUE TITLE
Better end dragon respawn

### ISSUE THREAD

**Issue by Lord-Bowden-CGP** [paulevsGitch/BetterEnd#370]
The basic problem is that the dragon doesn't respawn. Reddit people claim you just do it as normal. That doesn't work. How do I respawn the dragon? I would appreciate this fixed soon as I help run a smp with better end on and evolving origins that can only be evolved via killing the dragon

**Comment by paulevsGitch** [comment]
Can you please provide more information? Mod and MC version, how are you trying to respawn it, are you on client or server?

**Comment by Lord-Bowden-CGP** [comment]
It's in a 1.17.1 fabric public server. Server side. Mod version is 0.12.5

**Comment by Lord-Bowden-CGP** [comment]
Oops didn't mean to close it

**Comment by Lord-Bowden-CGP** [comment]
It's in a 1.17.1 fabric public server. Server side. Mod version is 0.12.5

**Comment by paulevsGitch** [comment]
In this case it should work fine if it is done properly, can you please show your crystal placement?

**Comment by Lord-Bowden-CGP** [comment]
I placed the crystals in every way I could think of. I've made my own solutions of remaking the vanilla portal and placing it in the vanilla way. I just assumed there would be a way to do it without gmc. Thanks anyway

**Comment by Danekjovax** [comment]
How are the crystals placed??  Wiki is not helpful.

**Comment by Lord-Bowden-CGP** [comment]
All I did was set up a command block that removed the better end portal and cloned a self build vanilla portal to 0,0 and placed the crystals like normal, as if the mod wasn't on

**Comment by Danekjovax** [comment]
> All I did was set up a command block that removed the better end portal and cloned a self build vanilla portal to 0,0 and placed the crystals like normal, as if the mod wasn't on

Is this how it's supposed to be done?  I thought the crystals were supposed to be placed on the modded end portal somewhere.  Could a mod 'dev chime in here?

**Comment by paulevsGitch** [comment]
![image](https://user-images.githubusercontent.com/17707380/147979027-ba4c086a-be96-47c6-a523-9997a975512c.png)

**Comment by Lord-Bowden-CGP** [comment]
Yeah, that doesn't work for what ever reason. Might just be a fabric issues, but it's a known issue

**Comment by Danekjovax** [comment]
> This is correct placement. It is same as in vanilla
> 
> ![image](https://user-images.githubusercontent.com/17707380/147979027-ba4c086a-be96-47c6-a523-9997a975512c.png)

Ok, I have done that pattern in the modpack I am playing in and nothing is happening.  I'll report this to the modpack dev.  Thank you for clarification.

**Comment by paulevsGitch** [comment]
You can disable custom portal in the config if it is not working for some reasons
