### ISSUE TITLE
No Bioms generated?

### ISSUE THREAD

**Issue by hisross** [paulevsGitch/BetterEnd#371]
in my current Wolrd it looks like there is absolute no Bioms. I even checked with Spectator Mode and finding nothing. I checked in an other world of the some Version an there are Bioms. Dont know if its a Bug or anything. Is there a way to re-generate the End or anything? 
![grafik](https://user-images.githubusercontent.com/96746219/147501093-83760347-e2af-4bf8-973b-54f1eb495020.png)

**Comment by paulevsGitch** [comment]
What mod version are you using?

**Comment by paulevsGitch** [comment]
Also looks like this is not vanilla generation, what other mods do you have?

**Comment by paulevsGitch** [comment]
Issue was opened 10 days ago, there is no answers, I'm closing this
