### ISSUE TITLE
Crash when loading 1.17 world

### ISSUE THREAD

**Issue by Sinogard** [paulevsGitch/BetterEnd#373]
I have both better end and Better Nether along side a few other mods. It gets to 0% loading then instant crash error 0

[crash-2021-12-29_21.54.29-server.txt](https://github.com/paulevsGitch/BetterEnd/files/7791558/crash-2021-12-29_21.54.29-server.txt)
I loaded an 1.18 world already generated and soft locked. no blocks appeared, minimap loaded, mobs loaded, but game was not actually running, damaging the enemies could only be done once then they couldnt be hurt again. 

Heres the mods I've got running. works without better end.
![Screenshot 2021-12-29 220709](https://user-images.githubusercontent.com/88293626/147723197-cc294b49-2f0e-431e-86aa-4eaa26cbe6d2.png)

Just realized the screenshot doesnt have better end or the new BClib 1.2.0. Rest assured I updated that when I tried the mod. 
.

Edited For clarity

**Comment by Sinogard** [comment]
![Screenshot 2022-01-01 190420](https://user-images.githubusercontent.com/88293626/147864127-98e9f21d-fe65-4e41-9da4-cf08300d58db.png)
I went ahead to try it on a server by running my old 1.17 server world and got a different error.

**Comment by quiqueck** [comment]
This fabric message usually means, that mod version or the mod settings on client and server are different. Could you please check if that is the case?
