### ISSUE TITLE
[Compatibility] Incompatible with Concurrent Chunk Management Engine

### ISSUE THREAD

**Issue by Treetrain1** [paulevsGitch/BetterEnd#375]
When you travel to the end, everything is fine. The dragon fight is normal, but when travelling through the gateway and a custom biome generates, the game crashes.

I am running more mods, but I tested them by themselves and it has the same result

Heres the crash report in case you need it

[crash-2021-12-30_02.57.32-server.txt](https://github.com/paulevsGitch/BetterEnd/files/7792198/crash-2021-12-30_02.57.32-server.txt)

**Comment by paulevsGitch** [comment]
Hm, looks like chunk generation is wrong
> No chunk exists at

This is actually not a BE issue, BE don't change chunk management and uses only vanilla-available chinks for generation

**Comment by Alkiasan** [comment]
https://github.com/RelativityMC/C2ME-fabric/issues/101

Discussed here with c2me dev, he's saying that it needs to be fixed on BE's side?

**Comment by quiqueck** [comment]
It is the same as in BN. Our current implementation is not prepared to be executed in parallel. Currently I do not know the extend of changes we'd have to make to BE and the runtime impact it might have on players not using c2me, but I'll have a look.

**Comment by paulevsGitch** [comment]
This was actually fixed in one of updates, so I'm closing this
