### ISSUE TITLE
Jitpack doesn't build

### ISSUE THREAD

**Issue by Micalobia** [paulevsGitch/BetterEnd#376]
Jitpack doesn't build correctly for any version, despite there being a jitpack.yml to suggest that you're supposed to be able to use it.
https://jitpack.io/#paulevsGitch/BetterEnd/

**Comment by paulevsGitch** [comment]
I think replacing Java 16 to 17 in Jitpack config will probably fix this

**Comment by quiqueck** [comment]
The last commit seems to have fixed the problem, I can at least build HEAD on jitpack. So it should start working for the next release. If it does not, please reopen the issue.
