### ISSUE TITLE
Better End music doesn't play when Music Control is installed

### ISSUE THREAD

**Issue by Treetrain1** [paulevsGitch/BetterEnd#379]
When Music Control and Better End are installed and an end biome has custom music, music control plays music and is cut off. The end biome music never plays

I'm not sure if this is a bug with Music Control or Better End, since the logs mention nothing about the issue

Here's a video of the issue
https://user-images.githubusercontent.com/39657565/147793141-a57f6226-5042-46dc-91d8-889a7753fbc9.mp4

Music control scrolls through music without playing it

**Comment by paulevsGitch** [comment]
Looks like this is Music Control [issue](https://github.com/sf-inc/music_control/issues/1)
