### ISSUE TITLE
'Bubble Coral' is already a vanilla block

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#38]
Better End adds a block called Bubble Coral, but vanilla Minecraft has had its own block by the same name since 1.13, the Update Aquatic. Giving one's modded blocks or items the same name as vanilla ones can be seen as a bit tacky, and can also make it difficult for one to tell which bubble coral their server mate is referring to, for example. I would love to see this issue fixed by simply giving your block a non-conflicting name.~

**Comment by paulevsGitch** [comment]
I think it is not very important that this block has the same name as one of vanilla blocks. It named like this as it emits bubbles
