### ISSUE TITLE
[1.18.1] End Highlands start spawning too close to main iland

### ISSUE THREAD

**Issue by Joulanh** [paulevsGitch/BetterEnd#381]
bclib 1.2.1
better end 1.0.0
fabric api 0.45.0

End Islands start to spawn at roughly radius 200 instead of usually 1000, with better end ores and structures but without better end biomes.

![2022-01-01_15 25 45](https://user-images.githubusercontent.com/80494384/147853279-75d9e24d-8252-4810-9c12-d61d2b816206.png)

![2022-01-01_15 25 58](https://user-images.githubusercontent.com/80494384/147853283-e1aa07ce-3ce6-4fd9-88bd-f7eb111dccc0.png)

![2022-01-01_15 28 02](https://user-images.githubusercontent.com/80494384/147853287-e654f019-a997-4c4f-904b-7b41d8190e51.png)

**Comment by Sirkilium** [comment]
This is intended AFAIK

**Comment by paulevsGitch** [comment]
> This is intended AFAIK

No, this is a bug

**Comment by Sirkilium** [comment]
World it be possible to make it a config option once it's fixed? I think the close end islands are quite cool

**Comment by paulevsGitch** [comment]
It already is a config option

**Comment by quiqueck** [comment]
This should be fixed in 1.0.1. If you still see this problem, please reopen the issue.
