### ISSUE TITLE
[1.18.1] Anvil Recipies not working

### ISSUE THREAD

**Issue by MarkNoName** [paulevsGitch/BetterEnd#384]
I don't know if the Recipies changed or not but when trying to craft plates for armor or head's for tools it doesn't show off the item outputs. I tried it with nearly every combination with all of the BE ore's and nither of them worked.

Setup:
fresh install of Fabric Loader 1.18.1 v0.12.12
Java 17.0.1.0
bclib-1.2.1.jar
better-end-1.0.0.jar
fabric-api-0.45.0+1.18.jar

Here is a Video of what i mean:  https://user-images.githubusercontent.com/35975662/147871617-61ab2bc2-3215-420b-9b1f-523b3838757f.mp4

**Comment by DasKnocker** [comment]
Will echo this as well - Tried both regular anvil and thallium, netherite and thallium hammer, shard and ender pearl to create dust and no output created. This is on 1.0 with both dependencies installed, but as part of a larger modpack 1.18.1 Medieval Minecraft Fabric .12.12.

**Comment by Hideout28** [comment]
Also gonna echo this, I tried all combinations of hammers and anvils, none of them working, but I did notice that if you are using Roughly Enough Items and click on any random recipe and quickly exit the crafting helper (you may have to do this several times in succession) the buttons to cycle between the item you want to make will appear, although they do nothing and you still can't craft any of the tool heads or ender dust. Did this on 1.18.1 with just Better End, REI, VoiceChat, and Optifine/Optifabric (as well as their dependencies of course)

**Comment by DJMan255** [comment]
Same here, running on the Better Minecraft [Fabric] v8.5, as everyone else has started above, I've tried every combo of anvil and hammer to no avail.

**Comment by PedroBavdaz** [comment]
Same here, the recipes don't work with everything up to date, hope they fix this quick
