### ISSUE TITLE
End portal not working

### ISSUE THREAD

**Issue by Cetins** [paulevsGitch/BetterEnd#385]
Hi, I'm using 1.18.1 better minecraft modpack (fabric) and I find out that my end biomes are not updated with BetterEnd modpack. Then I found the suggestion here and change the end generation preferences to "betterend:better_end_biome_source" as in the way the instructions suggests. Now my end portal exists but When I jump in it does nothing. Then I tried to find another stronghold so I could activate a new portal, but still the same results. I've placed all the ender eyes and portal activated but when I jumped in nothing happens I literally stand there inside the portal effect. Luckily I've covered the lava under the portal so I didn't fall in there. Do you have any suggestions for how to fix this?

I've tried this in the better minecraft modpack version 7.5 , 8 and 8.5. all the same results end portal not working. All fabric.

**Comment by paulevsGitch** [comment]
You are using outdated instructions made for 1.16.5. You write wrong biome source and corrupted your save. Restore your dimension entries and use **bclib:end_biome_source** for the End and **bclib:nether_biome_source** for the Nether
