### ISSUE TITLE
Broken Biome Source Tutorial is outdated (I believe)

### ISSUE THREAD

**Issue by RotatingBuffalo** [paulevsGitch/BetterEnd#386]
I followed the tutorial to fix the biome source being wrong, after updating a modpack that added BetterEnd in said update.
Apparently "betterend:better_end_biome_source", did not exist, and upon making a new world and inspecting its level.dat, It's instead "bclib:end_biome_source".

I would have assumed this is due to general modpack crustiness, until I saw on the CurseForge page that BCLib is a required dependency of BetterEnd, meaning that the prefix has probably actually just changed and you guys haven't updated the tutorial yet.

Please update it, as it would save probably more people than just me a lot of headache lmao.
![level_structure](https://user-images.githubusercontent.com/13899634/148164659-2122bb3e-9c93-4bda-8b67-86c479d6559a.png)
![level_structure](https://user-images.githubusercontent.com/13899634/148164687-8fad8b02-2d4c-41ef-897e-5808030a4bdb.png)

**Comment by paulevsGitch** [comment]
This tutorial was made for 1.16 version, in modern versions BCLib fixes biome source automatically. Probably tutorial require some updates
