### ISSUE TITLE
whenever I try to load any world-- even creating a new one-- my game crashes instantly

### ISSUE THREAD

**Issue by idkman2021** [paulevsGitch/BetterEnd#387]
https://gist.github.com/idkman2021/2ba83b14e486bd5d1538ad3872537ae8

 Hey I'm running into an issue where whenever I try to load any world-- even creating a new one-- my game crashes instantly. I know it's this mod because I can load the other 4 without issue, including BCLib. I'm not sure what other information is needed, but I'm happy to share.

 

Thank you!

**Comment by paulevsGitch** [comment]
You have outdated BCLib, please use the latest one
