### ISSUE TITLE
Aeternium, Terminite, and Thallasium recipe bugs on Multiplayer!

### ISSUE THREAD

**Issue by Theobot3782** [paulevsGitch/BetterEnd#388]
The recipes will not eat the hammer anymore, but you can't switch between different items to forge! SPECIFICALLY ON MULTIPLAYER!
The recipes work perfectly fine on singleplayer, but on multiplayer, REI doesn't even detect ANY recipes either! PLZ FIX DIS BUGGGGGGGGGGGGGGGGGG

**Comment by paulevsGitch** [comment]
Please provide correct information - mod & minecraft versions, other mods, server and client logs

**Comment by Theobot3782** [comment]
This bug got worse in the betterend 1.18.1 port, THE ANVIL RECIPES DON'T WORK AT ALL!!! AND THE THALLASIUM INGOT SMELTING RECIPE IS MISSING!!! :(((
