### ISSUE TITLE
Please Register Tags the correct way or allow us to have an option to disable certain tags. 

### ISSUE THREAD

**Issue by KaneHart** [paulevsGitch/BetterEnd#390]
For example: 
![image](https://user-images.githubusercontent.com/425853/148339755-5e1a3e6a-c9d6-4c80-b751-be0886667802.png)

It seems this is registered in JS and using kubejs for example sadly can't remove the tag's from said Item. With larger Tech Packs the last thing I want is to have it mix like that.

If possible add even a config for us to remove it.

Thanks :)

**Comment by paulevsGitch** [comment]
Fabric allows to overwrite any item/block tag list, additional configs are not necessary
