### ISSUE TITLE
Elytra Variants Glide Slow

### ISSUE THREAD

**Issue by Hideout28** [paulevsGitch/BetterEnd#392]
When using either the Armored Elytra or the Elytra Crystalline they both glide significantly slower than the normal elytra, rockets still work fine and you go full speed until the fuse ends, then it decelerates significantly, not sure if this is a bug or just a way of balancing being able to use an elytra and still have armor value from it.

**Comment by paulevsGitch** [comment]
This is a feature, both elytras work like armor and their speed is decreased
