### ISSUE TITLE
Anvil recipes not working and thallasium smelting is missing!

### ISSUE THREAD

**Issue by Theobot3782** [paulevsGitch/BetterEnd#393]
On multiplayer OR singleplayer, the thallasium smelting recipes don't exist, and the anvil recipes are not working... This is for the 1.18 port, but before the 1.18 port, the anvil recipes were not working properly in multiplayer only, but now in the 1.18 port, they don't work at all... NOT EVEN IN SINGLEPLAYER.

**Comment by paulevsGitch** [comment]
Duplicate of other issues
