### ISSUE TITLE
[1.16.5] If you use the mode without BYG, only 4 Biomes will appear

### ISSUE THREAD

**Issue by mingh2e** [paulevsGitch/BetterEnd#396]
If i don't use BYG and just use BATTER END mode, there's very little biomes.
You can use byg mode, but I don't like the addition of Overworld's bioome.
![2022-01-09_12 05 56_2](https://user-images.githubusercontent.com/96931727/148667883-21299e95-03cb-4eb3-9a7e-30c10d3b61df.png)
,
It's a chunk with byg and a chunk without.
As a result of checking without using the byg mode, only 4 biomes came out.
I tried a solution using NBT Explorer, but it was useless.
If I use it without BYG mode, does it produce less biome?

**Comment by paulevsGitch** [comment]
Fix your biome source like was mentioned [on wiki](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source)

**Comment by mingh2e** [comment]
![캡처](https://user-images.githubusercontent.com/96931727/148670495-c56b80c7-24df-4086-89f8-701e6cd68195.PNG)
I've already done it

**Comment by paulevsGitch** [comment]
In this case generation will work fine. What BetterEnd version are you using?

**Comment by mingh2e** [comment]
I'm using the most recent file 1.16.5 fabric
better-end-0.9.8.5-pre-1.16.5

**Comment by paulevsGitch** [comment]
In this case if you edit dimension entry correctly and without typos - it will work fine. Do you have other mods and datapacks except BYG?

**Comment by mingh2e** [comment]
I'm only using better end packs for data packs.
I'm using a few performance-enhancing modes, and I'm not using additional biome modes.
