### ISSUE TITLE
Modded ores (other than betterend) do not generate in BetterEnd biomes

### ISSUE THREAD

**Issue by FirstMegaGame4** [paulevsGitch/BetterEnd#398]
Modded ores (other than betterend) do not generate in BetterEnd biomes.

I destroyed islands in the end with commands to verify.

BCLib 1.2.2
BetterEnd 1.0.0

**Comment by paulevsGitch** [comment]
BetterEnd doesn't change how other mods adding their ores, if another mod don't handling other mods biomes - it is issue on its side

**Comment by FirstMegaGame4** [comment]
Isn't it possible to accept ores that spawn in Basic Biomes in BetterEnd Biomes?

**Comment by paulevsGitch** [comment]
There are no any ores in Vanilla End biomes. If another mod adds ore - it should add it into other modded biomes too using Fabric API

**Comment by MJRamon** [comment]
I new to Fabric modding. How do I reference a BetterEnd biome in biome list, when I register an ore generation?

**Comment by paulevsGitch** [comment]
> I new to Fabric modding. How do I reference a BetterEnd biome in biome list, when I register an ore generation?

This is done with Biome Modification API, like this:

```
BiomeModifications.addFeature(
	// Check that biome is in End (Simple variant)
	context -> context.getBiome().getBiomeCategory().equals(BiomeCategory.THEEND),
	Decoration.UNDERGROUND_DECORATION,
	ore // Your Ore ResourceKey
);
```

If you don't want to use categories and want your ore to appear in specific biomes:

```
BiomeModifications.addFeature(
	// someBiomeKey is a biome ResourceKey
	context -> context.getBiomeKey().equals(someBiomeKey),
	Decoration.UNDERGROUND_DECORATION,
	ore // Your Ore ResourceKey
);
```
