### ISSUE TITLE
Game crashed unexpectively with an hs_err_pids log file

### ISSUE THREAD

**Issue by linzexin022** [paulevsGitch/BetterEnd#40]
Hi there, game crashed while I was at high speed flight, with the Mincraft log saying:
`**[23:22:20] [Server thread/WARN]: Tried to load a DUMMY block entity @ class_2338{x=-328, y=57, z=-2087} but found not block entity block Block{betterend:violecite} at location
[23:22:20] [Server thread/WARN]: Tried to load a block entity for block Block{betterend:violecite} but failed at location class_2338{x=-328, y=57, z=-2087}**
[23:23:05] [main/INFO]: OpenGL debug message, id=0, source=API, type=ERROR, severity=HIGH, message=Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=6196 javaw.exe 64bit)
[23:23:05] [main/INFO]: OpenGL debug message, id=1285, source=API, type=ERROR, severity=HIGH, message=GL_OUT_OF_MEMORY error generated. Failed to allocate memory for buffer data.

A fatal error has been detected by the Java Runtime Environment:

 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000020d6045f16d, pid=6196, tid=0x0000000000001e24

 JRE version: OpenJDK Runtime Environment (8.0_265-b01) (build 1.8.0_265-b01)
 Java VM: OpenJDK 64-Bit Server VM (25.265-b01 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  0x0000020d6045f16d

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 D:\MultiMC\instances\1.16.4\.minecraft\hs_err_pid6196.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

AL lib: (EE) alc_cleanup: 1 device not closed`

Don't know if you can figure it out what caused the problem. It was also printed an hs_err_pids log file which I think there might be some problems with JVM?

Here's the hs_err_pids log file:
[hs_err_pid6196.log](https://github.com/paulevsGitch/BetterEnd/files/5744723/hs_err_pid6196.log)

--------------------------------------------------------------

Minecraft version: 1.16.4
Fabric Loader version:  0.10.8
Fabric API version: 0.28.4
Better End version: 0.8.3-beta
Canvas Renderer: 1.0.1257

Versions of other mods installed (unnecessary?):
Better Nether: 5.0.4
Can I Mine this Block?: 1.0.2
Disable Custom Worlds Advice: 1.2
Hwyla: 1.9.22
Lithium: 0.6.0
Patchouli: 48
Phosphor: 0.7.0
Roughly Enough Items: 5.8.10

**Comment by paulevsGitch** [comment]
Looks like you run out of your RAM limit, you can try to increase memory limit for Java
