### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Thrumptus** [paulevsGitch/BetterEnd#400]
Running fabric 1.17.1 and betterend 0.12.5
A few textures, endstone and endmoss for example, simply show up as the missing texture block

**Comment by paulevsGitch** [comment]
Do you have mods like Dashloader or other graphical mods that can be incompatible with Fabric Rendering API?

**Comment by Thrumptus** [comment]
It's sodium and iris causing me the issue i believe, is there any way around this other than uninstalling them?

**Comment by paulevsGitch** [comment]
On 1.17 Sodium and Iris are not compatible - Iris already include custom build of Sodium and 2 instances of Sodium are conflicting with each other. This is the root of the issue

**Comment by Thrumptus** [comment]
Turns out i just needed to install indium, i use the custom sodium build that comes with iris anyway
