### ISSUE TITLE
Lost server connection in single player

### ISSUE THREAD

**Issue by Yashean** [paulevsGitch/BetterEnd#401]
Im trying to add better end to my modpack but every time im installing it and try to get into a world i get the message that I lost connection to the server and it puts me in the multiplayer menue. 
I tried to look at the crash log but it tells me this: 

[02:59:07] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[02:59:07] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[02:59:07] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 8 column 12

I'm already using the newest version of libcd and I tried to use the one that was before that. The problem persists but only after adding the better end alpha. The pack is working just fine otherwise.

**Comment by paulevsGitch** [comment]
Can you please send full logs?

**Comment by Yashean** [comment]
[2022-01-12-7.log.gz](https://github.com/paulevsGitch/BetterEnd/files/7851208/2022-01-12-7.log.gz)

of course sorry

**Comment by paulevsGitch** [comment]
The reason is:
> Encountered exception while handling in channel with name "fabric:registry/sync"
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097212bytes where max allowed: 2097152

Your server have too large packets. You can install [XLPackets](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric) to solve this
