### ISSUE TITLE
[Bug] [1.18.1] Null recipes server-side

### ISSUE THREAD

**Issue by TheIllusiveC4** [paulevsGitch/BetterEnd#405]
**Versions**:
- Fabric: 0.12.12
- BetterEnd: 1.0.0
- Fabric API: 0.45.2+1.18

**Observed Behavior**:

Calling `RecipeManager#byKey(ResourceLocation)` will return an empty value for BetterEnd recipes on server-side. Client-side calls will return the appropriate recipe instance.

**Expected Behavior**:

Calling `RecipeManager#byKey(ResourceLocation)` should return equivalent non-empty values both server-side and client-side.

**Comments**:

I'm the developer for Polymorph and I started investigating a small issue (https://github.com/TheIllusiveC4/Polymorph/issues/136) involving a recipe conflict, one output of which involves a BetterEnd recipe. I discovered that the source of the issue is due to the observed behavior outlined above, which causes Polymorph to fail the recipe validation server-side and refuse to switch recipes.

I'm not exactly sure what _causes_ this behavior, but this is reproducible with only BetterEnd installed. However, I don't have a full understanding of the code base and perhaps I have missed something crucial. This is as much an invitation for dialogue/clarification as it is a bug report.

There seems to be several other bug reports about recipes, but they don't seem to be quite the same as this one. I apologize if this is considered a duplicate of those.

**Comment by paulevsGitch** [comment]
Hm, this is strange that recipes doesn't exist on server side. So, this is how the recipes are implemented:
- All custom recipes are stored in map (same as vanilla)
- This map is [merged](https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/recipes/BCLRecipeManager.java#L35) with vanilla map when necessary

The old code used injections to Recipe Manager, but some mods like KubeJS injected in same place too, so the modern incetions are done into [MinecraftServer](https://github.com/paulevsGitch/BCLib/blob/e53e14eb0e0e3a85191964b7a95ae16ca5a74031/src/main/java/ru/bclib/mixin/common/MinecraftServerMixin.java). So possible reasons can be:
- Mixin fails (they are old and used RETURN injection point);
- Server code was changed and now recipes can't be added this way;
- Probably something breaks the access to original map or overrides it in startup.

I think there can be more reasons, these are first that I can imagine.

> There seems to be several other bug reports about recipes, but they don't seem to be quite the same as this one. I apologize if this is considered a duplicate of those.

Other recipe bugs are related to missing "!" symbol before existence check, which made recipes fail to register, fix will be published soon

**Comment by TheIllusiveC4** [comment]
Ah, I have a suspicion then. Vanilla has two recipe collections, one is the map that's organized by recipe type and the other is the map that's organized by resource location. Does your logic merge only with the former and not the latter? That would account for why the recipes do seem to work, but not when called directly from `RecipeManager#byKey`.

**Comment by paulevsGitch** [comment]
In this case fix should be simple - additional mixin into manager that will add recipes into another internal recipe storage

**Comment by paulevsGitch** [comment]
I uploaded [new BCLib release](https://github.com/paulevsGitch/BCLib/releases/tag/1.2.3), now recipes are added into both map. I added recipes into named map only if environment is not client side, otherwise REI tells that there are recipe duplicates with same keys (I don't know why - this is a hashmap). I hope that bug is fixed now

**Comment by TheIllusiveC4** [comment]
I just did a quick test and the issue seems to be resolved now, thank you!
