### ISSUE TITLE
End stone smelter crafting

### ISSUE THREAD

**Issue by xmanking** [paulevsGitch/BetterEnd#408]
The end stone smelter is impossible to craft. It requires thallasium ingots to craft but you can't make the ingots without a smelter. 
Version- 1.18.1

**Comment by FirstMegaGame4** [comment]
Recipes are Broken in BE 1.18.1

**Comment by xmanking** [comment]
Ok

**Comment by xmanking** [comment]
Do you know if it will be fixed?

**Comment by FirstMegaGame4** [comment]
Certainly in the next 1.18.1 version, this issue is known.

**Comment by xmanking** [comment]
Ok thank you

**Comment by FirstMegaGame4** [comment]
Are you using the latest version of BClib (1.2.4)? I just saw that its latest version solves crafting problems.

**Comment by xmanking** [comment]
no but I will try

**Comment by xmanking** [comment]
That worked

**Comment by FirstMegaGame4** [comment]
Perfect
