### ISSUE TITLE
Using hoes on leaves drop the leaf blocks, making sappling hard to get

### ISSUE THREAD

**Issue by Sirkilium** [paulevsGitch/BetterEnd#418]
The only way to get sapplings is by breaking the leaves with your hands

**Comment by quiqueck** [comment]
What Version of BE are you using? That should have been fixed with the latest update.

**Comment by Sirkilium** [comment]
I'm on 1.0.1

**Comment by paulevsGitch** [comment]
It affect some leaves like Helix tree which have their own (and wrong) code that incorrectly process hoe tools

**Comment by quiqueck** [comment]
Version 1.0.2 should fix this. If you still have the same problem after upgrading, please re-open this issue.
