### ISSUE TITLE
[1.18/1.18.1] BetterEnd causing major Overworld chunk loading issues. Video linked.

### ISSUE THREAD

**Issue by AryonLegacy** [paulevsGitch/BetterEnd#420]
Mc1.18.1 Fabric+Api+BCLib+BetterEnd 
https://gyazo.com/325133d1fe309ea9b829b651092e4b51
Unable to fly in straight line with Elytra...

Mc1.18.1 Fabric+Api
https://gyazo.com/268ef152623c5fb3a1beb6dbfa94911d
This is how chunks normally load, even with 50+ mods included none of them have the impact BetterEnd by itself has on chunk loading...

**Comment by quiqueck** [comment]
Since it is not stated in the report, you are using the latest version of BetterEnd (v1.0.1)? Oh and is the report about slow chunk loading or does the elytra cause those direction changes?

**Comment by AryonLegacy** [comment]
> Since it is not stated in the report, you are using the latest version of BetterEnd (v1.0.1)? Oh and is the report about slow chunk loading or does the elytra cause those direction changes?

Yes latest everything, I also tried different combinations of older Fabric/newer Better End and vice versa.

Slow chunk loading yes, (Keep in mind this is on a good gaming PC, its WORSE on your average tier servers)
 I was demonstrating how a player needs to constantly turn and zig zag to wait for chunks to load because how slow they pop in. 

I have a more than capable rig and no other mods have caused issues like this before, it actually took me forever to narrow it down to BetterEnd because I never suspected it since why would an End mod cause Overwold lag, right?

**Comment by quiqueck** [comment]
Thank you for clarifying :)

**Comment by quiqueck** [comment]
Version 1.0.2 should fix this. If you still have the same problem after upgrading, please re-open this issue.
