### ISSUE TITLE
[1.18.1] Sulfuric Lake corrupted chunks, crashed entire world until removed from chunks

### ISSUE THREAD

**Issue by cypressfalls** [paulevsGitch/BetterEnd#421]
My boyfriend and I were on our LAN minecraft world (singleplayer world, opened to LAN, cheats enabled for teleportation purposes) exploring the End. Everything was running 100% smoothly and okay, zero bugs to be found, until we went to the Sulfur Springs biome and tried to load in the entire thing. When we were running around exploring, chunks STOPPED loading entirely no matter how many server restarts I did and then we started crashing just staying in the End - thus making me have to kill my character to get back home so we could get out of those chunks.

Attached are screenshots of the broken area(the best I could manage), and the crash report.

Mods list is as follows. All of these are 100% up to date, I double checked, and the ones _in italics_ are ones that I believe have absolutely 0 interference with BetterEnd.
_3D Skin Layers_, _Adorn_, _Appleskin_, Architectury API, BCLib, BetterEnd & _BetterNether_, _Cloth API_, _Comforts_, _Croptopia_, _Diggus Maximus_, Fabric API, Kotlin, _Falling Leaves_, NBT Deadlock be gone & No Null Processors, _Modmenu_, _Optifabric & Optifine_, _Patchouli_, Repurposed Structures, _REI_, _Simple Backpacks_, _Worldedit_, _WTHIT_, and _Xaero's Minimap & World Map_
[crash-2022-01-24_19.40.42-server.txt](https://github.com/paulevsGitch/BetterEnd/files/7929846/crash-2022-01-24_19.40.42-server.txt)
![2022-01-24_19 35 41](https://user-images.githubusercontent.com/98366118/150890732-15b11f48-d693-4dea-8b73-0a7b8ed0bb0c.png)
![2022-01-24_19 35 55](https://user-images.githubusercontent.com/98366118/150890733-317cd85f-df32-40fa-94c0-cd1d15d1603b.png)
![2022-01-24_19 35 58](https://user-images.githubusercontent.com/98366118/150890734-855500d5-3176-47fe-82fa-d4a5aeeb5bcc.png)
![2022-01-24_19 36 06](https://user-images.githubusercontent.com/98366118/150890736-5a40412b-a0f0-453b-889a-87ca3c5f3c36.png)
![2022-01-24_19 36 17](https://user-images.githubusercontent.com/98366118/150890739-431ed41a-e21b-4630-8c15-704c77e57869.png)
![2022-01-24_19 36 20](https://user-images.githubusercontent.com/98366118/150890741-8019f0ba-c7d7-4830-8105-f0c47fa9306d.png)
![2022-01-24_19 36 27](https://user-images.githubusercontent.com/98366118/150890745-80ceae6a-09cf-4bd2-8cfc-370a6e074c78.png)
.

**Comment by paulevsGitch** [comment]
Hm, I'm not sure what can cause this, but I guess it can be same issue as with c2me related to underwater plants scatter

**Comment by LeafWDM** [comment]
I am having the exact same issue
