### ISSUE TITLE
Infusion desyncs and incorrect output

### ISSUE THREAD

**Issue by Sirkilium** [paulevsGitch/BetterEnd#422]
Infusion pedestal catalysts are remaining on the pedestals until the client updates them, and the output is giving only a single item instead of specified amount

**Comment by Sirkilium** [comment]
I've discovered that removing the catalyst before updating it allows you to duplicate the item, on both singleplayer and server

**Comment by paulevsGitch** [comment]
Fixed in 1.1.0
