### ISSUE TITLE
an error occurred while loading up the game using this mod.

### ISSUE THREAD

**Issue by TheKing8900** [paulevsGitch/BetterEnd#428]
Crash screen states:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'!
Exit Code: -1

Crash report:
https://pastebin.com/iRwn1uHa

**Comment by paulevsGitch** [comment]
You are using outdated mod version, please use version with same release date as required libraries
