### ISSUE TITLE
Anvil Recipe not Working (Ender Dust)

### ISSUE THREAD

**Issue by atyshka** [paulevsGitch/BetterEnd#429]
Hi, thanks for this awesome mod but I'm trying to figure out the crafting as a beginner. I wanted to make the guidebook with end dust, but I have a hammer and ender shard on an anvil and I am unable to produce the end dust output. Is this a bug or am I misunderstanding the anvil recipes?

<img width="796" alt="Screen Shot 2022-02-03 at 9 47 56 PM" src="https://user-images.githubusercontent.com/19317207/152464416-14fc2c56-4d21-480b-bb77-8aa81ed356c6.png">

Minceraft 1.18.1
Better End 1.0.1
BCLib 1.2.5

**Comment by atyshka** [comment]
#384 Mentioned this was fixed in BClib 1.2.3 but seems to be present in newer versions?

**Comment by paulevsGitch** [comment]
You are not using Hammer and Anvil of proper level. Please use REI to see required tool and anvil level

![image](https://user-images.githubusercontent.com/17707380/152474847-2690a95d-e590-47f2-8a72-daed0de32b59.png)

**Comment by atyshka** [comment]
I hate to be that person but... this really needs a better getting started guide. Happy to contribute to docs once I funally understand it. I downloaded REI, but it looks like in order to get end dust, I need to get a terminite hammer. But in order to get terminite, I need to smelt with end dust, which is now a circular loop

**Comment by paulevsGitch** [comment]
> I need to get a terminite hammer

You can use Netherite hammer

**Comment by atyshka** [comment]
Actually netherite hammer does not work, but a thalassium hammer does the trick
