### ISSUE TITLE
[Bug] Missing Tags

### ISSUE THREAD

**Issue by quiqueck** [paulevsGitch/BetterEnd#436]
Some Blocks need to be added to the `c:end_stones`-Tag.

The following code example shows a failing test:

https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/world/features/terrain/SurfaceVentFeature.java#L28 

Current effects are:
- "stacked" sulfur springs are missing
- caves are missing

**Comment by paulevsGitch** [comment]
Hammers don't have c:hammers tag
