### ISSUE TITLE
Chunk error in the end

### ISSUE THREAD

**Issue by brasi333** [paulevsGitch/BetterEnd#437]
As shown in the image, some of the end islands have gaps missing. This happens some close to the end portal to the outer islands, but it appears to get worse the farther I go in one direction. 

This world was already made when I added the mod, though I hadn't entered the End yet. I did the Wrong Biome Source fix with NTB Explorer before entering the end. 

![2022-02-12_18 40 11](https://user-images.githubusercontent.com/95038179/153736314-ebea1f34-5f94-409a-ad57-13606e27d5c8.png)

**Comment by paulevsGitch** [comment]
> This world was already made when I added the mod

Some chunks were generated in old version, some in new. This is not a bug

**Comment by brasi333** [comment]
Ok, thanks for the answer. Is the Wrong Biome Source Fix with NBTExplorer supposed to fix this issue, so long as I did the fix before entering the End? Or is there something else that can be done to fix the chunks now?

Thanks

**Comment by paulevsGitch** [comment]
> Is the Wrong Biome Source Fix with NBTExplorer supposed to fix this issue

No, biome source is not related to chunk generation, you need to reset your End by deleting DIM1 folder and removing dragon fights tags from level.dat. If you want you can safe central island and dragon - it has region files with numbers from -1 to 0 (4 regions)
