### ISSUE TITLE
Modded Jobsite blocks don't work with villagers

### ISSUE THREAD

**Issue by xanthian** [paulevsGitch/BetterEnd#438]
This applies to all 3 mods
Nether
End
Eden

The added Barrels, Composters etc do not work with villagers (as in they are not interested in them)
I understand this may be considerable work to add this, but would be a nice to have.

Latest 1.18.1 releases.

**Comment by xanthian** [comment]
If it helps, I found this 
[Beehive POI Mixin](https://github.com/Faboslav/friends-and-foes/blob/aa625e1f430aa11d8ef48bc8e6f7b55c3ceebcba/src/main/java/com/faboslav/friendsandfoes/mixin/PointOfInterestTypeMixin.java)

I've utilized similar in my mod to make modded Grindstones work.

**Comment by quiqueck** [comment]
Will lokk into it. I think we also have a similar problem with Bookshelves not beeing recognized by the enchantment table.
