### ISSUE TITLE
[iris]Wrong irradiance map rendering 

### ISSUE THREAD

**Issue by CongYuSanXun** [paulevsGitch/BetterEnd#439]
![huge_2022-02-18_14 14 45](https://user-images.githubusercontent.com/68322529/154633491-6db03b7b-b9af-4bb8-a46d-6fed9eea2afe.jpg)
![huge_2022-02-18_14 11 05](https://user-images.githubusercontent.com/68322529/154633500-cc7b6ec3-0f80-4052-aeab-31af5c886df2.jpg)
![huge_2022-02-18_14 12 23](https://user-images.githubusercontent.com/68322529/154633506-1b41dc2a-0b96-4499-8baf-c60bf199d375.jpg)
Irradiance map rendering error in betterend and betternether,they do not express alpha.such as end_fish,end_slime,cubozoa,firefly.
but in AdventureZ( https://github.com/Globox1997/AdventureZ )，textures are displayed correctly.

Below is the irradiance map file

![end_slime_lake_glow](https://user-images.githubusercontent.com/68322529/154634358-6c11c1fb-1212-4993-a17b-7708143fb652.png)
end_slime_lake_glow.png

![ender_whale_glow_feature](https://user-images.githubusercontent.com/68322529/154634448-a7c82849-6818-4f8f-80ad-d5dd8312523b.png)
ender_whale_glow_feature.png

shaderpack is Sildur's Shaders( https://sildurs-shaders.github.io/ )

Thank you for your contribution.

**Comment by paulevsGitch** [comment]
Fixed in 1.1.0
