### ISSUE TITLE
[Compatibility] Retextures for Blockus purpur blocks

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#44]
The mod Blockus (https://github.com/Brandcraf06/Blockus) adds additional purpur blocks that, when the mod is used in conjunction with Better End, look out of place with Better End's retextures of the vanilla purpur blocks. While not necessary, letting Better End override these blocks' textures with ones that match your vision for purpur would be a nice compatibility feature.~

**Comment by paulevsGitch** [comment]
Looks like there are only 6 textures, recolor will not be very hard

**Comment by paulevsGitch** [comment]
![2021-01-05_03 17 34](https://user-images.githubusercontent.com/17707380/103592636-9ac50a00-4f04-11eb-8715-2f9403175b1a.png)

**Comment by saltyseadoggo** [comment]
Looking absolutely lovely.~

**Comment by paulevsGitch** [comment]
Thank you

**Comment by paulevsGitch** [comment]
Added in 0.8.6
