### ISSUE TITLE
My game keeps crashing because of this mod?

### ISSUE THREAD

**Issue by Furiouspotato** [paulevsGitch/BetterEnd#440]
[crash-2022-02-20_12.28.55-client.txt](https://github.com/paulevsGitch/BetterEnd/files/8104515/crash-2022-02-20_12.28.55-client.txt)

**Comment by entwinedent** [comment]
can you update , playerex , cloth-config , and dataattributes ? all rely on one another for playerex to work, I just did a test with bclib-1.3.4,   better-end-1.0.2,   cloth-config-6.2.57-fabric,             fabric-api-0.46.4+1.18    ,playerex-3.1.4-1.18.1,   dataattributes-1.1.5-1.18.1 , and everything ran
