### ISSUE TITLE
Custom Infusion recipes

### ISSUE THREAD

**Issue by Tenchu98** [paulevsGitch/BetterEnd#446]
Is there a json structure to use if I wanted to add custom infusion recipes in my pack? I have tried looking everywhere and can't seem to find them, I am wanting to use crafttweaker to add infusion recipes for my fabric modpack

**Comment by paulevsGitch** [comment]
Hi, yes, JSON structure of infusion recipes is described on [wiki tutorial section](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#infusion-ritual)
