### ISSUE TITLE
Caves are extremely rare

### ISSUE THREAD

**Issue by Soldies** [paulevsGitch/BetterEnd#449]
I am running 1.0.2 of BE and are using the latest version of BCLib. For whatever reason caves seem to be extremely rare in biomes other than the Umbra Valley. This lack of caves also results in the lack of hydrothermal vents & underwater areas in the Sulphur Springs biome. They also tend to get cut off at either a chunk border or the border between two biomes [Umbra Valley].

**Comment by paulevsGitch** [comment]
Relative to #436
