### ISSUE TITLE
[Potential Conflict] Wild World

### ISSUE THREAD

**Issue by BrekiTomasson** [paulevsGitch/BetterEnd#45]
Running this mod alongside [Wild World](https://www.curseforge.com/minecraft/mc-mods/wild-world) makes this pop up when starting up (on both the client and server):

`Method overwrite conflict for setFeatures in betterend.mixins.common.json:GenerationSettingsAccessor, previously written by me.andre111.wildworld.mixin.MixinGenerationSettings. Skipping method.`

Here's a direct link to their [MixinGenerationSettings.java](https://bitbucket.org/andre111/wildnature/src/1.16/src/main/java/me/andre111/wildworld/mixin/MixinGenerationSettings.java) for reference.

**Comment by paulevsGitch** [comment]
Thank you for report, I will add suffix to function to prevent conflicts

**Comment by paulevsGitch** [comment]
Fixed in 0.8.6
