### ISSUE TITLE
Megalakes/Lakes tend to be filled with end stone

### ISSUE THREAD

**Issue by Soldies** [paulevsGitch/BetterEnd#450]
Again, I am using the latest BCLib and BE version for 1.18.1. For whatever reason, naturally generating lakes fail to generate and are just left with the end stone at the bottom of what would be the lake. Megalakes generate perfectly fine though, other than the fact that they tend to get covered with end stone in some parts.
![help](https://user-images.githubusercontent.com/98559994/156975491-2ab7d951-9de0-4480-85ec-0543fa770e7b.png)

**Comment by paulevsGitch** [comment]
This is also related to #436
