### ISSUE TITLE
BE Wrecked Ships

### ISSUE THREAD

**Issue by TakashiOreki** [paulevsGitch/BetterEnd#451]
The "wrecked" ships do not look wrecked:
![image](https://user-images.githubusercontent.com/31328512/157134538-51858400-3abb-407f-bf56-381c562ff418.png)

**Comment by TakashiOreki** [comment]
Or, only a small part of it near the bottom looks wrecked as you can see with the endstone being ripped off the front of the ship; but not the other parts.

**Comment by TakashiOreki** [comment]
For reference they had previously looked like (screenshot taken in BE 1.16.5, version 0.9.8.5) this:
![image](https://user-images.githubusercontent.com/31328512/157135956-83bc03cb-8b8e-422f-8414-de0fb9b614c7.png)

**Comment by paulevsGitch** [comment]
In dev version it looks fine, so I think it works as intended now

![2022-04-26_05 30 44](https://user-images.githubusercontent.com/17707380/165207777-e9bbb025-0c8d-40b1-b287-69f4b0b3c45b.png)

**Comment by paulevsGitch** [comment]
Fixed in 1.1.0
