### ISSUE TITLE
Missing Endstone Texture

### ISSUE THREAD

**Issue by ShadowThunder992** [paulevsGitch/BetterEnd#454]
The version I used is for 1.18.1 on a modpack called "afterlife" which I have slightly modified, removing a mod that makes you change origins when you die. Arriving at the end the normal endstone (dragon island and also the various islands after to go and get the elytra), they have the problem of giving the black and purple block without texture. Removed the mods the problem is not there. (At the moment I have no screenshots because I have taken the mods off for a long time, and I am nowhere near the end in the new world!)

**Comment by paulevsGitch** [comment]
One of your mods breaks Fabric rendering API or endstone rendering. You can use Indium to fix this. This is not a BE issue
