### ISSUE TITLE
Bugs for EVERY SINGLE MOD...

### ISSUE THREAD

**Issue by Theobot3782** [paulevsGitch/BetterEnd#455]
Betterend and Eden Ring: Cause Crash on startup! The message said something about java runtime config being invalid.
Betternether: Use an anvil to repair and enchant items??? IMMA CRASH UR GAME FOR YA! HA!!!

**Comment by paulevsGitch** [comment]
Please provide correct reports

**Comment by Theobot3782** [comment]
sorry :/
