### ISSUE TITLE
End cities much rarer than vanilla

### ISSUE THREAD

**Issue by balt-is-you-and-shift** [paulevsGitch/BetterEnd#456]
I've looked for at least 8 hours, searching tens of thousands of blocks, all to no avail. I've only found two end cities, and they're like 40 blocks tall with no loot. PLEASE increase the chance of end cities, I'm dying here.

**Comment by balt-is-you-and-shift** [comment]
For reference, this is what a vanilla end city distribution looks like:
![image](https://user-images.githubusercontent.com/59123926/160313110-c29d7cb2-ffae-4388-a532-f5379d6936f5.png)

**Comment by paulevsGitch** [comment]
In Better End cities are generating much more common than in vanilla due to different terrain generator. Their chance is also configurable
