### ISSUE TITLE
(Suggestion) Make an opportunity to upgrade Crystallite Armor! :)

### ISSUE THREAD

**Issue by Theobot3782** [paulevsGitch/BetterEnd#457]
I think there should be a new ore added to the end, a type of metal! It will be just like netherite, but you can upgrade crystallite armor to it, this will give the crystallite more durability, protection, max health, ETC and still have the status effects! :)
Maybe this ore could be nether related (who knows???)

**Comment by paulevsGitch** [comment]
There is already an alloy that is stronger than Netherite - Aeternium. Crystallite is a magic compound that uses other gameplay style compared to Aeternium gear, it compensate protection weakness it with positive effects on the player and is not supposed to be harder than Netherite
