### ISSUE TITLE
Not all aeternium items are fire resistant!

### ISSUE THREAD

**Issue by Theobot3782** [paulevsGitch/BetterEnd#458]
Only the tools and armor are fire resistant! the rest of the aeternium items, like the tool heads, sword handle, blade, aeternium ingot and plate, the aeternium block and anvil all burn in lava and fire! Can you fix this please?

**Comment by Theobot3782** [comment]
Same thing happens with cinncinnasite and nether ruby for better nether

**Comment by paulevsGitch** [comment]
Fixed in 1.1.0
