### ISSUE TITLE
Modifying / Editing recipes

### ISSUE THREAD

**Issue by BrekiTomasson** [paulevsGitch/BetterEnd#46]
In my modpack, I use Cotton to disable the crafting recipes for buttons in vanilla Minecraft and any mod that adds blocks that can be crafted into buttons, and then I use a datapack to put the recipes back in but with 4 buttons as output instead of just one - because 1 plank => 1 button just doesn't make sense, right?

Now, this is usually really simple, just adding `"cinderscapes:scorched_button"` to `config/CottonDatapack.json5` will remove that recipe, because it's added to the game using the normal JSON-file-in-the-resources-folder method. The way you've implemented these recepies, however, makes it so that Cotton can't remove them. Do you have any alternate ways of doing this, or are there any plans to changing the recipes to something more compatible with how everybody else does it?

**Comment by paulevsGitch** [comment]
It is possible to rewrite recipe with correct json, we will add a config for all code recipes so you will be able to disable them

**Comment by paulevsGitch** [comment]
![image](https://user-images.githubusercontent.com/17707380/103593161-1ffcee80-4f06-11eb-82c5-62a65dd26cc2.png)

**Comment by BrekiTomasson** [comment]
Thanks!

**Comment by paulevsGitch** [comment]
Added in 0.8.6
