### ISSUE TITLE
1.18.2 Compatibility

### ISSUE THREAD

**Issue by atyshka** [paulevsGitch/BetterEnd#460]
Is this mod not yet compatible with 1.18.2? It seems to be crashing for me, I'm assuming the underlying bclib dependency still needs to be updated?

**Comment by paulevsGitch** [comment]
Generation mods for 1.18.1 are not compatible with 1.18.2

**Comment by OverloadedWithMods** [comment]
the devs are working on it, look at the 1.18.2 branch
