### ISSUE TITLE
Better end increases loading time a lot!

### ISSUE THREAD

**Issue by OverloadedWithMods** [paulevsGitch/BetterEnd#463]
Look at these times (in my modpack):

without
Control: Charm
Better end
Better nether
Eden Ring
Raw loading time: 1 min 16 seconds
Dashloader time:        41 seconds

without
control: Charm
Better End
Better nether
Raw loading time: 1 min 15 seconds
Dashloader time:        41 seconds

wtihout:
control: Charm
Better nether
Raw loading time: 1 min 32 seconds
Dashloader time:        53 seconds 

without:
control: Charm
Raw loading time: 1 min 39 seconds
Dashloader time:        56 seconds 

wtihout:
control: Charm
Better end
Raw loading time: 1 min 20 seconds
Dashloader time:        45 seconds

You see the issue!

**Comment by OverloadedWithMods** [comment]
?

**Comment by OverloadedWithMods** [comment]
I tested rigorously

**Comment by OverloadedWithMods** [comment]
Why is the issue closed this is a genuine issue!

**Comment by OverloadedWithMods** [comment]
Can you atleast explain why it was closed?

**Comment by paulevsGitch** [comment]
> Can you atleast explain why it was closed?

Mod with 87МБ of assets can't load fast

**Comment by OverloadedWithMods** [comment]
Well, I guess that is fair but it's still a fair bit of time being consumed. Anyways, thanks for explaining!
