### ISSUE TITLE
Flowerpots not accepting items

### ISSUE THREAD

**Issue by Runovaris** [paulevsGitch/BetterEnd#464]
I'm playing a 1.18.1 modpack with Better End/Nether, and any of the flowerpots from either one don't accept items. I've gone through all plants, both vanilla and modded.

**Comment by paulevsGitch** [comment]
Did you put ground for plant first?

**Comment by Runovaris** [comment]
How does one do that? Does it only accept soil from the Better End?

**Comment by paulevsGitch** [comment]
> How does one do that?

Right click

> Does it only accept soil from the Better End?

Yes, pots are designed oly for BetterEnd plants

**Comment by Runovaris** [comment]
Ah, thank you! Any plans on allowing any plant to be placed within?

**Comment by paulevsGitch** [comment]
Most BE plants (and leaf blocks) can be planted into pots, there are no plans to add other plants for them as they are using blockstates for plants and soils
