### ISSUE TITLE
Incompatibility with Quilt (uses FAPI impl)

### ISSUE THREAD

**Issue by sisby-folk** [paulevsGitch/BetterEnd#469]
```
Minecraft 1.18.2
Quilt Loader 0.16.0-beta.16
bclib-1.4.5
better-end-1.1.0
qsl-1.1.0-beta.8_qfapi-1.0.0-beta.12_fapi-0.51.1_mc-1.18.2
```
[latest.log](https://0x0.st/oAfZ.txt)

Functions correctly with 
```
Fabric 0.14.4
fabric-api-0.51.1+1.18.2.jar
```

Suggested reason: mod uses bits from FAPI's `impl` package (perhaps erroneously)

**Comment by paulevsGitch** [comment]
BetterEnd is a Fabric mod, it was not made for Quilt

**Comment by sisby-folk** [comment]
Continued in https://github.com/paulevsGitch/BetterNether/issues/544
