### ISSUE TITLE
1.18.2 Fabric server - No dragon or Portal

### ISSUE THREAD

**Issue by XelaDK** [paulevsGitch/BetterEnd#473]
My 1.18.2 server for fabric doesnt spawn a dragon or the portal frame under the dragon, ive tried reseting the end multiple times. Is this a know bug or something that can be fixed easily?

-XelaDK

**Comment by paulevsGitch** [comment]
> ive tried reseting the end multiple times

You need to delete previous dragon fights data from level.dat. Otherwise dragon will not spawn again. This is a vanilla thing - Minecraft doesn't imply deletion of data (including dimension regions) and will not recreate dragon automatically if chunks were deleted. This is not a BetterEnd issue
