### ISSUE TITLE
Fabric server 1.18.2 - No portal or Dragon

### ISSUE THREAD

**Issue by XelaDK** [paulevsGitch/BetterEnd#474]
My 1.18.2 server for fabric doesnt spawn a dragon or the portal frame under the dragon, ive tried reseting the end multiple times, as stated in issue  #473 . Ive also editied the level.dat file as you previous stated so the fight never happend then reset the end again, still didn't work, i took a screenshot so you can see that not even the portal frame is there as it normally would be, even i vanilla if the dragon was glitched.
![image](https://user-images.githubusercontent.com/79642141/168444468-5cfb9360-68a1-4e07-b171-5e9d9202229b.png)

Hope you can help.

-XelaDK

**Comment by paulevsGitch** [comment]
If dragon don't spawn - this is issue with incorrectly removed data. This bug will happen in vanilla too, it is not related to BetterNether. Please don't duplicate issues if they were already opened
