### ISSUE TITLE
Remapping failed

### ISSUE THREAD

**Issue by thfgvileundbv** [paulevsGitch/BetterEnd#48]
ok so I downloaded this in a mod pack and all the other mods work and I wanted to open it on my server that I already setup and it's working fine but when I try to go to that server it says the remapping failed for all of the fails in betterend.

**Comment by paulevsGitch** [comment]
Are all mods on server and client have same version and configs?

**Comment by paulevsGitch** [comment]
I close this issue since there was no answer
