### ISSUE TITLE
End Cities not spawning

### ISSUE THREAD

**Issue by nbdTyler** [paulevsGitch/BetterEnd#489]
Trying to create a private modpack for my friends and I and when I test the End out, it looks amazing, but upon using the "/locate" command to find an end city, it says there are none. I've spent about an hour just flying around trying the command, and nothing. The only way to get an End City to spawn is to disable BetterEnd, which I really don't want to do, because it looks so good and makes everything 100x better, so I was wondering why this is happening??

### Some Information (if it helps):

End Mods -
- BYG
- Nullscape
- BetterEnd

World Generation
- BetterX

**Comment by paulevsGitch** [comment]
Hi, please don't use the old tracker for issues, use only [the new one](https://github.com/quiqueck/BetterEnd/issues)

**Comment by OrangeFoxick** [comment]
@nbdTyler Hi have you been able to solve this problem?
If yes, please tell me how
