### ISSUE TITLE
Blocks being replaced when connected to vanilla server

### ISSUE THREAD

**Issue by spiralhalo** [paulevsGitch/BetterEnd#49]
1. Without Better End:
![2021-01-07_13 30 42](https://user-images.githubusercontent.com/8444172/103860474-3e254300-50ee-11eb-9336-da3e83534351.png)

2. With Better End:
![2021-01-07_13 33 38](https://user-images.githubusercontent.com/8444172/103860494-48dfd800-50ee-11eb-888a-f1fe4ebd0feb.png)

3. The entire blocks are replaced, not just the texture, by looking from the block id of the replaced blocks.
4. The server is unaffected, seems to be purely client side.
5. I was unable to reproduce this in single player world.
6. Here is a log of when this happens: https://gist.github.com/spiralhalo/e9ae207ff376931b9c3a54f8c230f765

**Comment by IMS212** [comment]
this happens with every single mod that adds custom blocks from what i can tell, i believe it's unavoidable

**Comment by quat1024** [comment]
This happens whenever a mod adds new blockstates to a vanilla block, as is done in `ChorusPlantBlockMixin`.

The game login process assumes but *does not verify* that a given block ID has the same set of blockstates on the client and the server.

**Comment by paulevsGitch** [comment]
I don’t know about possibility to check if client is on vanilla server or not, I will add a config option that will make possible to disable new chorus states

**Comment by paulevsGitch** [comment]
New blockstates off/on. This option will be in generator.json config

![2021-01-11_10 19 23](https://user-images.githubusercontent.com/17707380/104159064-b433ed80-53ff-11eb-8101-432b007c4372.png)
![2021-01-11_11 23 51](https://user-images.githubusercontent.com/17707380/104159067-b5651a80-53ff-11eb-99e5-c392f643e96d.png)

**Comment by paulevsGitch** [comment]
Config option to disable custom chorus plat added in 0.8.6
