### ISSUE TITLE
Crash with Better Slabs mod

### ISSUE THREAD

**Issue by cs127** [paulevsGitch/BetterEnd#5]
Better slabs mod:
https://www.curseforge.com/minecraft/mc-mods/better-slabs
https://github.com/Eilux/BetterSlabs

Crash report:
[crash-2020-10-23_22.20.23-client.txt](https://github.com/paulevsGitch/BetterEnd/files/5431325/crash-2020-10-23_22.20.23-client.txt)

**Comment by paulevsGitch** [comment]
I couldn't see anything relative to Better End in this crash
