### ISSUE TITLE
[BYG compatibility] Purpur peaks overlap other structures

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#50]
There might not be anything to do about this, but at around position 750, ~, -900 in a world generated with seed -8805222280992705697 with Better End and BYG installed, I found this purpur peak structure extending far outside of the nearest byg:purpur_peaks biome, and submerging some Crystal Mountains mountains and Old Bulbis Gardens bulbis in a visually unappealing way. This occurred on the junction point of BYG's *Purpur Peaks* biome and Better End's *Crystal Mountains* and *Old Bulbis Gardens* biomes. Curiously, when using /fill to strip away the purpur stone, the bulbis and crystal mountains are found to be intact.

Seeing as how you have branched into explicit support for BYG with biome variants, I was wondering if you could perhaps do something about this, or, alternatively, if I should ask the BYG team to rework the peaks to stick closer to their biome.

![2021-01-08_17 40 49](https://user-images.githubusercontent.com/69029346/104079856-c9c7ce00-51d9-11eb-9087-e6e0fa0fbe18.png)
Upon using /fill to remove some of the purpur stone:
![2021-01-08_17 44 44](https://user-images.githubusercontent.com/69029346/104079857-caf8fb00-51d9-11eb-96f9-48c4f60d1785.png)

**Comment by paulevsGitch** [comment]
BYG spikes are simple noise values that don't check if neighbor biome is near or not, this should be fixed from BYG side
