### ISSUE TITLE
[BYG compatibility] Blossoming Spires and BYG Ethereal Islands boundary issues

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#51]
With Better End and BYG installed together, if the Blossoming Spires biome generates next to one of BYG's Ethereal Islands biomes, the floating spires that generate as part of the former but generate in the Etherial Islands take on the Ether Phylium top block from the it, but not the Ether Soil or Stone that make up its terrain. This causes them to look a bit strange.

![2021-01-08_16 36 31](https://user-images.githubusercontent.com/69029346/104080468-ee717500-51dc-11eb-964e-40f0779aec41.png)

Seeing as how you have branched into explicit support for BYG with biome variants, I was wondering if you could perhaps do something about this.

**Comment by paulevsGitch** [comment]
Partially fixed, I couldn't get custom stone type from biome, but I can get its surface

![2021-01-14_22 02 46](https://user-images.githubusercontent.com/17707380/104636348-449a5880-56b4-11eb-9141-75c976c115a1.png)

**Comment by paulevsGitch** [comment]
Looks like I didn't close this issue after fix release
