### ISSUE TITLE
Z-fighting underneath violecite brick wall

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#52]
As per the title, the post and wall elements of the violecite brick wall z-fight on the bottom of the block.
This issue is best seen in a world, where the flickering is visible.
![2021-01-08_18 46 18](https://user-images.githubusercontent.com/69029346/104081217-16afa280-51e2-11eb-99fe-80c52c48ee80.png)

**Comment by paulevsGitch** [comment]
Small offset fixed that

![2021-01-11_11 39 29](https://user-images.githubusercontent.com/17707380/104160154-b26b2980-5401-11eb-86df-8d0572d76ad1.png)

**Comment by paulevsGitch** [comment]
Fixed in 0.8.6
