### ISSUE TITLE
[Potential Conflict] Biome Makeover

### ISSUE THREAD

**Issue by BrekiTomasson** [paulevsGitch/BetterEnd#53]
Here's another potential conflict similar to the one I raised back in #45 

`[00:25:30] [main/WARN]: Method overwrite conflict for setSlimeSize in biomemakeover.mixins.json:SlimeEntityMixin, previously written by ru.betterend.mixin.common.SlimeEntityMixin. Skipping method.`

**Comment by BrekiTomasson** [comment]
`Method overwrite conflict for method_8132 in betternether.mixins.common.json:RecipeManagerMixin, previously written by ru.betterend.mixin.common.RecipeManagerMixin. Skipping method.`

This looks like more of the same.

**Comment by paulevsGitch** [comment]
This methods both set slime size and are probably are similar. I will add suffix to method, this will prevent possible conflict

**Comment by paulevsGitch** [comment]
Fixed in 0.8.6
