### ISSUE TITLE
Ender Dust?

### ISSUE THREAD

**Issue by BrekiTomasson** [paulevsGitch/BetterEnd#54]
I'm unable to create the Ender Dust item in-game, for some reason, and have had to implement a custom recipe for it for now.

Looking at your code, it looks like you're adding it as an Anvil recipe... Does that mean that it absolutely requires a Hammer to smash the Ender Pearl into dust? Is there any way of adding a version of this recipe without the requirement to use Hammers? My modpack tries to avoid new tool "types", sticking to the five old faithfuls: pickaxe, axe, sword, shovel, hoe. Maybe we could have something like giving players the option of 'cracking' the Ender Pearl in a Blast Furnace?

**Comment by paulevsGitch** [comment]
By our design hammers are used for recipes like that. If you want another type of recipes you can use datapacks
