### ISSUE TITLE
Tree leaves

### ISSUE THREAD

**Issue by Blob336** [paulevsGitch/BetterEnd#56]
Helix tree leaves do not decay after all log is mined. I tested only helix tree that I planted in overworld. Also all tree leaves are not mined faster with hoes.

**Comment by paulevsGitch** [comment]
Helix tree leaves will not decay, they are similar to warped tree foliage

**Comment by paulevsGitch** [comment]
I fixed hoe speed, it will be in the next release

**Comment by paulevsGitch** [comment]
Fixed in 0.8.6
