### ISSUE TITLE
Bookshelves uses paper in crafting but drop books

### ISSUE THREAD

**Issue by vemerion** [paulevsGitch/BetterEnd#59]
When porting the different wood blocks to the Forge version, I came across this bug. The crafting recipe for the mod bookshelves takes 3 paper in the middle row [(see here)](https://github.com/paulevsGitch/BetterEnd/blob/ba68f1fe4ff73d81413e10b408d6ba0f78e6de4a/src/main/java/ru/betterend/blocks/complex/WoodenMaterial.java#L111) (unlike vanilla which uses books), but when destroyed, the bookshelves drop books [(see here)](https://github.com/paulevsGitch/BetterEnd/blob/ba68f1fe4ff73d81413e10b408d6ba0f78e6de4a/src/main/java/ru/betterend/blocks/basis/EndBookshelfBlock.java#L34). I would create a pull request that fixes this, but I am unsure which way you would want it to be fixes: change the recipe or change the drop?

**Comment by paulevsGitch** [comment]
Fixed in 0.9.0
