### ISSUE TITLE
BetterEnd makes my end mod essentially useless

### ISSUE THREAD

**Issue by quek04** [paulevsGitch/BetterEnd#6]
With both BetterEnd and Quek's End installed, a lot of the things I implement into the End (essentially everything) seem to be removed. 
I mixin into the DefaultBiomeCreator to add things to the 4 vanilla End biomes, and it seems that you mixin into that class as well. I think this causes things I add in my mod to not appear in the End.

**Comment by quek04** [comment]
I make the End Highlands look like this: 
![image](https://user-images.githubusercontent.com/55364841/97047097-0d495f00-153e-11eb-83b3-8388721c6a3b.png)

And with your mod combined with mine, the End Highlands look like this:
![image](https://user-images.githubusercontent.com/55364841/97047138-1afee480-153e-11eb-8aa7-d4e3c339d76a.png)

**Comment by EnderBro123** [comment]
Hey! Say your mod. If you wanna join the Discord, then here's the link.
https://discord.gg/azkRMYB

**Comment by paulevsGitch** [comment]
Better End change only Highlands, other vanilla End biomes are the same

**Comment by quek04** [comment]
I noticed after reporting. Could we fix this issue though, somehow?

**Comment by paulevsGitch** [comment]
I looked into you mixin, this is not good method to add features - it is not compatible with datapacks and other mod biomes, you will have similar issue with other mods like BYG. Better way to add features is to add them via worldgen init, like [this](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/util/FeaturesHelper.java#L22). With this way you can add any feature to any biome without overriding generator. The same can be done for surface builder.

My mixin into default biome creator are simple, and I will remove it as the same things can be done with method above. Actually mountains already adding with that method

**Comment by paulevsGitch** [comment]
There is also an alternative way. We also have a [public API](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/api/BetterEndPlugin.java) to make biomes in our generator as well. With it you can create your biomes instead of vanilla modification - they will be added only when BE installed, so you will have 2 modes - without BE (vanilla modify) and with BE - custom biomes. They will appear in the world like all other biomes. You can also modify many parameters that vanilla biomes don't have - like fog color or fog density, biome spawn chance, etc.

**Comment by paulevsGitch** [comment]
I also decided to move my content into separate biomes (from vanilla biomes), so it will not conflict with other mods. In v.0.4.0 it will be in its own biomes

**Comment by paulevsGitch** [comment]
![2020-10-24_18 19 44](https://user-images.githubusercontent.com/17707380/97085358-a30be980-1625-11eb-8c95-d4e59d1b8753.png)

**Comment by paulevsGitch** [comment]
![2020-10-24_18 36 00](https://user-images.githubusercontent.com/17707380/97085710-d0f22d80-1627-11eb-82f9-66838f7cbe31.png)

**Comment by paulevsGitch** [comment]
@quek04, looks like [this mixin function](https://github.com/quek04/Queks_End/blob/master/src/main/java/quek/queksend/mixin/ChorusPlantBlockMixin.java#L41) conflicts with [our mixin function](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/mixin/common/ChorusPlantBlockMixin.java#L48). The result is incorrect chorus block shape. Can you try to replace target value from _INVOKE_ to _RETURN_ please?

![2020-10-24_18 41 57](https://user-images.githubusercontent.com/17707380/97086480-28929800-162c-11eb-92ae-ece29522d7e8.png)

**Comment by quek04** [comment]
Sure thing

**Comment by paulevsGitch** [comment]
Fixed in 0.4.0
