### ISSUE TITLE
Generation bug Server

### ISSUE THREAD

**Issue by EkutoruSama** [paulevsGitch/BetterEnd#60]
I have created my own server and I see with this mod a bug with some blocks like water corails dirt and other Got switched with random block. Wen you broke them, You got the official items but Earlyer, you have an other block.
![2021-01-16_13 19 22](https://user-images.githubusercontent.com/77534573/104811680-808d0500-57fd-11eb-8e08-e3a2a912e23c.png)
![2021-01-16_13 19 08](https://user-images.githubusercontent.com/77534573/104811682-81259b80-57fd-11eb-9720-05770851b658.png)
![2021-01-16_12 53 30](https://user-images.githubusercontent.com/77534573/104811683-81be3200-57fd-11eb-8399-e71e676942f6.png)

**Comment by paulevsGitch** [comment]
Does client and server have the same mod version?

**Comment by EkutoruSama** [comment]
Yep, I using fabric 1.16.4 and other mods have the same version. But this bug are Only in the server. After disable this mod and re-join my server, the bug leave.

**Comment by EkutoruSama** [comment]
When I use BetterEnd on the server, the blocks are bugged and when I don't use it the world goes back to normal

**Comment by paulevsGitch** [comment]
Probably this is relative to [this](https://github.com/paulevsGitch/BetterEnd/issues/49), I will test it

**Comment by EkutoruSama** [comment]
Yea, the same blocks have switched to end scafold. 
Thank you for read my post

**Comment by paulevsGitch** [comment]
You can try to disable chorus plant changes in the config, this probably can help

**Comment by EkutoruSama** [comment]
Okay, Thank you <3

**Comment by paulevsGitch** [comment]
As i think this is same issue as #49 I will close this as it was resolved (I think) with the configs
