### ISSUE TITLE
weird textures

### ISSUE THREAD

**Issue by Baiorettojdm** [paulevsGitch/BetterEnd#61]
![2021-01-15_21 39 32](https://user-images.githubusercontent.com/77535348/104812165-b1bb0480-5800-11eb-8d45-5dd96765cfb0.png)
I don't know if its related to the mod or game settings but i dont know how to fix this.
Its very hard to walk around since you can barely see the ground.
Someone please help me on this.

**Comment by paulevsGitch** [comment]
Looks like you are using shaders and optifine. This bug is not relative to BE
