### ISSUE TITLE
Obsidian End Platform does not Generate

### ISSUE THREAD

**Issue by milkev** [paulevsGitch/BetterEnd#66]
The obsidian platform the player is supposed to spawn on upon entering the end, is not present. Attempted on multiple worlds.

Am using the new generation which must be toggled on in the configs.

For most of my worlds, the player did spawn on the end island itself, which would make this not an issue... but some of them also spawned me out in the void, which will be a instakill for any player entering the end without an elytra.

**Comment by paulevsGitch** [comment]
This is known issue, it will be fixed

**Comment by paulevsGitch** [comment]
Fixed in 0.9.0
