### ISSUE TITLE
Vines Displace Shulkers in End Cities

### ISSUE THREAD

**Issue by milkev** [paulevsGitch/BetterEnd#68]
Vines that generate inside End Cities are cool, in my humble opinion, however they displace shulkers, sometimes to nearby tree's and places not within the End City itself.

Am using the new generation which must be enabled in config.
![2021-01-21_23 33 10](https://user-images.githubusercontent.com/22010128/105458545-08cc3980-5c46-11eb-9441-e15d7d30b787.png)

**Comment by paulevsGitch** [comment]
This is not a bug, shulkers can teleport randomly to nearby structures
