### ISSUE TITLE
[Suggestion] Seperate Crystal Grass and Crystal Flowers

### ISSUE THREAD

**Issue by milkev** [paulevsGitch/BetterEnd#69]
Separate crystal grass into two blocks, crystal grass, and crystal flowers. This way they can be more easily used for decoration, instead of hoping the coordinates of wherever you are building is suited for what you want.
I haven't checked if this sort of functionality is elsewhere as well, but if it is I would suggest the same change.
![2021-01-22_00 10 16](https://user-images.githubusercontent.com/22010128/105458773-682a4980-5c46-11eb-9fe4-3986e30c81aa.png)

**Comment by paulevsGitch** [comment]
I think grass will not be separated as it just random block variants
