### ISSUE TITLE
[Suggestion] Player made Eternal Portals/Moving Eternal Portals

### ISSUE THREAD

**Issue by milkev** [paulevsGitch/BetterEnd#70]
When I first saw the eternal portals I thought it would be pretty cool. A non-end-gateway way to teleport between the end and a certain location in the overworld.

Mainly I was hoping that the player was able to build these anywhere they wanted, which is sadly not the case. In fact the entire structure is unbreakable. The overworld side of it is as well. Most of the ones I found and activated in my creative testing spawned a portal at the bottom of the ocean... not a very usable place for the portal.

It would be great if the Eternal Portals were able to be created by the player (even if its just a creative mode thing) at any location in the end. They could be similar to nether portals, but for the end.

This would be a great addition to just about any base. The structure itself also looks pretty cool.

As they currently are, I don't see much value in them, outside of the cool factor in first finding/activating one.

**Comment by paulevsGitch** [comment]
Eternal portals are impossible to made by design
