### ISSUE TITLE
Sodium incompatibility?

### ISSUE THREAD

**Issue by srnyx** [paulevsGitch/BetterEnd#72]
I think that the mod might be incompatible with Sodium.
Whenever I try going to the end or logging into the end (after crashing when I die), I crash and can't do anything.
I don't get any crash reports either, I've only gotten one so far and it had Sodium in it. This only happens when going to the end.

**Comment by paulevsGitch** [comment]
Please attach your crashlog

**Comment by srnyx** [comment]
> Please attach your crashlog

There was none, weirdly. I didn't really crash, I just got stuck on the "Loading terrain..." screen when trying to join the server and had to close out of Minecraft.

**Comment by paulevsGitch** [comment]
Sodium and Better End are compatible at some versions and on some are not, I don't know why. You can try to updgrade/downgrade sodium/BE and find working pair. Some issues will be fixed in the next release of BetterEnd (with water)
