### ISSUE TITLE
Crash upon clicking in the anvil screen with an item when there are no anvil recipes present

### ISSUE THREAD

**Issue by LeoCTH** [paulevsGitch/BetterEnd#74]
Crash log here: https://paste.gg/p/anonymous/f7556b6a1024492b886fabc3898d69d5
Upon examining `AnvilScreenHandlerExtended#be_previousRecipe` ([here](https://github.com/paulevsGitch/BetterEnd/blob/8d56a7ec7efc6432b684f6fbe24b64124bdb6e95/src/main/java/ru/betterend/interfaces/AnvilScreenHandlerExtended.java#L22)), it seems like the method does not check whether the list of recipes (`recipes`) is empty, causing the index value to be erroneously set to -1 and an `ArrayIndexOutOfBoundsException` occurs when trying to use that index to access the recipe list.

**Comment by Bulldog83** [comment]
Fixed in dev code

**Comment by paulevsGitch** [comment]
Fixed in 0.9.0
