### ISSUE TITLE
[Suggestion] Make metal blocks possible to use as a beacon pyramid blocks

### ISSUE THREAD

**Issue by Pablindatz** [paulevsGitch/BetterEnd#75]
Not even with REI I can seem to find the way to craft any of the ores, and I've inspected every block in the mod an still no luck.
Is there any tutorial that I can watch to get an Idea on how to get these materials.

Is there any way you could make the blocks in the mod work with Beacons?

**Comment by paulevsGitch** [comment]
Ores are not craftable, they are findable in the world

**Comment by paulevsGitch** [comment]
Added in 0.9.2
