### ISSUE TITLE
Shift Clicking Anvil Recipes consumes low durability

### ISSUE THREAD

**Issue by milkev** [paulevsGitch/BetterEnd#77]
Shift clicking an anvil recipe while there is more than 1 item in the slot (ie: a stack of ender pearls) only consumes 5 durability on your hammer, when it should consume 5 x stackCount (with a full stack of enderpearls, 5x16=80 durability).

**Comment by Bulldog83** [comment]
Fixed in the dev code

**Comment by paulevsGitch** [comment]
Fixed in 0.9.0
