### ISSUE TITLE
Aeternium shouldnt burn in lava

### ISSUE THREAD

**Issue by Hinake** [paulevsGitch/BetterEnd#79]
so, I was looking at the recipes for the items, and saw that aeternium is made with netherite, which doesnt burn, yet aeternium still does burn... i dont think it should

**Comment by JustReg2Download** [comment]
True, seems without logic.

**Comment by Bulldog83** [comment]
In the dev code

**Comment by Beethoven92** [comment]
> 
> 
> True, seems without logic.

"An alloy is an admixture of metals, or a metal combined with one or more other elements. **The resulting mixture forms a substance with properties that often differ from those of the pure metals**, such as increased strength or hardness" (Cit.)

**Comment by Hinake** [comment]
okay, but even if thats the case would the parts of the alloy that were fire resistant ( the four netherite scraps ) not be fire resistant still? even if its in an alloy those components shouldnt burn... so if you drop aeturnium in lava it seems like you should at least still get the four scraps back

**Comment by paulevsGitch** [comment]
Added in 0.9.0
