### ISSUE TITLE
Incompatible with new Fabric API

### ISSUE THREAD

**Issue by TailsMSN** [paulevsGitch/BetterEnd#8]
[crash-2020-10-27_13.41.24-client.txt](https://github.com/paulevsGitch/BetterEnd/files/5448049/crash-2020-10-27_13.41.24-client.txt)
Of the things installed with MultiMC, there is LWJGL 3 version 3.2.2, Minecraft 1.16.3, Intermediary Mapping 1.16.3, Fabric Load 0.10.5+build.213, Fabric API 0.24.2+build.413-1.16, and Better End 0.4.1-alpha. All other mods in folder are disabled, still crashes.

**Comment by TailsMSN** [comment]
Update: Source of error is the newest Fabric API. Downgrading by one version solved the crash.

**Comment by paulevsGitch** [comment]
v 0.5.0 will be compatible with new Fabric API

**Comment by paulevsGitch** [comment]
Fixed
