### ISSUE TITLE
Does BetterEnd adds mineshafts in the End?

### ISSUE THREAD

**Issue by RDKRACZ** [paulevsGitch/BetterEnd#80]
If no then sorry!

They are broken:
![2021-01-31_03 41 24](https://user-images.githubusercontent.com/43277609/106373062-39168500-6376-11eb-9497-599b8879fd55.png)

**Comment by RDKRACZ** [comment]
Seems like they are from BetterEnd because of the plants on them but they aren't mentioned on the curseforge

**Comment by paulevsGitch** [comment]
BetterEnd doesn’t add mineshafts into the End, looks like you have another mod doing it

**Comment by BluePixel1708** [comment]
it's most likely repurposed structures since it adds end variants of mineshafts, i'd never seem them generate that way tho
