### ISSUE TITLE
Signs should use or extend SignBlockEntity

### ISSUE THREAD

**Issue by martmists-gh** [paulevsGitch/BetterEnd#82]
For compatibility reasons with various mods, signs should extend the vanilla BE.

**Comment by paulevsGitch** [comment]
It is not possible to use Sign Entity at this moment as it has pre-defined type in its constructor. Looks like it is possible to get around this with some mixins, but this require more research

**Comment by armuell** [comment]
Every mod that adds a new woodtype seems to have no issue with creating signs that don't cause gunpowder to crash (traverse, better nether, etc.). Do they all use mixins to avoid that issue? Why does having a pre-defined type in the constructor prevent you from extending it if all you are doing is changing the color of the sign?

**Comment by paulevsGitch** [comment]
> Do they all use mixins to avoid that issue?

Yes, each mod use its own mixins to avoid this. And BetterNether use the same system as BetterEnd, so it will cause the same issues

> Why does having a pre-defined type in the constructor prevent you from extending it if all you are doing is changing the color of the sign?

It is possible to extend it, but you still need to use mixins to make it work properly. Some mods use vanilla entity type and handle it in mixins (terraforms mods, for example), some use its own entities (like BN and BE). There is a WIP version where end sign entity extends vanilla sign entity, but it is not ready yet

**Comment by martmists-gh** [comment]
Worst case scenario I could add a sign interface to Gunpowder that people can support using conditional mixins or something

**Comment by paulevsGitch** [comment]
The current code (from latest commits) should probably work

**Comment by paulevsGitch** [comment]
Fixed in 0.9.2
