### ISSUE TITLE
Add anvil recipe support to the Netherite Anvil

### ISSUE THREAD

**Issue by OroArmor** [paulevsGitch/BetterEnd#83]
The mod https://github.com/OroArmor/Netherite-Plus-Mod/
has a custom anvil. I received a request to add compatibility for your custom anvil recipes with the issue:
https://github.com/OroArmor/Netherite-Plus-Mod/issues/57

After a bit of investigation, it seems that you mixin to the anvil to add your custom recipes, and because my anvil is almost a perfect copy of the vanilla one, a simple mixin plugin should be all that is needed to add support.

**Comment by Bulldog83** [comment]
For the Anvil Recipes I'vt made mixins into AnvilScreen and AnvilScreenHandler. Your Anvil using it's own Screen and ScreenHadler. Moreover, you uses Architectury API. Well, only one way that I see, you yourself will have to implement the recipes using our API.

**Comment by OroArmor** [comment]
Alright i did this on my end. Thank!
