### ISSUE TITLE
I'm using the 1.16.4 version of BetterEnd and End cities don't change

### ISSUE THREAD

**Issue by Pablindatz** [paulevsGitch/BetterEnd#84]
I'm using the 1.16.4 version of BetterEnd and End cities don't change to what I have seen in videos or pictures of the mod, is this normal or do I need some sort of external mod?

**Comment by philoufilou** [comment]
Maybe u mean this Datapack : https://www.planetminecraft.com/data-pack/end-city-for-better-end/

**Comment by paulevsGitch** [comment]
BetterEnd doesn't change End City generation at this moment, all non-vanilla end cities are from datapacks

**Comment by ZenoCoding** [comment]
Are there plans for this in the future?
