### ISSUE TITLE
Better End crash on mod load in Aternos Server

### ISSUE THREAD

**Issue by faustojc** [paulevsGitch/BetterEnd#85]
In my Aternos server, the server always crashes on mod loading. I tried to remove the BetterEnd mod and no crash. I've Oh The Biomes You'll Go mod installed. I haven't tried to remove the Oh the Biomes with BetterEnd mod installed Only. 

I tested the Better End and Oh the Biomes in my singleplayer, there are no errors or crash. Traveled to the end dimension and I saw the BetterEnd's biomes

Mods installed:
- Age of Exile
- Dungeons of Exile
- Better End
- Oh The Biomes
- MO' Structures

Crash log:
https://mclo.gs/abuLklH

**Comment by paulevsGitch** [comment]
We need to test this, looks like wrong API version or mixin error

**Comment by dragongamerxtrm** [comment]
I have the same problem, yet on a pc-hosted server. Any updates?

**Comment by paulevsGitch** [comment]
Is this crash still actual? I mean after all mods updated

**Comment by faustojc** [comment]
> Is this crash still actual? I mean after all mods updated

Yup until today, Only in aternos server, I dont know why, when I have BetterEnd mod installed in Aternos server, the console mentioned "Mixin error" but without BetterEnd, no mixin error

**Comment by paulevsGitch** [comment]
Do you have the same mods on client and server with the same configs?

**Comment by faustojc** [comment]
Yup, everything, the exact configs, versions and same mods on both client and server

**Comment by paulevsGitch** [comment]
After some research we found that Aternos use its own rewritten API, as it is unofficial it will not be supported and this issue will be closed
