### ISSUE TITLE
Literally cannot join any servers with the mod installed

### ISSUE THREAD

**Issue by Eclipse-Ilx** [paulevsGitch/BetterEnd#87]
Whenever i join ANY server with only better end 1.4.1 FORGE i get an error saying

Connection lost

Incomplete set of tags received from server Please contact server operator

Removing the mod solves this problem (This is with and without other mods installed)

**Comment by paulevsGitch** [comment]
This is Fabric version tracker, please report all Forge issues into Forge version tracker
