### ISSUE TITLE
Incompatible with latest BYG version

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#89]
The latest version of *Oh, the Biomes You Go (BYG)* is incompatible with Better End, which throws a crash that seems to have something to do with its compatibility measures. [Here is a crash report.](https://github.com/paulevsGitch/BetterEnd/files/5949452/crash-2021-02-08_21.48.55-client.txt)

In addition to getting this working again, the latest version of *BYG* has made sweeping changes to its End biomes that should preferably be addressed in Better End's compatibility:
- The Bulbis biomes have been reworked entirely with new plantlife and 'tree' shapes, the latter of which seem to take after your 'Old Bulbis Gardens' variant biome. Said biome will likely need some adjustment to work with the new plantlife.
- Likewise, the Nightshade biomes have also seen reworks to the shape of their trees that will no longer match up with Better End's Nightshade Redwoods biome.
- And, finally, BYG adds therium crystal deposits throughout its End biomes, which I heard on the Discord that Better End will likely need to explicitly support.

**Comment by paulevsGitch** [comment]
Bug was related to missing structure IDs, it will be fixed in the next version (I think it will be released during this week)

**Comment by paulevsGitch** [comment]
Shape of redwood trees will be updated later. Crystal deposits probably should be added from BYG side

**Comment by paulevsGitch** [comment]
Fixed in 0.9.0, other things will be added later
