### ISSUE TITLE
Sildurs Vibrant

### ISSUE THREAD

**Issue by NattyNuke** [paulevsGitch/BetterEnd#9]
I have been having an issue with items like torches when they are placed down, I have identified that the issue stems from using the Sildurs Vibrant Extreme shaders. This may not be the right place to post this but I just wanted to bring attention to it.
I'm using version 1.16.3 along with Optifabric and Fabric API and a few other mods.
I know it's not that big a deal, but the mod looks best with Sildurs.

**Comment by NattyNuke** [comment]
BTW other shaders like KUDA and Oceano work fine, it's just Sildurs that it was problems with.

**Comment by NattyNuke** [comment]
![image](https://user-images.githubusercontent.com/73963232/98159329-62746180-1eaa-11eb-896e-f3728fdeccb2.png)

**Comment by NattyNuke** [comment]
![2020-11-04_14 29 06](https://user-images.githubusercontent.com/73963232/98159389-7c15a900-1eaa-11eb-9382-5e63aa9eac10.png)

**Comment by NattyNuke** [comment]
![image](https://user-images.githubusercontent.com/73963232/98159536-c434cb80-1eaa-11eb-8dda-cc9fb0881f05.png)

**Comment by EnderBro123** [comment]
You may wanna let the shaders dev know.

I don't think @paulevsGitch can do anything.

**Comment by paulevsGitch** [comment]
This is shaders issue, not BE

**Comment by NattyNuke** [comment]
Lol fair enough
