### ISSUE TITLE
Enter the end?!

### ISSUE THREAD

**Issue by TheCherry** [paulevsGitch/BetterEnd#90]
Sorry but how can I even enter the end? Eye of Ender doesn't show me the way to the portal, when I build it in creative mode nothing happens and in the book I only find instructions on how to get back to the overworld.

**Comment by dragongamerxtrm** [comment]
To build in creative, stand on the center when placing the frames so that all of them are facing the inside. After that, put the eyes of ender in any order. Hope this helps

**Comment by paulevsGitch** [comment]
This issue was described on the [wiki](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-missing-end-dimension), I hope it will help you

**Comment by TheCherry** [comment]
> 
> 
> This issue was described on the [wiki](https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-missing-end-dimension), I hope it will help you

In the Wiki is described "you will find that you couldn't go into the End" ... I haven't any command to test that.
The Problem is more that I can find the portal self, because the "Eye of Ender" don't work. And I tested this with many new test worlds.

**Comment by Beethoven92** [comment]
BetterEnd doesn't touch the EnderEye behavior. This may be caused by another mod, i had already heard that issue somewhere, before..
