### ISSUE TITLE
my game crashes when i click "create new world"

### ISSUE THREAD

**Issue by CubedSquare** [paulevsGitch/BetterEnd#91]
my game crashed when i clicked create new world

 

here is the crash report:

---- Minecraft Crash Report -------- Minecraft Crash Report ----// Hey, that tickles! Hehehe!
Time: 2/13/21 10:09 AMDescription: mouseClicked event handler
java.lang.NullPointerException: mouseClicked event handler at ru.betterend.integration.byg.BYGIntegration.lambda$addBiomes$1(BYGIntegration.java:54) at ru.betterend.integration.byg.BYGIntegration$$Lambda$5902/334839097.accept(Unknown Source) at java.util.ArrayList.forEach(ArrayList.java:1249) at ru.betterend.integration.byg.BYGIntegration.addBiomes(BYGIntegration.java:40) at ru.betterend.integration.Integrations.lambda$addBiomes$1(Integrations.java:27) at ru.betterend.integration.Integrations$$Lambda$5901/74468852.accept(Unknown Source) at java.util.ArrayList.forEach(ArrayList.java:1249) at ru.betterend.integration.Integrations.addBiomes(Integrations.java:25) at ru.betterend.registry.EndBiomes.mutateRegistry(EndBiomes.java:140) at ru.betterend.world.generator.BetterEndBiomeSource.<init>(BetterEndBiomeSource.java:56) at net.minecraft.class_2874.handler$zkn000$be_replaceGenerator(class_2874.java:521) at net.minecraft.class_2874.method_28533(class_2874.java) at net.minecraft.class_2874.method_28517(class_2874.java:175) at net.minecraft.class_5285.method_28009(class_5285.java:101) at net.minecraft.class_525.method_31130(class_525.java:135) at net.minecraft.class_526.method_19944(class_526.java:54) at net.minecraft.class_526$$Lambda$5711/815032950.onPress(Unknown Source) at net.minecraft.class_4185.method_25306(class_4185.java:33) at net.minecraft.class_4264.method_25348(class_4264.java:16) at net.minecraft.class_339.method_25402(class_339.java:149) at net.minecraft.class_4069.method_25402(class_4069.java:27) at net.minecraft.class_312.method_1611(class_312.java:92) at net.minecraft.class_312$$Lambda$5566/55860765.run(Unknown Source) at net.minecraft.class_437.method_25412(class_437.java:435) at net.minecraft.class_312.method_1601(class_312.java:92) at net.minecraft.class_312.method_22686(class_312.java:162) at net.minecraft.class_312$$Lambda$5420/1920712174.run(Unknown Source) at net.minecraft.class_1255.execute(class_1255.java:104) at net.minecraft.class_312.method_22684(class_312.java:162) at net.minecraft.class_312$$Lambda$4876/1471263360.invoke(Unknown Source) at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) at org.lwjgl.system.JNI.invokeV(Native Method) at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109) at net.minecraft.class_1041.method_15998(class_1041.java:388) at net.minecraft.class_310.method_1523(class_310.java:1068) at net.minecraft.class_310.method_1514(class_310.java:681) at net.minecraft.client.main.Main.main(Main.java:215) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Render threadStacktrace: at ru.betterend.integration.byg.BYGIntegration.lambda$addBiomes$1(BYGIntegration.java:54) at ru.betterend.integration.byg.BYGIntegration$$Lambda$5902/334839097.accept(Unknown Source) at java.util.ArrayList.forEach(ArrayList.java:1249) at ru.betterend.integration.byg.BYGIntegration.addBiomes(BYGIntegration.java:40) at ru.betterend.integration.Integrations.lambda$addBiomes$1(Integrations.java:27) at ru.betterend.integration.Integrations$$Lambda$5901/74468852.accept(Unknown Source) at java.util.ArrayList.forEach(ArrayList.java:1249) at ru.betterend.integration.Integrations.addBiomes(Integrations.java:25) at ru.betterend.registry.EndBiomes.mutateRegistry(EndBiomes.java:140) at ru.betterend.world.generator.BetterEndBiomeSource.<init>(BetterEndBiomeSource.java:56) at net.minecraft.class_2874.handler$zkn000$be_replaceGenerator(class_2874.java:521) at net.minecraft.class_2874.method_28533(class_2874.java) at net.minecraft.class_2874.method_28517(class_2874.java:175) at net.minecraft.class_5285.method_28009(class_5285.java:101) at net.minecraft.class_525.method_31130(class_525.java:135) at net.minecraft.class_526.method_19944(class_526.java:54) at net.minecraft.class_526$$Lambda$5711/815032950.onPress(Unknown Source) at net.minecraft.class_4185.method_25306(class_4185.java:33) at net.minecraft.class_4264.method_25348(class_4264.java:16) at net.minecraft.class_339.method_25402(class_339.java:149) at net.minecraft.class_4069.method_25402(class_4069.java:27) at net.minecraft.class_312.method_1611(class_312.java:92) at net.minecraft.class_312$$Lambda$5566/55860765.run(Unknown Source)
-- Affected screen --Details: Screen name: net.minecraft.class_526Stacktrace: at net.minecraft.class_437.method_25412(class_437.java:435) at net.minecraft.class_312.method_1601(class_312.java:92) at net.minecraft.class_312.method_22686(class_312.java:162) at net.minecraft.class_312$$Lambda$5420/1920712174.run(Unknown Source) at net.minecraft.class_1255.execute(class_1255.java:104) at net.minecraft.class_312.method_22684(class_312.java:162) at net.minecraft.class_312$$Lambda$4876/1471263360.invoke(Unknown Source) at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) at org.lwjgl.system.JNI.invokeV(Native Method) at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109) at net.minecraft.class_1041.method_15998(class_1041.java:388) at net.minecraft.class_310.method_1523(class_310.java:1068) at net.minecraft.class_310.method_1514(class_310.java:681) at net.minecraft.client.main.Main.main(Main.java:215) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
-- System Details --Details: Minecraft Version: 1.16.4 Minecraft Version ID: 1.16.4 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_51, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 823232672 bytes (785 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB) CPUs: 8 JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M Fabric Mods:  allure: Allure 1.2.8 angerable-patch: Angerable Patch 1.0.0-1.16.1 autoconfig1u: Auto Config v1 Updated 3.3.1 bettercaves: YUNG's Better Caves 1.16.2-1.0.3 betterend: Better End 0.9.0-pre betternether: Better Nether 5.0.4 betterweather: Better Weather 1.0.0 biomemakeover: Biome Makeover 1.16.4-1.2.0 byg: BYG 1.1.4 campanion: Campanion 1.2.0+build.39 cavebiomes: Cave Biomes 0.5.1 charm: Charm 2.2.2 charmonium: Charmonium 2.2.2 cinderscapes: Cinderscapes 1.3.0+build.51 cloth-api: Cloth API 1.2.1 cloth-basic-math: Cloth Basic Math 0.5.1 cloth-config2: Cloth Config v4 4.8.3 com_electronwill_night-config_core: core 3.6.2 com_electronwill_night-config_toml: toml 3.6.2 com_moandjiezana_toml_toml4j: toml4j 0.7.2 croptopia: Croptopia 1.1.0 dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2 enderitemod: Enderite Mod 1.2.2 endreborn: End: Rebellion 1.8 fabric: Fabric API 0.29.3+1.16 fabric-api-base: Fabric API Base 0.2.0+ab87788d3a fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a fabric-language-scala: Fabric Language Scala 1.0.0 fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095 fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a fabricloader: Fabric Loader 0.10.8 fluidphysics: Fluid Physics 1.3.9+fabric-1.16.4 jankson: Jankson 3.0.1+j1.2.0 kirin: Kirin UI 1.7-1.16.2 libgui: LibGui 3.0.0-beta.1+1.16.2-rc2 libstructure: LibStructure 1.5 minecraft: Minecraft 1.16.4 minecraftcapes: MinecraftCapes Mod 10 mm: Manningham Mills 2.1 modmenu: Mod Menu 1.14.7+build.11 morepaths: More Paths 0.0.3 mostructures: Mo' Structures 1.0.0-pre3+mc.1.16.2 net_openhft_zero-allocation-hashing: zero-allocation-hashing 0.11 optifabric: OptiFabric 1.8.16 physicsmod: Physics Mod 1.0.0 presencefootsteps: Presence Footsteps r29+1.16.4 pumice: Pumice 0.0.2 reach-entity-attributes: Reach Entity Attribute 1.0.1 reborncore: Reborn Core 4.6.3+build.110 repurposed_structures: Repurposed Structures 1.16.4-1.7.0 seasons: Fabric Seasons 1.0.3-BETA soulsoilfarmland: Soul Soil Farmland 0.0.2 structure-helpers: Structure Helpers 3.0.0 team_reborn_energy: Energy 0.1.1 techreborn: Tech Reborn 3.7.3+build.192 terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1 terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1 terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1 terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1 terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1 terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1 terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2 terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1 terrestria: Terrestria 2.1.5+build.28 tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2 traverse: Traverse 3.0.1+build.8 unearthed: Unearthed 1.1.0 voyager: Voyager 1.0.0 worldedit: WorldEdit 7.2.0+a51fa43 Launched Version: fabric-loader-0.10.8-1.16.4 Backend library: LWJGL version 3.2.2 build 10 Backend API: Intel(R) UHD Graphics GL version 4.6.0 - Build 27.20.100.9168, Intel GL Caps: Using framebuffer using OpenGL 3.0 Using VBOs: Yes Is Modded: Definitely; Client brand changed to 'fabric' Type: Client (map_client.txt) Graphics mode: fancy Resource Packs: vanilla, Fabric Mods Current Language: English (US) CPU: 8x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz OptiFine Version: OptiFine_1.16.4_HD_U_G6 OptiFine Build: 20210117-001622 Render Distance Chunks: 8 Mipmaps: 4 Anisotropic Filtering: 1 Antialiasing: 0 Multitexture: false Shaders: null OpenGlVersion: 4.6.0 - Build 27.20.100.9168 OpenGlRenderer: Intel(R) UHD Graphics OpenGlVendor: Intel CpuCount: 8
-- OptiFabric --Details: OptiFine jar designed for: 1.16.4 OptiFine jar version: OptiFine_1.16.4_HD_U_G6 OptiFine jar status: Valid OptiFine installer OptiFine remapped jar: C:\Users\jjboc\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.4_HD_U_G6\Optifine-mapped.jar OptiFabric error: <None>

**Comment by paulevsGitch** [comment]
This is probably a boolean null pointer, I will try to fix this

**Comment by paulevsGitch** [comment]
Fixed in 0.9.1
