### ISSUE TITLE
Terminite Chandelier model is broken

### ISSUE THREAD

**Issue by saltyseadoggo** [paulevsGitch/BetterEnd#92]
As per the title, the Terminite chandelier's model shows missing textures that z-fight with the bulbs.

![2021-02-13_19 07 54](https://user-images.githubusercontent.com/69029346/107867441-b7bbf980-6e2f-11eb-9400-a4c9814eb6c1.png)

**Comment by paulevsGitch** [comment]
Fixed in 0.9.1
