### ISSUE TITLE
The blockstate of lanterns are inconsistent with vanilla

### ISSUE THREAD

**Issue by DLumina** [paulevsGitch/BetterEnd#94]
BetterEnd lanterns use "is_floor" to describe the behaviour, while vanilla (and BetterEndForge) lanterns use "hanging". This may cause further issues in cross-mod compatibility (When other mods trying to interact with lanterns).

**Comment by paulevsGitch** [comment]
BE lanterns use custom class (which is not a subclass of MC Lantern), this will not affect other mods
