### ISSUE TITLE
Overworld water generation.

### ISSUE THREAD

**Issue by lojarz** [paulevsGitch/BetterEnd#96]
For some reason, whenever I have this mod installed my overworld water generation gets completely messed up.
This may be an incompatibility issue because I have quite a few mods but it would be nice if you could look into it.
![image](https://user-images.githubusercontent.com/79212754/108227921-47b2b980-7136-11eb-8eb6-61bd069bb7a4.png)
![2021-02-17_15 41 24](https://user-images.githubusercontent.com/79212754/108228308-a5470600-7136-11eb-89f3-ac0b764be184.png)

**Comment by paulevsGitch** [comment]
BetterEnd doesn't affect water generation and vanilla biomes (except the End), this looks like wrong-placed caves filled with water

**Comment by lojarz** [comment]
Thanks for getting back to me, but I went through every mod in my mods folder to try and fix the issue, removing until the issue is gone. The only results I got were from the better end mod.

**Comment by lojarz** [comment]
I will go through all of my mods again and if you are right, I will close this issue.

**Comment by lojarz** [comment]
It seems like it was just a coincidence to do with another mod which for some reason fixed itself when I uninstalled better end, better caves had nothing to do with it though.
