### ISSUE TITLE
BetterEnd replacing blocks in vanilla realms

### ISSUE THREAD

**Issue by Turtle1311** [paulevsGitch/BetterEnd#97]
Vanilla
![javaw_yCmGZH6wcq](https://user-images.githubusercontent.com/17770361/108417406-8c515a00-71f5-11eb-8ddf-e2fa1674aa57.jpg)

With BetterEnd
![javaw_PfvCTAlDt5](https://user-images.githubusercontent.com/17770361/108417417-91aea480-71f5-11eb-9139-ae13c2647780.jpg)

A few friends and I concluded that BetterEnd was the issue as removing the mod resulted in normal textures, and testing by myself by turning my shaders off resulted in no changes other than the visual effects of the shader itself being gone

Without Shaders
![javaw_9f0Dj5oJXD](https://user-images.githubusercontent.com/17770361/108417937-33ce8c80-71f6-11eb-8480-8c4bc6556210.jpg)

If this was a known issue then I apologize

**Comment by paulevsGitch** [comment]
Hi it is known issue (#49), this can be fixed by changing
```
"changeChorusPlant [default: true]": true,
```
to
```
"changeChorusPlant [default: true]": false,
```
in the minecraft/config/betterend/generator.json
The reason of this issue was described in the link. If this will not help for some reason please reopen this issue
